import '../../../core/app_language.dart';

/// 네비게이터 선택 화면(Tab 1) 문구 — 임금체불/산재 두 내비게이터 중 하나를
/// 고르는 화면. 카드 문구는 홈 화면 도움 가이드(home_strings.dart의
/// wageNavTitle/wageNavDesc/injuryNavTitle/injuryNavDesc)와 같은 내용이지만,
/// 피처 간 역방향 의존을 피하기 위해 이 피처 안에 따로 둔다.
class NavigatorHomeStrings {
  NavigatorHomeStrings._();

  static const eyebrow = L10nText(
    ko: 'NAVIGATOR',
    en: 'NAVIGATOR',
    tr: "NAVİGATÖR",
    tg: "НАВИГАТОР",
    fil: "NAVIGATOR",
    ur: "نیویگیٹر",
    th: "ตัวนำทาง",
    ky: "НАВИГАТОР",
    km: "កម្មវិធីណែនាំ",
    id: "NAVIGATOR",
    si: "මාර්ගෝපදේශක",
    bn: "নেভিগেটর",
    my: "လမ်းညွှန်",
    mn: "УДИРДАМЖ",
    lo: "ຕົວນຳທາງ",
    tet: "NAVIGADÓR",
    ne: "नेभिगेटर",
    zh: 'NAVIGATOR',
    vi: 'NAVIGATOR',
    uz: "NAVIGATOR",
  );
  static const title = L10nText(
    ko: '네비게이터',
    en: 'Navigator',
    tr: "Rehber",
    tg: "Роҳнамо",
    fil: "Gabay",
    ur: "رہنما",
    th: "คู่มือ",
    ky: "Жол көрсөткүч",
    km: "មគ្គុទ្ទេសក៍",
    id: "Panduan",
    si: "මාර්ගෝපදේශය",
    bn: "গাইড",
    my: "လမ်းညွှန်",
    mn: "Удирдамж",
    lo: "ຄູ່ມື",
    tet: "Gia",
    ne: "गाइड",
    zh: '导航',
    vi: 'Điều hướng',
    uz: "Navigator",
  );
  static const subtitle = L10nText(
    ko: '어떤 문제인지 골라주시면 신고·신청까지 단계별로 안내해드려요.',
    en: 'Pick your situation and we’ll guide you step by step, all the way to filing.',
    tr: "Durumunuzu seçin, dosyalama sürecine kadar adım adım size rehberlik edelim.",
    tg: "Вазъияти худро интихоб кунед, мо шуморо қадам ба қадам то раванди пешниҳоди ариза роҳнамоӣ мекунем.",
    fil:
        "Piliin ang iyong sitwasyon, at gagabayan ka namin nang sunud-sunod hanggang sa proseso ng pag-file.",
    ur: "اپنی صورتحال کا انتخاب کریں، ہم فائلنگ کے عمل تک قدم بہ قدم آپ کی رہنمائی کریں گے۔",
    th: "กรุณาเลือกสถานะของคุณ เราจะแนะนำคุณทีละขั้นตอนจนกว่าจะเสร็จสิ้นกระบวนการยื่นเรื่อง",
    ky: "Абалыңызды тандаңыз, арыз берүү процессине чейин кадам сайын жол көрсөтөбүз.",
    km: "ជ្រើសរើសស្ថានភាពរបស់អ្នក ហើយយើងនឹងណែនាំអ្នកជាជំហានៗរហូតដល់ដំណើរការដាក់ពាក្យ។",
    id: "Pilih status Anda, dan kami akan memandu Anda langkah demi langkah melalui proses pengajuan.",
    si: "ඔබේ තත්ත්වය තෝරන්න, ගොනු කිරීමේ ක්‍රියාවලිය දක්වා අපි ඔබට පියවරෙන් පියවර මඟ පෙන්වමු.",
    bn: "আপনার পরিস্থিতি নির্বাচন করুন, আমরা আপনাকে ফাইল করার প্রক্রিয়া পর্যন্ত ধাপে ধাপে গাইড করব।",
    my: "သင်၏အခြေအနေကို ရွေးချယ်ပါ၊ တိုင်ကြားမှုလုပ်ငန်းစဉ်အထိ အဆင့်ဆင့် လမ်းညွှန်ပေးပါမည်။",
    mn: "Таны нөхцөл байдлыг сонгоно уу, бид танд өргөдөл гаргах үйл явцыг алхам алхмаар удирдан чиглүүлнэ.",
    lo: "ເລືອກສະຖານະຂອງທ່ານ, ພວກເຮົາຈະນຳພາທ່ານເທື່ອລະຂັ້ນຕອນຈົນເຖິງຂັ້ນຕອນການຍື່ນເອກະສານ.",
    tet:
        "Hili Ita-nia situasaun, ami sei orienta Ita pasu-ba-pasu to'o prosesu aprezentasaun.",
    ne: "आफ्नो अवस्था छान्नुहोस्, हामी तपाईंलाई फाइल गर्ने प्रक्रियासम्म चरण-चरण मार्गदर्शन गर्नेछौं।",
    zh: '选择您的情况，我们将逐步引导您完成申诉或申请。',
    vi: 'Chọn tình huống của bạn, chúng tôi sẽ hướng dẫn từng bước đến khi nộp đơn.',
    uz: "Vaziyatingizni tanlang va biz sizga bosqichma-bosqich, arizani topshirguncha yoʻl koʻrsatamiz.",
  );

  static const wageTitle = L10nText(
    ko: '임금체불 진정 안내',
    en: 'Unpaid wage report guide',
    tr: "Ödenmemiş ücret raporu rehberi",
    tg: "Дастур оид ба ҳисоботи музди меҳнати пардохтнашуда",
    fil: "Gabay sa ulat ng hindi nabayarang sahod",
    ur: "غیر ادا شدہ اجرت کی رپورٹ گائیڈ",
    th: "คู่มือการรายงานค่าจ้างที่ค้างชำระ",
    ky: "Төлөнбөгөн эмгек акы боюнча отчеттун көрсөтмөсү",
    km: "ការណែនាំអំពីរបាយការណ៍ប្រាក់ឈ្នួលមិនទាន់បានបង់",
    id: "Panduan laporan upah yang belum dibayar",
    si: "නොගෙවූ වැටුප් වාර්තා මාර්ගෝපදේශය",
    bn: "অপ্রদত্ত মজুরি রিপোর্ট গাইড",
    my: "မပေးချေရသေးသော လုပ်ခလစာ တိုင်ကြားခြင်း လမ်းညွှန်",
    mn: "Цалин хөлс төлөгдөөгүй тухай тайлангийн гарын авлага",
    lo: "ຄູ່ມືການລາຍງານຄ່າຈ້າງທີ່ຄ້າງຈ່າຍ",
    tet: "Gia relatóriu saláriu la selu",
    ne: "भुक्तानी नगरिएको ज्याला रिपोर्ट गाइड",
    zh: '拖欠工资申诉指南',
    vi: 'Hướng dẫn khiếu nại nợ lương',
    uz: "Toʻlanmagan ish haqi hisoboti boʻyicha qoʻllanma",
  );
  static const wageDesc = L10nText(
    ko: '단계별로 진정서까지 안내해드려요.',
    en: 'Step-by-step guidance all the way to filing a report.',
    tr: "Raporlama sürecine kadar adım adım rehberlik.",
    tg: "Роҳнамоии қадам ба қадам то раванди гузоришдиҳӣ.",
    fil: "Step-by-step na gabay hanggang sa proseso ng pag-uulat.",
    ur: "رپورٹنگ کے عمل تک مرحلہ وار رہنمائی۔",
    th: "คำแนะนำทีละขั้นตอนจนถึงกระบวนการรายงาน",
    ky: "Отчет берүү процессине чейинки кадам-кадам жол көрсөтүү.",
    km: "ការណែនាំជាជំហានៗរហូតដល់ដំណើរការរាយការណ៍។",
    id: "Panduan langkah demi langkah hingga proses pelaporan.",
    si: "වාර්තාකරණ ක්‍රියාවලිය දක්වා පියවරෙන් පියවර මග පෙන්වීම.",
    bn: "রিপোর্টিং প্রক্রিয়া পর্যন্ত ধাপে ধাপে নির্দেশনা।",
    my: "အစီရင်ခံခြင်း လုပ်ငန်းစဉ်အထိ အဆင့်ဆင့် လမ်းညွှန်ချက်။",
    mn: "Тайлагнах үйл явцын алхам алхмаар удирдамж.",
    lo: "ຄູ່ມືແນະນຳເທື່ອລະຂັ້ນຕອນຈົນເຖິງຂັ້ນຕອນການລາຍງານ.",
    tet: "Gia pasu-ba-pasu to'o prosesu relatóriu.",
    ne: "रिपोर्टिङ प्रक्रियासम्म चरण-दर-चरण मार्गदर्शन।",
    zh: '逐步引导您完成申诉书。',
    vi: 'Hướng dẫn từng bước đến khi nộp đơn khiếu nại.',
    uz: "Hisobot berishgacha bosqichma-bosqich yoʻriqnoma.",
  );
  static const injuryTitle = L10nText(
    ko: '산재처리 신청 안내',
    en: 'Workplace injury claim guide',
    tr: "İş kazası tazminat rehberi",
    tg: "Дастур оид ба ҷуброни садамаи меҳнатӣ",
    fil: "Gabay sa kompensasyon sa aksidente sa trabaho",
    ur: "کام کے حادثے کے معاوضے کی گائیڈ",
    th: "คู่มือการชดเชยอุบัติเหตุจากการทำงาน",
    ky: "Өндүрүштүк кырсыктан компенсация алуу боюнча көрсөтмө",
    km: "ការណែនាំអំពីសំណងគ្រោះថ្នាក់ការងារ",
    id: "Panduan kompensasi kecelakaan kerja",
    si: "රැකියා අනතුරු වන්දි මාර්ගෝපදේශය",
    bn: "শিল্প দুর্ঘটনা ক্ষতিপূরণ গাইড",
    my: "လုပ်ငန်းခွင်ထိခိုက်မှု လျော်ကြေး လမ်းညွှန်",
    mn: "Ажлын байран дахь ослын нөхөн олговрын гарын авлага",
    lo: "ຄູ່ມືການຊົດເຊີຍອຸບັດຕິເຫດໃນບ່ອນເຮັດວຽກ",
    tet: "Gia kompensasaun asidente servisu",
    ne: "कार्यस्थल दुर्घटना क्षतिपूर्ति गाइड",
    zh: '工伤申报指南',
    vi: 'Hướng dẫn yêu cầu bồi thường tai nạn lao động',
    uz: "Ish joyidagi jarohat boʻyicha daʼvo qoʻllanmasi",
  );
  static const injuryDesc = L10nText(
    ko: '단계별로 요양급여 신청까지 안내해드려요.',
    en: 'Step-by-step guidance all the way to your benefit claim.',
    tr: "Yardım talebinize kadar adım adım rehberlik.",
    tg: "Роҳнамоии қадам ба қадам то дархости кӯмаки шумо.",
    fil: "Step-by-step na gabay hanggang sa iyong kahilingan para sa tulong.",
    ur: "مدد کی درخواست تک مرحلہ وار رہنمائی۔",
    th: "คำแนะนำทีละขั้นตอนจนกว่าจะมีการร้องขอความช่วยเหลือ",
    ky: "Жардам сурооңузга чейинки кадам-кадам жол көрсөтүү.",
    km: "ការណែនាំជាជំហានៗរហូតដល់ការស្នើសុំជំនួយរបស់អ្នក។",
    id: "Panduan langkah demi langkah hingga permintaan bantuan Anda.",
    si: "උදව් ඉල්ලීම දක්වා පියවරෙන් පියවර මග පෙන්වීම.",
    bn: "আপনার সাহায্যের অনুরোধ পর্যন্ত ধাপে ধাপে নির্দেশনা।",
    my: "အကူအညီ တောင်းခံခြင်းအထိ အဆင့်ဆင့် လမ်းညွှန်ချက်။",
    mn: "Тусламж хүсэх хүртэлх алхам алхмаар удирдамж.",
    lo: "ຄູ່ມືແນະນຳເທື່ອລະຂັ້ນຕອນຈົນເຖິງການຮ້ອງຂໍຄວາມຊ່ວຍເຫຼືອຂອງທ່ານ.",
    tet: "Gia pasu-ba-pasu to'o pedidu ajuda.",
    ne: "तपाईंको मद्दत अनुरोधसम्म चरण-दर-चरण मार्गदर्शन।",
    zh: '逐步引导您完成疗养补偿申请。',
    vi: 'Hướng dẫn từng bước đến khi yêu cầu trợ cấp.',
    uz: "Nafaqangizni talab qilishgacha bosqichma-bosqich yoʻriqnoma.",
  );
}
