import '../../../core/app_language.dart';

enum WorkType { manufacturing, serving, delivery, other }

enum IncidentType { normal, overtime, accident }

extension WorkTypeLabel on WorkType {
  L10nText get label => switch (this) {
    WorkType.manufacturing => const L10nText(
      ko: '제조',
      en: 'Manufacturing',
      tr: "İmalat",
      tg: "Истеҳсолот",
      fil: "Paggawa",
      ur: "مینوفیکچرنگ",
      th: "การผลิต",
      ky: "Өндүрүш",
      km: "ផលិតកម្ម",
      id: "Manufaktur",
      si: "නිෂ්පාදනය",
      bn: "উৎপাদন",
      my: "ထုတ်လုပ်ရေး",
      mn: "Үйлдвэрлэл",
      lo: "ການຜະລິດ",
      tet: "Manufatura",
      ne: "उत्पादन",
      zh: '制造',
      vi: 'Sản xuất',
      uz: "Ishlab chiqarish",
    ),
    WorkType.serving => const L10nText(
      ko: '서빙',
      en: 'Serving',
      tr: "Hizmet",
      tg: "Хизматрасонӣ",
      fil: "Serbisyo",
      ur: "خدمات",
      th: "บริการ",
      ky: "Кызмат көрсөтүү",
      km: "សេវាកម្ម",
      id: "Layanan",
      si: "සේවාව",
      bn: "পরিষেবা",
      my: "ဝန်ဆောင်မှု",
      mn: "Үйлчилгээ",
      lo: "ບໍລິການ",
      tet: "Servisu",
      ne: "सेवा",
      zh: '服务员',
      vi: 'Phục vụ',
      uz: "Xizmat koʻrsatish",
    ),
    WorkType.delivery => const L10nText(
      ko: '배달',
      en: 'Delivery',
      tr: "Teslimat",
      tg: "Интиқол",
      fil: "Paghahatid",
      ur: "ڈیلیوری",
      th: "การจัดส่ง",
      ky: "Жеткирүү",
      km: "ការដឹកជញ្ជូន",
      id: "Pengiriman",
      si: "බෙදාහැරීම",
      bn: "ডেলিভারি",
      my: "ပို့ဆောင်ခြင်း",
      mn: "Хүргэлт",
      lo: "ການຈັດສົ່ງ",
      tet: "Entrega",
      ne: "डेलिभरी",
      zh: '配送',
      vi: 'Giao hàng',
      uz: "Yetkazib berish",
    ),
    WorkType.other => const L10nText(
      ko: '기타',
      en: 'Other',
      tr: "Diğer",
      tg: "Дигар",
      fil: "Iba pa",
      ur: "دیگر",
      th: "อื่น ๆ",
      ky: "Башка",
      km: "ផ្សេងៗ",
      id: "Lainnya",
      si: "වෙනත්",
      bn: "অন্যান্য",
      my: "အခြား",
      mn: "Бусад",
      lo: "ອື່ນໆ",
      tet: "Seluk",
      ne: "अन्य",
      zh: '其他',
      vi: 'Khác',
      uz: "Boshqa",
    ),
  };
}

extension IncidentTypeLabel on IncidentType {
  L10nText get label => switch (this) {
    IncidentType.normal => const L10nText(
      ko: '정상근무',
      en: 'Normal work',
      tr: "Normal çalışma",
      tg: "Кори муқаррарӣ",
      fil: "Normal na trabaho",
      ur: "معمول کا کام",
      th: "การทำงานปกติ",
      ky: "Кадимки жумуш",
      km: "ការងារធម្មតា",
      id: "Kerja normal",
      si: "සාමාන්‍ය වැඩ",
      bn: "সাধারণ কাজ",
      my: "ပုံမှန်အလုပ်",
      mn: "Энгийн ажил",
      lo: "ການເຮັດວຽກປົກກະຕິ",
      tet: "Servisu normál",
      ne: "सामान्य काम",
      zh: '正常工作',
      vi: 'Làm việc bình thường',
      uz: "Oddiy ish",
    ),
    IncidentType.overtime => const L10nText(
      ko: '연장근무',
      en: 'Overtime work',
      tr: "Fazla mesai",
      tg: "Коркарди изофагӣ",
      fil: "Overtime",
      ur: "اوور ٹائم",
      th: "ค่าล่วงเวลา",
      ky: "Ашыкча иштөө",
      km: "ម៉ោងបន្ថែម",
      id: "Lembur",
      si: "අතිකාල",
      bn: "ওভারটাইম",
      my: "အချိန်ပို",
      mn: "Илүү цаг",
      lo: "ຊົ່ວໂມງລ່ວງເວລາ",
      tet: "Oras-extra",
      ne: "अतिरिक्त समय",
      zh: '加班',
      vi: 'Làm thêm giờ',
      uz: "Qoʻshimcha ish",
    ),
    IncidentType.accident => const L10nText(
      ko: '사고·부상',
      en: 'Accident/injury',
      tr: "Kaza/yaralanma",
      tg: "Ҳодиса/ҷароҳат",
      fil: "Aksidente/pinsala",
      ur: "حادثہ/چوٹ",
      th: "อุบัติเหตุ/การบาดเจ็บ",
      ky: "Кырсык/жаракат",
      km: "គ្រោះថ្នាក់/របួស",
      id: "Kecelakaan/cedera",
      si: "අනතුර/තුවාල",
      bn: "দুর্ঘটনা/আঘাত",
      my: "မတော်တဆမှု/ထိခိုက်ဒဏ်ရာရမှု",
      mn: "Осол/гэмтэл",
      lo: "ອຸບັດຕິເຫດ/ການບາດເຈັບ",
      tet: "Asidente/kanek",
      ne: "दुर्घटना/चोट",
      zh: '事故·受伤',
      vi: 'Tai nạn/thương tích',
      uz: "Baxtsiz hodisa/jarohat",
    ),
  };
}
