import '../../../core/app_language.dart';

class WorkLogReportStrings {
  static const step = L10nText(
    ko: '근무기록장의 내용을 증거물로 출력하세요',
    en: 'Export your work log as supporting material',
    zh: '导出工作记录作为证明材料',
    vi: 'Xuất nhật ký làm việc làm tài liệu chứng minh',
    uz: 'Ish qaydlarini tasdiqlovchi hujjat sifatida chiqaring',
    tr: 'Çalışma kayıtlarınızı destekleyici belge olarak dışa aktarın',
    tg: "Сабтҳои кории худро ҳамчун ҳуҷҷати тасдиқкунанда содир кунед",
    fil:
        "I-export ang iyong mga record ng trabaho bilang sumusuportang dokumento",
    ur: "اپنے کام کے ریکارڈز کو معاون دستاویز کے طور پر ایکسپورٹ کریں",
    th: "ส่งออกบันทึกการทำงานของคุณเป็นเอกสารประกอบ",
    ky: "Иш тарыхыңызды колдоочу документ катары экспорттоңуз",
    km: "នាំចេញកំណត់ត្រាការងាររបស់អ្នកជាឯកសារគាំទ្រ",
    id: "Ekspor catatan kerja Anda sebagai dokumen pendukung",
    si: "ඔබේ වැඩ වාර්තා ආධාරක ලේඛනයක් ලෙස අපනයනය කරන්න",
    bn: "আপনার কাজের রেকর্ডগুলি সহায়ক নথি হিসাবে এক্সপোর্ট করুন",
    my: "သင်၏အလုပ်မှတ်တမ်းများကို အထောက်အထားစာရွက်စာတမ်းအဖြစ် ထုတ်ယူပါ။",
    mn: "Ажлын бүртгэлээ баримт бичиг болгон экспортлох",
    lo: "ສົ່ງອອກບັນທຶກການເຮັດວຽກຂອງທ່ານເປັນເອກະສານສະໜັບສະໜູນ",
    tet: "Eksporta Ita-nia rejistu servisu nu'udar dokumentu suporta",
    ne: "आफ्नो कार्य रेकर्डहरूलाई सहायक कागजातको रूपमा निर्यात गर्नुहोस्",
  );
  static const title = L10nText(
    ko: '근무기록 확인자료',
    en: 'Work log report',
    zh: '工作记录资料',
    vi: 'Báo cáo nhật ký làm việc',
    uz: 'Ish qaydlari hisoboti',
    tr: 'Çalışma kayıt raporu',
    tg: "Ҳисоботи сабтҳои корӣ",
    fil: "Ulat ng record ng trabaho",
    ur: "کام کے ریکارڈ کی رپورٹ",
    th: "รายงานบันทึกการทำงาน",
    ky: "Иш тарыхынын отчету",
    km: "របាយការណ៍កំណត់ត្រាការងារ",
    id: "Laporan catatan kerja",
    si: "වැඩ වාර්තා වාර්තාව",
    bn: "কাজের রেকর্ড রিপোর্ট",
    my: "အလုပ်မှတ်တမ်းအစီရင်ခံစာ",
    mn: "Ажлын бүртгэлийн тайлан",
    lo: "ລາຍງານບັນທຶກການເຮັດວຽກ",
    tet: "Relatóriu rejistu servisu",
    ne: "कार्य रेकर्ड रिपोर्ट",
  );
  static const lead = L10nText(
    ko: '오늘을 포함한 최근 30일의 저장된 출퇴근·휴게시간·위치 인증·메모를 불러옵니다. 한국어 또는 내 언어 PDF로 저장해 진정서에 첨부할 수 있습니다.',
    en: 'Load saved clock-in/out times, breaks, location verification and notes for the last 30 days including today. Save a Korean or translated PDF to attach to your complaint.',
    zh: '读取包括今天在内最近30天的上下班、休息、位置认证和备注记录。可保存韩语或所选语言PDF，作为申诉附件。',
    vi: 'Tải giờ vào/ra, giờ nghỉ, xác minh vị trí và ghi chú trong 30 ngày gồm hôm nay. Lưu PDF tiếng Hàn hoặc ngôn ngữ của bạn để đính kèm đơn.',
    uz: 'Bugunni ham hisobga olgan oxirgi 30 kunning kelish/ketish, tanaffus, joylashuv tasdigʻi va izohlarini yuklang. Shikoyatga ilova qilish uchun koreyscha yoki oʻz tilingizda PDF saqlang.',
    tr: 'Bugün dahil son 30 günün giriş/çıkış, mola, konum doğrulama ve not kayıtlarını yükleyin. Şikayete eklemek için Korece veya kendi dilinizde PDF kaydedin.',
    tg: "Сабтҳои вуруд/хуруҷ, танаффус, тасдиқи макон ва қайдҳои 30 рӯзи охир, аз ҷумла имрӯзро бор кунед. Барои илова кардан ба шикоят PDF-ро бо забони кореягӣ ё забони худ захира кунед.",
    fil:
        "I-load ang mga record ng pagpasok/paglabas, break, pagpapatunay ng lokasyon, at tala para sa huling 30 araw, kasama ang ngayon. I-save ang PDF sa Korean o sa iyong wika upang ilakip sa reklamo.",
    ur: "آج سمیت پچھلے 30 دنوں کے ان/آؤٹ، بریک، مقام کی تصدیق اور نوٹ کے ریکارڈز اپ لوڈ کریں۔ شکایت میں شامل کرنے کے لیے کورین یا اپنی زبان میں پی ڈی ایف محفوظ کریں۔",
    th: "อัปโหลดบันทึกการเข้า/ออก, การพัก, การยืนยันตำแหน่ง และบันทึกย่อในช่วง 30 วันที่ผ่านมา รวมถึงวันนี้ บันทึกเป็นไฟล์ PDF ในภาษาเกาหลีหรือภาษาของคุณเพื่อแนบไปกับการร้องเรียน",
    ky: "Бүгүнкү күндү кошкондо акыркы 30 күндүн кирүү/чыгуу, тыныгуу, жайгашкан жерди текшерүү жана эскертме жазууларын жүктөңүз. Арызга кошуу үчүн корей же өз тилиңизде PDF сактаңыз.",
    km: "ផ្ទុកឡើងកំណត់ត្រាចូល/ចេញ សម្រាក ការផ្ទៀងផ្ទាត់ទីតាំង និងកំណត់ចំណាំសម្រាប់ 30 ថ្ងៃចុងក្រោយ រួមទាំងថ្ងៃនេះ។ រក្សាទុកជា PDF ជាភាសាកូរ៉េ ឬភាសារបស់អ្នក ដើម្បីភ្ជាប់ជាមួយពាក្យបណ្តឹង។",
    id: "Muat catatan masuk/keluar, istirahat, verifikasi lokasi, dan catatan untuk 30 hari terakhir, termasuk hari ini. Simpan PDF dalam bahasa Korea atau bahasa Anda sendiri untuk dilampirkan pada keluhan.",
    si: "අද ඇතුළුව පසුගිය දින 30 සඳහා ඇතුල්වීම්/පිටවීම්, විවේක, ස්ථාන සත්‍යාපන සහ සටහන් වාර්තා පූරණය කරන්න. පැමිණිල්ලට ඇමිණීම සඳහා කොරියානු හෝ ඔබේ භාෂාවෙන් PDF සුරකින්න.",
    bn: "আজ সহ গত 30 দিনের প্রবেশ/প্রস্থান, বিরতি, অবস্থান যাচাইকরণ এবং নোটের রেকর্ডগুলি আপলোড করুন। অভিযোগের সাথে সংযুক্ত করার জন্য কোরিয়ান বা আপনার নিজের ভাষায় PDF সংরক্ষণ করুন।",
    my: "ယနေ့အပါအဝင် နောက်ဆုံး 30 ရက်အတွင်း ဝင်/ထွက်၊ အနားယူချိန်၊ တည်နေရာအတည်ပြုချက်နှင့် မှတ်စုမှတ်တမ်းများကို တင်ပါ။ တိုင်ကြားချက်တွင် ထည့်သွင်းရန် ကိုရီးယားဘာသာ သို့မဟုတ် သင့်ဘာသာစကားဖြင့် PDF ကို သိမ်းဆည်းပါ။",
    mn: "Өнөөдрийг оролцуулаад сүүлийн 30 өдрийн ирэх/явах, завсарлага, байршлын баталгаажуулалт болон тэмдэглэлийн бүртгэлийг татаж авна уу. Гомдолд хавсаргахын тулд Солонгос эсвэл таны хэлээр PDF хэлбэрээр хадгална уу.",
    lo: "ອັບໂຫຼດບັນທຶກການເຂົ້າ/ອອກ, ການພັກຜ່ອນ, ການຢືນຢັນສະຖານທີ່ ແລະ ບັນທຶກຕ່າງໆ ຂອງ 30 ມື້ສຸດທ້າຍ ລວມທັງມື້ນີ້. ບັນທຶກເປັນ PDF ເປັນພາສາເກົາຫຼີ ຫຼື ພາສາຂອງທ່ານເອງ ເພື່ອເພີ່ມໃສ່ຄຳຮ້ອງຮຽນ.",
    tet:
        "Karega rejistu tama/sai, deskansa, verifikasaun fatin, no nota husi loron 30 ikus, inklui ohin. Guarda PDF iha lian Koreanu ka Ita-nia lian rasik atu tau ba keixa.",
    ne: "आज सहित पछिल्लो 30 दिनको प्रवेश/निकास, विश्राम, स्थान प्रमाणीकरण र नोट रेकर्डहरू अपलोड गर्नुहोस्। उजुरीमा संलग्न गर्न कोरियन वा तपाईंको आफ्नै भाषामा PDF बचत गर्नुहोस्।",
  );
  static const demo = L10nText(
    ko: '데모 기록 - 실제 제출용이 아닙니다. 로그인하면 내 기록을 불러옵니다.',
    en: 'DEMO records - not for submission. Sign in to load your own records.',
    zh: '演示记录 - 不可提交。登录后读取本人记录。',
    vi: 'Dữ liệu DEMO - không dùng để nộp. Đăng nhập để tải bản ghi của bạn.',
    uz: 'DEMO qaydlar - topshirish uchun emas. Oʻz qaydlaringizni yuklash uchun kiring.',
    tr: 'DEMO kayıtları - başvuru için kullanılamaz. Kendi kayıtlarınız için giriş yapın.',
    tg: "Сабтҳои НАМУНАВӢ - барои ариза истифода намешаванд. Барои сабтҳои худ ворид шавед.",
    fil:
        "DEMO records - hindi magagamit para sa aplikasyon. Mag-log in para sa iyong sariling mga record.",
    ur: "ڈیمو ریکارڈز - درخواست کے لیے استعمال نہیں کیے جا سکتے۔ اپنے ریکارڈز کے لیے لاگ ان کریں۔",
    th: "บันทึก DEMO - ไม่สามารถใช้สำหรับการสมัครได้ กรุณาเข้าสู่ระบบเพื่อดูบันทึกของคุณเอง",
    ky: "ДЕМО жазуулары - арыз үчүн колдонулбайт. Өз жазууларыңыз үчүн кириңиз.",
    km: "កំណត់ត្រាសាកល្បង - មិនអាចប្រើសម្រាប់ការដាក់ពាក្យបានទេ។ ចូលដើម្បីមើលកំណត់ត្រាផ្ទាល់ខ្លួនរបស់អ្នក។",
    id: "Catatan DEMO - tidak dapat digunakan untuk pengajuan. Masuk untuk catatan Anda sendiri.",
    si: "ආදර්ශන වාර්තා - අයදුම්පත් සඳහා භාවිතා කළ නොහැක. ඔබේම වාර්තා සඳහා පුරනය වන්න.",
    bn: "ডেমো রেকর্ড - আবেদনের জন্য ব্যবহার করা যাবে না। আপনার নিজের রেকর্ডের জন্য লগইন করুন।",
    my: "DEMO မှတ်တမ်းများ - လျှောက်လွှာတင်ရန် အသုံးမပြုနိုင်ပါ။ သင်၏ကိုယ်ပိုင်မှတ်တမ်းများအတွက် လော့ဂ်အင်ဝင်ပါ။",
    mn: "ДЕМО бүртгэлүүд - өргөдөлд ашиглах боломжгүй. Өөрийн бүртгэлээ харахын тулд нэвтэрнэ үү.",
    lo: "ບັນທຶກ DEMO - ບໍ່ສາມາດໃຊ້ສຳລັບການສະໝັກໄດ້. ເຂົ້າສູ່ລະບົບເພື່ອເບິ່ງບັນທຶກຂອງທ່ານເອງ.",
    tet:
        "Rejistu DEMO - la bele uza ba aplikasaun. Log in ba Ita-nia rejistu rasik.",
    ne: "डेमो रेकर्डहरू - आवेदनको लागि प्रयोग गर्न सकिँदैन। आफ्ना रेकर्डहरूको लागि लगइन गर्नुहोस्।",
  );
  static const note = L10nText(
    ko: '사용자가 앱에 저장한 기록의 사본입니다. 위치 인증은 해당 날짜에 저장된 상태이며 출근·퇴근 각각의 위치나 인증 시각을 증명하지 않습니다. 미기록은 결근을 뜻하지 않습니다. 메모와 주소는 원문 그대로 출력됩니다.',
    en: 'A copy of records saved by the user. Location status is recorded per day; it does not certify separate clock-in/out locations or verification times. Missing records do not mean absence. Notes and addresses retain their original text.',
    zh: '本资料为用户保存记录的副本。位置状态按日记录，不证明上下班各自的位置或认证时间。无记录不代表缺勤。备注和地址保持原文。',
    vi: 'Bản sao dữ liệu người dùng đã lưu. Trạng thái vị trí theo ngày không xác nhận riêng vị trí vào/ra hay thời điểm xác minh. Thiếu bản ghi không có nghĩa là vắng mặt. Ghi chú và địa chỉ giữ nguyên văn.',
    uz: 'Foydalanuvchi saqlagan qaydlar nusxasi. Kunlik joylashuv holati alohida kelish/ketish joylari yoki tasdiqlash vaqtini isbotlamaydi. Qayd yoʻqligi ishga kelmaganlikni anglatmaydi. Izoh va manzillar asl holida chiqariladi.',
    tr: 'Kullanıcının kaydettiği verilerin kopyasıdır. Günlük konum durumu, ayrı giriş/çıkış konumlarını veya doğrulama saatini kanıtlamaz. Kayıt olmaması devamsızlık anlamına gelmez. Notlar ve adresler aynen aktarılır.',
    tg: "Ин нусхаи маълумоти сабтшудаи корбар аст. Вазъияти макони ҳаррӯза, маконҳои алоҳидаи вуруд/хуруҷ ё вақти тасдиқро исбот намекунад. Набудани сабт маънои ғоиб буданро надорад. Қайдҳо ва суроғаҳо дақиқ интиқол дода мешаванд.",
    fil:
        "Ito ay kopya ng data na naitala ng user. Ang pang-araw-araw na status ng lokasyon ay hindi nagpapatunay ng magkahiwalay na lokasyon ng pagpasok/paglabas o oras ng pagpapatunay. Ang kawalan ng record ay hindi nangangahulugang pagliban. Ang mga tala at address ay inilipat nang eksakto.",
    ur: "یہ صارف کے محفوظ کردہ ڈیٹا کی ایک کاپی ہے۔ روزانہ کی مقام کی حیثیت الگ الگ ان/آؤٹ مقامات یا تصدیق کے وقت کو ثابت نہیں کرتی۔ ریکارڈ کی عدم موجودگی کا مطلب غیر حاضری نہیں ہے۔ نوٹس اور پتے جوں کے توں منتقل کیے جاتے ہیں۔",
    th: "นี่คือสำเนาข้อมูลที่ผู้ใช้บันทึกไว้ สถานะตำแหน่งรายวันไม่ได้พิสูจน์ตำแหน่งการเข้า/ออกที่แยกจากกัน หรือเวลาการยืนยัน การไม่มีบันทึกไม่ได้หมายถึงการขาดงาน บันทึกย่อและที่อยู่จะถูกส่งออกตามที่บันทึกไว้",
    ky: "Колдонуучу сактаган маалыматтардын көчүрмөсү. Күндөлүк жайгашкан жердин абалы, өзүнчө кирүү/чыгуу жайгашкан жерлерин же текшерүү убактысын далилдебейт. Жазуунун жоктугу жумушка келбегендикти билдирбейт. Эскертмелер жана даректер так ошондой өткөрүлүп берилет.",
    km: "នេះគឺជាច្បាប់ចម្លងនៃទិន្នន័យដែលបានរក្សាទុកដោយអ្នកប្រើប្រាស់។ ស្ថានភាពទីតាំងប្រចាំថ្ងៃមិនបញ្ជាក់ពីទីតាំងចូល/ចេញដាច់ដោយឡែក ឬពេលវេលាផ្ទៀងផ្ទាត់ទេ។ ការមិនមានកំណត់ត្រាមិនមានន័យថាអវត្តមាននោះទេ។ កំណត់ចំណាំ និងអាសយដ្ឋានត្រូវបានផ្ទេរដូចដើម។",
    id: "Ini adalah salinan data yang dicatat oleh pengguna. Status lokasi harian tidak membuktikan lokasi masuk/keluar yang terpisah atau waktu verifikasi. Tidak adanya catatan tidak berarti ketidakhadiran. Catatan dan alamat diekspor apa adanya.",
    si: "මෙය පරිශීලකයා විසින් සුරකින ලද දත්තවල පිටපතකි. දෛනික ස්ථාන තත්ත්වය, වෙනම ඇතුල්වීමේ/පිටවීමේ ස්ථාන හෝ සත්‍යාපන වේලාව ඔප්පු නොකරයි. වාර්තාවක් නොමැති වීමෙන් නොපැමිණීම අදහස් නොවේ. සටහන් සහ ලිපිනයන් එලෙසම මාරු කරනු ලැබේ.",
    bn: "এটি ব্যবহারকারীর সংরক্ষিত ডেটার একটি অনুলিপি। দৈনিক অবস্থানের স্থিতি, পৃথক প্রবেশ/প্রস্থান অবস্থান বা যাচাইকরণের সময় প্রমাণ করে না। রেকর্ডের অভাব অনুপস্থিতি বোঝায় না। নোট এবং ঠিকানাগুলি হুবহু স্থানান্তরিত হয়।",
    my: "၎င်းသည် အသုံးပြုသူ မှတ်တမ်းတင်ထားသော ဒေတာ၏ မိတ္တူဖြစ်သည်။ နေ့စဉ်တည်နေရာအခြေအနေသည် သီးခြားဝင်/ထွက်တည်နေရာများ သို့မဟုတ် အတည်ပြုချိန်ကို သက်သေမပြနိုင်ပါ။ မှတ်တမ်းမရှိခြင်းသည် ပျက်ကွက်ခြင်းကို မဆိုလိုပါ။ မှတ်စုများနှင့် လိပ်စာများကို အတိအကျ ဖော်ပြထားပါသည်။",
    mn: "Энэ нь хэрэглэгчийн хадгалсан өгөгдлийн хуулбар юм. Өдөр тутмын байршлын статус нь ирэх/явах байршил эсвэл баталгаажуулалтын цагийг баталгаажуулахгүй. Бүртгэл байхгүй байх нь ажил тасалсан гэсэн үг биш. Тэмдэглэл болон хаягийг яг таг хуулбарлана.",
    lo: "ນີ້ແມ່ນສຳເນົາຂໍ້ມູນທີ່ຜູ້ໃຊ້ໄດ້ບັນທຶກໄວ້. ສະຖານະສະຖານທີ່ປະຈຳວັນບໍ່ໄດ້ພິສູດສະຖານທີ່ເຂົ້າ/ອອກແຍກຕ່າງຫາກ ຫຼື ເວລາຢືນຢັນ. ການບໍ່ມີບັນທຶກບໍ່ໄດ້ໝາຍເຖິງການຂາດວຽກ. ບັນທຶກ ແລະ ທີ່ຢູ່ຈະຖືກໂອນຍ້າຍຕາມເດີມ.",
    tet:
        "Ida ne'e kópia husi dadus ne'ebé utilizadór rejista. Estatutu fatin diáriu la prova fatin tama/sai separadu ka oras verifikasaun. La iha rejistu la signifika la mai servisu. Nota no enderezu sira sei transfere hanesan.",
    ne: "यो प्रयोगकर्ताले बचत गरेको डेटाको प्रतिलिपि हो। दैनिक स्थान स्थितिले छुट्टै प्रवेश/निकास स्थानहरू वा प्रमाणीकरण समय प्रमाणित गर्दैन। रेकर्ड नहुनुको अर्थ अनुपस्थिति होइन। नोटहरू र ठेगानाहरू जस्ताको तस्तै हस्तान्तरण गरिन्छ।",
  );
  static const load = L10nText(
    ko: '기록 새로 불러오기',
    en: 'Reload records',
    zh: '重新读取记录',
    vi: 'Tải lại bản ghi',
    uz: 'Qaydlarni qayta yuklash',
    tr: 'Kayıtları yeniden yükle',
    tg: "Сабтҳоро аз нав бор кунед",
    fil: "I-reload ang mga record",
    ur: "ریکارڈز دوبارہ لوڈ کریں",
    th: "โหลดบันทึกใหม่",
    ky: "Жазууларды кайра жүктөө",
    km: "ផ្ទុកកំណត់ត្រាឡើងវិញ",
    id: "Muat ulang catatan",
    si: "වාර්තා නැවත පූරණය කරන්න",
    bn: "রেকর্ডগুলি পুনরায় লোড করুন",
    my: "မှတ်တမ်းများ ပြန်တင်ပါ",
    mn: "Бүртгэлүүдийг дахин татах",
    lo: "ໂຫຼດບັນທຶກຄືນໃໝ່",
    tet: "Karega fali rejistu sira",
    ne: "रेकर्डहरू पुन: लोड गर्नुहोस्",
  );
  static const loading = L10nText(
    ko: '근무기록을 불러오는 중입니다…',
    en: 'Loading work records…',
    zh: '正在读取工作记录…',
    vi: 'Đang tải nhật ký…',
    uz: 'Ish qaydlari yuklanmoqda…',
    tr: 'Çalışma kayıtları yükleniyor…',
    tg: "Сабтҳои корӣ бор карда мешаванд…",
    fil: "Naglo-load ng mga record ng trabaho…",
    ur: "کام کے ریکارڈز لوڈ ہو رہے ہیں…",
    th: "กำลังโหลดบันทึกการทำงาน…",
    ky: "Иш жазуулары жүктөлүүдө…",
    km: "កំពុងផ្ទុកកំណត់ត្រាការងារ…",
    id: "Memuat catatan kerja…",
    si: "වැඩ වාර්තා පූරණය වෙමින් පවතී...",
    bn: "কাজের রেকর্ড লোড হচ্ছে…",
    my: "အလုပ်မှတ်တမ်းများ တင်နေသည်…",
    mn: "Ажлын бүртгэлүүдийг татаж байна…",
    lo: "ກຳລັງໂຫຼດບັນທຶກການເຮັດວຽກ…",
    tet: "Rejistu servisu sira karega hela…",
    ne: "कार्य रेकर्डहरू लोड हुँदैछन्…",
  );
  static const error = L10nText(
    ko: '기록을 불러오지 못했습니다. 로그인 상태와 연결을 확인하고 다시 시도하세요.',
    en: 'Could not load records. Check your sign-in and connection, then retry.',
    zh: '读取失败。请检查登录和网络后重试。',
    vi: 'Không tải được. Kiểm tra đăng nhập, kết nối rồi thử lại.',
    uz: 'Yuklab boʻlmadi. Hisob va ulanishni tekshirib, qayta urinib koʻring.',
    tr: 'Kayıtlar yüklenemedi. Giriş ve bağlantınızı kontrol edip yeniden deneyin.',
    tg: "Сабтҳо бор карда нашуданд. Вуруд ва пайвасти худро тафтиш кунед ва дубора кӯшиш кунед.",
    fil:
        "Hindi ma-load ang mga record. Pakisuri ang iyong pag-login at koneksyon at subukang muli.",
    ur: "ریکارڈز لوڈ نہیں ہو سکے۔ براہ کرم اپنا لاگ ان اور کنکشن چیک کریں اور دوبارہ کوشش کریں۔",
    th: "ไม่สามารถโหลดบันทึกได้ กรุณาตรวจสอบการเข้าสู่ระบบและการเชื่อมต่อของคุณ แล้วลองอีกครั้ง",
    ky: "Жазууларды жүктөө мүмкүн болгон жок. Кирүү жана байланышыңызды текшерип, кайра аракет кылыңыз.",
    km: "មិនអាចផ្ទុកកំណត់ត្រាបានទេ។ សូមពិនិត្យមើលការចូល និងការតភ្ជាប់របស់អ្នក ហើយព្យាយាមម្តងទៀត។",
    id: "Gagal memuat catatan. Periksa login dan koneksi Anda, lalu coba lagi.",
    si: "වාර්තා පූරණය කිරීමට නොහැකි විය. කරුණාකර ඔබේ පිවිසුම සහ සම්බන්ධතාවය පරීක්ෂා කර නැවත උත්සාහ කරන්න.",
    bn: "রেকর্ড লোড করা যায়নি। আপনার লগইন এবং সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।",
    my: "မှတ်တမ်းများ တင်မရပါ။ သင်၏ လော့ဂ်အင်နှင့် ချိတ်ဆက်မှုကို စစ်ဆေးပြီး ထပ်ကြိုးစားပါ။",
    mn: "Бүртгэлүүдийг татаж чадсангүй. Нэвтрэх болон холболтоо шалгаад дахин оролдоно уу.",
    lo: "ບໍ່ສາມາດໂຫຼດບັນທຶກໄດ້. ກວດສອບການເຂົ້າສູ່ລະບົບ ແລະ ການເຊື່ອມຕໍ່ຂອງທ່ານ ແລ້ວລອງໃໝ່ອີກຄັ້ງ.",
    tet:
        "Rejistu sira la konsege karega. Verifika Ita-nia log in no koneksaun, depois koko fali.",
    ne: "रेकर्डहरू लोड गर्न सकिएन। आफ्नो लगइन र जडान जाँच गर्नुहोस् र फेरि प्रयास गर्नुहोस्।",
  );
  static const empty = L10nText(
    ko: '최근 30일 동안 저장된 기록이 없습니다.',
    en: 'No saved records in the last 30 days.',
    zh: '最近30天没有保存的记录。',
    vi: 'Không có bản ghi trong 30 ngày qua.',
    uz: 'Oxirgi 30 kunda saqlangan qaydlar yoʻq.',
    tr: 'Son 30 günde kaydedilmiş kayıt yok.',
    tg: "Дар 30 рӯзи охир сабти қайдшуда вуҷуд надорад.",
    fil: "Walang naitalang record sa huling 30 araw.",
    ur: "پچھلے 30 دنوں میں کوئی ریکارڈ محفوظ نہیں کیا گیا۔",
    th: "ไม่มีบันทึกที่บันทึกไว้ในช่วง 30 วันที่ผ่านมา",
    ky: "Акыркы 30 күндө сакталган жазуулар жок.",
    km: "គ្មានកំណត់ត្រាដែលបានរក្សាទុកក្នុងរយៈពេល 30 ថ្ងៃចុងក្រោយទេ។",
    id: "Tidak ada catatan yang direkam dalam 30 hari terakhir.",
    si: "පසුගිය දින 30 තුළ වාර්තාගත වාර්තා නොමැත.",
    bn: "গত 30 দিনে কোনো রেকর্ড সংরক্ষিত হয়নি।",
    my: "နောက်ဆုံး 30 ရက်အတွင်း မှတ်တမ်းတင်ထားသော မှတ်တမ်းများ မရှိပါ။",
    mn: "Сүүлийн 30 өдөрт бүртгэгдсэн бүртгэл байхгүй.",
    lo: "ບໍ່ມີບັນທຶກທີ່ຖືກບັນທຶກໄວ້ໃນ 30 ມື້ສຸດທ້າຍ.",
    tet: "La iha rejistu ne'ebé rejista iha loron 30 ikus.",
    ne: "पछिल्लो 30 दिनमा कुनै रेकर्डहरू बचत गरिएका छैनन्।",
  );
  static const pdfError = L10nText(
    ko: 'PDF를 만들거나 저장하지 못했습니다. 다시 시도하세요.',
    en: 'Could not create or save the PDF. Please retry.',
    zh: '无法生成或保存PDF，请重试。',
    vi: 'Không tạo hoặc lưu được PDF. Hãy thử lại.',
    uz: 'PDF yaratilmadi yoki saqlanmadi. Qayta urinib koʻring.',
    tr: 'PDF oluşturulamadı veya kaydedilemedi. Yeniden deneyin.',
    tg: "PDF сохта ё захира карда нашуд. Дубора кӯшиш кунед.",
    fil: "Hindi makagawa o makapag-save ng PDF. Subukang muli.",
    ur: "پی ڈی ایف نہیں بن سکی یا محفوظ نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
    th: "ไม่สามารถสร้างหรือบันทึก PDF ได้ กรุณาลองอีกครั้ง",
    ky: "PDF түзүлгөн же сакталган жок. Кайра аракет кылыңыз.",
    km: "មិនអាចបង្កើត ឬរក្សាទុក PDF បានទេ។ សូមព្យាយាមម្តងទៀត។",
    id: "Gagal membuat atau menyimpan PDF. Coba lagi.",
    si: "PDF සෑදීමට හෝ සුරැකීමට නොහැකි විය. නැවත උත්සාහ කරන්න.",
    bn: "PDF তৈরি বা সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।",
    my: "PDF ဖန်တီး၍မရပါ သို့မဟုတ် သိမ်းဆည်း၍မရပါ။ ထပ်ကြိုးစားပါ။",
    mn: "PDF үүсгэж эсвэл хадгалж чадсангүй. Дахин оролдоно уу.",
    lo: "ບໍ່ສາມາດສ້າງ ຫຼື ບັນທຶກ PDF ໄດ້. ລອງໃໝ່ອີກຄັ້ງ.",
    tet: "La konsege kria ka guarda PDF. Koko fali.",
    ne: "PDF सिर्जना वा बचत गर्न सकिएन। फेरि प्रयास गर्नुहोस्।",
  );
  static const koreanPdf = L10nText(
    ko: '한국어 PDF 저장',
    en: 'Save Korean PDF',
    zh: '保存韩语PDF',
    vi: 'Lưu PDF tiếng Hàn',
    uz: 'Koreyscha PDF saqlash',
    tr: 'Korece PDF kaydet',
    tg: "PDF-ро бо забони кореягӣ захира кунед",
    fil: "I-save ang PDF sa Korean",
    ur: "کورین پی ڈی ایف محفوظ کریں",
    th: "บันทึก PDF ภาษาเกาหลี",
    ky: "Корей тилинде PDF сактоо",
    km: "រក្សាទុក PDF ជាភាសាកូរ៉េ",
    id: "Simpan PDF dalam bahasa Korea",
    si: "කොරියානු PDF සුරකින්න",
    bn: "কোরিয়ান PDF সংরক্ষণ করুন",
    my: "ကိုရီးယားဘာသာဖြင့် PDF သိမ်းဆည်းပါ",
    mn: "Солонгос хэлээр PDF хадгалах",
    lo: "ບັນທຶກ PDF ເປັນພາສາເກົາຫຼີ",
    tet: "Guarda PDF iha lian Koreanu",
    ne: "कोरियनमा PDF बचत गर्नुहोस्",
  );
  static const myPdf = L10nText(
    ko: '내 언어 PDF 저장',
    en: 'Save PDF in my language',
    zh: '保存所选语言PDF',
    vi: 'Lưu PDF ngôn ngữ của tôi',
    uz: 'Oʻz tilimda PDF saqlash',
    tr: 'Kendi dilimde PDF kaydet',
    tg: "PDF-ро бо забони худам захира кунед",
    fil: "I-save ang PDF sa aking wika",
    ur: "اپنی زبان میں پی ڈی ایف محفوظ کریں",
    th: "บันทึก PDF ในภาษาของฉัน",
    ky: "Өз тилимде PDF сактоо",
    km: "រក្សាទុក PDF ជាភាសារបស់ខ្ញុំ",
    id: "Simpan PDF dalam bahasa saya",
    si: "මගේ භාෂාවෙන් PDF සුරකින්න",
    bn: "আমার নিজের ভাষায় PDF সংরক্ষণ করুন",
    my: "ကျွန်ုပ်၏ဘာသာစကားဖြင့် PDF သိမ်းဆည်းပါ",
    mn: "Миний хэлээр PDF хадгалах",
    lo: "ບັນທຶກ PDF ເປັນພາສາຂອງຂ້ອຍ",
    tet: "Guarda PDF iha ha'u-nia lian rasik",
    ne: "मेरो आफ्नै भाषामा PDF बचत गर्नुहोस्",
  );
  static const preview = L10nText(
    ko: 'PDF 미리보기 및 인쇄',
    en: 'Preview and print PDF',
    zh: '预览及打印PDF',
    vi: 'Xem và in PDF',
    uz: 'PDFni koʻrish va chop etish',
    tr: 'PDF önizleme ve yazdırma',
    tg: "Пешнамоиш ва чоп кардани PDF",
    fil: "I-preview at i-print ang PDF",
    ur: "پی ڈی ایف کا پیش منظر اور پرنٹ",
    th: "ดูตัวอย่างและพิมพ์ PDF",
    ky: "PDF алдын ала көрүү жана басып чыгаруу",
    km: "មើលជាមុន និងបោះពុម្ព PDF",
    id: "Pratinjau dan cetak PDF",
    si: "PDF පෙරදසුන සහ මුද්‍රණය",
    bn: "PDF পূর্বরূপ এবং মুদ্রণ",
    my: "PDF ကြိုတင်ကြည့်ရှုပြီး ပုံနှိပ်ပါ",
    mn: "PDF-ийг урьдчилан харах, хэвлэх",
    lo: "ເບິ່ງຕົວຢ່າງ ແລະ ພິມ PDF",
    tet: "Pre-vizualiza no imprime PDF",
    ne: "PDF पूर्वावलोकन र प्रिन्ट गर्नुहोस्",
  );
  static const date = L10nText(
    ko: '날짜',
    en: 'Date',
    zh: '日期',
    vi: 'Ngày',
    uz: 'Sana',
    tr: 'Tarih',
    tg: "Сана",
    fil: "Petsa",
    ur: "تاریخ",
    th: "วันที่",
    ky: "Дата",
    km: "កាលបរិច្ឆេទ",
    id: "Tanggal",
    si: "දිනය",
    bn: "তারিখ",
    my: "ရက်စွဲ",
    mn: "Огноо",
    lo: "ວັນທີ",
    tet: "Data",
    ne: "मिति",
  );
  static const clockIn = L10nText(
    ko: '출근',
    en: 'Clock in',
    zh: '上班',
    vi: 'Vào',
    uz: 'Kelish',
    tr: 'Giriş',
    tg: "Вуруд",
    fil: "Pagpasok",
    ur: "ان",
    th: "เข้า",
    ky: "Кирүү",
    km: "ចូល",
    id: "Masuk",
    si: "ඇතුල්වීම",
    bn: "প্রবেশ",
    my: "ဝင်ရောက်ချိန်",
    mn: "Ирэх",
    lo: "ເຂົ້າ",
    tet: "Tama",
    ne: "प्रवेश",
  );
  static const clockOut = L10nText(
    ko: '퇴근',
    en: 'Clock out',
    zh: '下班',
    vi: 'Ra',
    uz: 'Ketish',
    tr: 'Çıkış',
    tg: "Хуруҷ",
    fil: "Paglabas",
    ur: "آؤٹ",
    th: "ออก",
    ky: "Чыгуу",
    km: "ចេញ",
    id: "Keluar",
    si: "පිටවීම",
    bn: "প্রস্থান",
    my: "ထွက်ခွာချိန်",
    mn: "Явах",
    lo: "ອອກ",
    tet: "Sai",
    ne: "निकास",
  );
  static const breaks = L10nText(
    ko: '휴게(분)',
    en: 'Break (min)',
    zh: '休息(分)',
    vi: 'Nghỉ (phút)',
    uz: 'Tanaffus (daq)',
    tr: 'Mola (dk)',
    tg: "Танаффус (дақ)",
    fil: "Break (min)",
    ur: "بریک (منٹ)",
    th: "พัก (นาที)",
    ky: "Тыныгуу (мүнөт)",
    km: "សម្រាក (នាទី)",
    id: "Istirahat (menit)",
    si: "විවේකය (විනාඩි)",
    bn: "বিরতি (মিনিট)",
    my: "အနားယူချိန် (မိနစ်)",
    mn: "Завсарлага (мин)",
    lo: "ພັກຜ່ອນ (ນາທີ)",
    tet: "Deskansa (min)",
    ne: "विश्राम (मिनेट)",
  );
  static const location = L10nText(
    ko: '위치 인증',
    en: 'Location status',
    zh: '位置认证',
    vi: 'Xác minh vị trí',
    uz: 'Joylashuv tasdigʻi',
    tr: 'Konum doğrulama',
    tg: "Тасдиқи макон",
    fil: "Pagpapatunay ng Lokasyon",
    ur: "مقام کی تصدیق",
    th: "การยืนยันตำแหน่ง",
    ky: "Жайгашкан жерди ырастоо",
    km: "ការផ្ទៀងផ្ទាត់ទីតាំង",
    id: "Verifikasi lokasi",
    si: "ස්ථාන සත්‍යාපනය",
    bn: "অবস্থান যাচাইকরণ",
    my: "တည်နေရာ အတည်ပြုခြင်း",
    mn: "Байршлын баталгаажуулалт",
    lo: "ການຢັ້ງຢືນສະຖານທີ່",
    tet: "Verifikasaun fatin",
    ne: "स्थान प्रमाणीकरण",
  );
  static const verified = L10nText(
    ko: '인증 기록 있음',
    en: 'Verification recorded',
    zh: '有认证记录',
    vi: 'Có bản ghi xác minh',
    uz: 'Tasdiq qayd etilgan',
    tr: 'Doğrulama kayıtlı',
    tg: "Тасдиқ сабт шудааст",
    fil: "Naitala ang pagpapatunay",
    ur: "تصدیق محفوظ شدہ",
    th: "ยืนยันแล้ว",
    ky: "Ырастоо катталды",
    km: "ការផ្ទៀងផ្ទាត់ត្រូវបានកត់ត្រា",
    id: "Verifikasi tercatat",
    si: "සත්‍යාපනය වාර්තා කර ඇත",
    bn: "যাচাইকরণ রেকর্ড করা হয়েছে",
    my: "အတည်ပြုချက် မှတ်တမ်းတင်ထားသည်",
    mn: "Баталгаажуулалт бүртгэгдсэн",
    lo: "ການຢັ້ງຢືນຖືກບັນທຶກແລ້ວ",
    tet: "Verifikasaun rejista ona",
    ne: "प्रमाणीकरण रेकर्ड गरियो",
  );
  static const unverified = L10nText(
    ko: '인증 기록 없음',
    en: 'No verification recorded',
    zh: '无认证记录',
    vi: 'Không có xác minh',
    uz: 'Tasdiq qaydi yoʻq',
    tr: 'Doğrulama kaydı yok',
    tg: "Сабти тасдиқ вуҷуд надорад",
    fil: "Walang naitalang pagpapatunay",
    ur: "تصدیق کا کوئی ریکارڈ نہیں",
    th: "ไม่มีการยืนยัน",
    ky: "Ырастоо жазуусу жок",
    km: "គ្មានកំណត់ត្រាផ្ទៀងផ្ទាត់",
    id: "Tidak ada catatan verifikasi",
    si: "සත්‍යාපන වාර්තා නොමැත",
    bn: "কোনো যাচাইকরণ রেকর্ড নেই",
    my: "အတည်ပြုချက် မှတ်တမ်းတင်ထားခြင်း မရှိပါ",
    mn: "Баталгаажуулалт бүртгэгдээгүй",
    lo: "ບໍ່ມີການບັນທຶກການຢັ້ງຢືນ",
    tet: "Verifikasaun la rejista",
    ne: "प्रमाणीकरण रेकर्ड छैन",
  );
  static const missing = L10nText(
    ko: '미기록',
    en: 'Not recorded',
    zh: '未记录',
    vi: 'Chưa ghi',
    uz: 'Qayd etilmagan',
    tr: 'Kaydedilmemiş',
    tg: "Сабт нашудааст",
    fil: "Hindi naitala",
    ur: "محفوظ نہیں کیا گیا",
    th: "ยังไม่ได้บันทึก",
    ky: "Катталган эмес",
    km: "មិនបានកត់ត្រា",
    id: "Tidak tercatat",
    si: "වාර්තා කර නැත",
    bn: "রেকর্ড করা হয়নি",
    my: "မှတ်တမ်းတင်မထားပါ",
    mn: "Бүртгэгдээгүй",
    lo: "ບໍ່ໄດ້ບັນທຶກ",
    tet: "La rejista",
    ne: "रेकर्ड नगरिएको",
  );
  static const address = L10nText(
    ko: '저장된 주소',
    en: 'Saved address',
    zh: '保存的地址',
    vi: 'Địa chỉ đã lưu',
    uz: 'Saqlangan manzil',
    tr: 'Kayıtlı adres',
    tg: "Суроғаи сабтшуда",
    fil: "Naitalang address",
    ur: "محفوظ شدہ پتہ",
    th: "ที่อยู่บันทึกแล้ว",
    ky: "Катталган дарек",
    km: "អាសយដ្ឋានដែលបានកត់ត្រា",
    id: "Alamat tercatat",
    si: "වාර්තා කළ ලිපිනය",
    bn: "রেকর্ড করা ঠিকানা",
    my: "မှတ်တမ်းတင်ထားသော လိပ်စာ",
    mn: "Бүртгэгдсэн хаяг",
    lo: "ທີ່ຢູ່ທີ່ຖືກບັນທຶກ",
    tet: "Adresa rejistradu",
    ne: "रेकर्ड गरिएको ठेगाना",
  );
  static const coordinates = L10nText(
    ko: '저장된 좌표(위도, 경도)',
    en: 'Saved coordinates (latitude, longitude)',
    zh: '保存的坐标(纬度、经度)',
    vi: 'Tọa độ đã lưu (vĩ độ, kinh độ)',
    uz: 'Saqlangan koordinatalar (kenglik, uzunlik)',
    tr: 'Kayıtlı koordinatlar (enlem, boylam)',
    tg: "Координатҳои сабтшуда (арз, тӯл)",
    fil: "Naitalang mga coordinate (latitude, longitude)",
    ur: "محفوظ شدہ نقاط (عرض بلد، طول بلد)",
    th: "พิกัดที่บันทึกไว้ (ละติจูด, ลองจิจูด)",
    ky: "Катталган координаттар (кеңдик, узундук)",
    km: "កូអរដោនេដែលបានកត់ត្រា (រយៈទទឹង, រយៈបណ្ដោយ)",
    id: "Koordinat tercatat (lintang, bujur)",
    si: "වාර්තා කළ ඛණ්ඩාංක (අක්ෂාංශ, දේශාංශ)",
    bn: "রেকর্ড করা স্থানাঙ্ক (অক্ষাংশ, দ্রাঘিমাংশ)",
    my: "မှတ်တမ်းတင်ထားသော ကိုဩဒိနိတ်များ (လတ္တီကျု၊ လောင်ဂျီကျု)",
    mn: "Бүртгэгдсэн координат (өргөрөг, уртраг)",
    lo: "ພິກັດທີ່ຖືກບັນທຶກ (ເສັ້ນຂະໜານ, ເສັ້ນແວງ)",
    tet: "Koordinadas rejistradu (latitude, longitude)",
    ne: "रेकर्ड गरिएका निर्देशांकहरू (अक्षांश, देशान्तर)",
  );
  static const memo = L10nText(
    ko: '메모(원문)',
    en: 'Notes (original)',
    zh: '备注(原文)',
    vi: 'Ghi chú (nguyên văn)',
    uz: 'Izohlar (asl)',
    tr: 'Notlar (orijinal)',
    tg: "Эзоҳҳо (аслӣ)",
    fil: "Mga Tala (orihinal)",
    ur: "نوٹس (اصل)",
    th: "บันทึก (ต้นฉบับ)",
    ky: "Эскертүүлөр (түп нуска)",
    km: "កំណត់ចំណាំ (ដើម)",
    id: "Catatan (asli)",
    si: "සටහන් (මුල්)",
    bn: "নোট (আসল)",
    my: "မှတ်စုများ (မူရင်း)",
    mn: "Тэмдэглэл (эх хувь)",
    lo: "ໝາຍເຫດ (ຕົ້ນສະບັບ)",
    tet: "Nota sira (orijinál)",
    ne: "टिप्पणीहरू (मूल)",
  );
  static const owner = L10nText(
    ko: '기록자',
    en: 'Record owner',
    zh: '记录人',
    vi: 'Người ghi',
    uz: 'Qayd egasi',
    tr: 'Kayıt sahibi',
    tg: "Соҳиби сабт",
    fil: "May-ari ng record",
    ur: "ریکارڈ کا مالک",
    th: "เจ้าของบันทึก",
    ky: "Жазуунун ээси",
    km: "ម្ចាស់កំណត់ត្រា",
    id: "Pemilik catatan",
    si: "වාර්තාවේ හිමිකරු",
    bn: "রেকর্ডের মালিক",
    my: "မှတ်တမ်းပိုင်ရှင်",
    mn: "Бүртгэлийн эзэмшигч",
    lo: "ເຈົ້າຂອງບັນທຶກ",
    tet: "Na'in ba rejistu",
    ne: "रेकर्डको मालिक",
  );
  static const period = L10nText(
    ko: '조회 기간(30일)',
    en: 'Period (30 days)',
    zh: '查询期间(30天)',
    vi: 'Khoảng thời gian (30 ngày)',
    uz: 'Davr (30 kun)',
    tr: 'Dönem (30 gün)',
    tg: "Давра (30 рӯз)",
    fil: "Panahon (30 araw)",
    ur: "مدت (30 دن)",
    th: "ระยะเวลา (30 วัน)",
    ky: "Мөөнөтү (30 күн)",
    km: "រយៈពេល (30 ថ្ងៃ)",
    id: "Periode (30 hari)",
    si: "කාල සීමාව (දින 30)",
    bn: "সময়কাল (30 দিন)",
    my: "ကာလ (30 ရက်)",
    mn: "Хугацаа (30 өдөр)",
    lo: "ໄລຍະເວລາ (30 ມື້)",
    tet: "Períodu (loron 30)",
    ne: "अवधि (30 दिन)",
  );
  static const generated = L10nText(
    ko: '불러온 시각(한국시간)',
    en: 'Retrieved at (KST)',
    zh: '读取时间(韩国时间)',
    vi: 'Thời điểm tải (KST)',
    uz: 'Yuklangan vaqt (KST)',
    tr: 'Yükleme zamanı (KST)',
    tg: "Вақти боргузорӣ (KST)",
    fil: "Oras ng pag-upload (KST)",
    ur: "اپ لوڈ کا وقت (KST)",
    th: "เวลาที่อัปโหลด (KST)",
    ky: "Жүктөө убактысы (KST)",
    km: "ពេលវេលាផ្ទុកឡើង (KST)",
    id: "Waktu unggah (KST)",
    si: "උඩුගත කළ වේලාව (KST)",
    bn: "আপলোডের সময় (KST)",
    my: "တင်သည့်အချိန် (ကိုရီးယားစံတော်ချိန်)",
    mn: "Байршуулсан цаг (KST)",
    lo: "ເວລາອັບໂຫຼດ (KST)",
    tet: "Tempu upload (KST)",
    ne: "अपलोड समय (KST)",
  );
  static const savedDays = L10nText(
    ko: '저장된 날짜 수',
    en: 'Days with records',
    zh: '有记录的天数',
    vi: 'Số ngày có bản ghi',
    uz: 'Qaydli kunlar soni',
    tr: 'Kayıt bulunan gün sayısı',
    tg: "Шумораи рӯзҳои дорои сабт",
    fil: "Bilang ng mga araw na may record",
    ur: "ریکارڈ کے ساتھ دنوں کی تعداد",
    th: "จำนวนวันที่พบการบันทึก",
    ky: "Жазуу табылган күндөрдүн саны",
    km: "ចំនួនថ្ងៃដែលមានកំណត់ត្រា",
    id: "Jumlah hari dengan catatan",
    si: "වාර්තා සොයාගත් දින ගණන",
    bn: "রেকর্ড পাওয়া দিনের সংখ্যা",
    my: "မှတ်တမ်းတွေ့ရှိသည့် ရက်အရေအတွက်",
    mn: "Бүртгэлтэй өдрийн тоо",
    lo: "ຈຳນວນມື້ທີ່ມີການບັນທຶກ",
    tet: "Numeru loron ho rejistu",
    ne: "रेकर्ड फेला परेका दिनहरूको संख्या",
  );
  static const details = L10nText(
    ko: '일별 상세 기록',
    en: 'Daily details',
    zh: '每日详细记录',
    vi: 'Chi tiết từng ngày',
    uz: 'Kunlik tafsilotlar',
    tr: 'Günlük ayrıntılar',
    tg: "Тафсилоти рӯзнома",
    fil: "Mga detalye ng log",
    ur: "روزانہ کی تفصیلات",
    th: "รายละเอียดรายวัน",
    ky: "Күндөлүк маалыматтар",
    km: "ព័ត៌មានលម្អិតប្រចាំថ្ងៃ",
    id: "Detail harian",
    si: "දිනපතා විස්තර",
    bn: "দিনের বিবরণ",
    my: "နေ့စဉ်အသေးစိတ်များ",
    mn: "Өдрийн дэлгэрэнгүй мэдээлэл",
    lo: "ລາຍລະອຽດປະຈຳວັນ",
    tet: "Detalhes diáriu",
    ne: "दैनिक विवरणहरू",
  );
}
