import 'package:flutter/material.dart';
import '../../../core/app_language.dart';

enum CategoryGroupId { a, b, c }

/// 백과사전 카테고리 1개. html_files/생활백과사전.html의 12개 항목(그룹당 4개)
/// 그대로를 옮긴 것이라 id는 그 순서를 그대로 따른다(1~4=A, 5~8=B, 9~12=C).
class CategoryItem {
  const CategoryItem({
    required this.id,
    required this.icon,
    required this.name,
    required this.group,
    required this.source,
  });

  final int id;
  final IconData icon;
  final L10nText name;
  final CategoryGroupId group;
  final String source;
}

/// 그룹(북마크) 1개 — 표지 우측의 세로 탭 A/B/C에 대응.
class CategoryGroupData {
  const CategoryGroupData({
    required this.id,
    required this.color,
    required this.backgroundTint,
    required this.markLabel,
    required this.name,
    required this.title,
    required this.itemIds,
    this.skeletonIds = const [],
  });

  final CategoryGroupId id;
  final Color color;
  final Color backgroundTint;

  /// 세로 북마크에 쓰는 짧은 라벨(예: "필수행정")
  final L10nText markLabel;

  /// 목차 상단에 쓰는 그룹명(예: "그룹 A · 필수 행정·인증")
  final L10nText name;

  /// 목차 상단 큰 제목(예: "입국 후 처음 해야 할 일")
  final L10nText title;

  final List<int> itemIds;

  /// 아직 콘텐츠가 없는 "준비 중" 항목 — 목차엔 노출하되 탭할 수 없다.
  /// 지금은 그룹당 4개 항목이 전부 채워져 있어 비어 있다.
  final List<int> skeletonIds;
}

const Map<int, CategoryItem> categoryById = {
  // ── Group A · 필수 행정 ──────────────────────────────────────────
  1: CategoryItem(
    id: 1,
    icon: Icons.badge_outlined,
    group: CategoryGroupId.a,
    name: L10nText(
      ko: '등록증',
      en: 'ARC',
      tr: "ARC",
      tg: "ARC",
      fil: "ARC",
      ur: "ARC",
      th: "บัตรประจำตัวคนต่างด้าว (ARC)",
      ky: "ARC",
      km: "ARC",
      id: "ARC",
      si: "ARC",
      bn: "এআরসি",
      my: "နိုင်ငံခြားသား မှတ်ပုံတင်ကတ်",
      mn: "Гадаадын иргэний бүртгэлийн карт",
      lo: "ARC",
      tet: "ARC",
      ne: "ARC",
      zh: '外国人登录证',
      vi: 'Thẻ đăng ký',
      uz: "ARC",
    ),
    source:
        '출입국관리법 제31조·제33조·제36조, 하이코리아(hikorea.go.kr), 법무부(moj.go.kr), 정부24(gov.kr)',
  ),
  2: CategoryItem(
    id: 2,
    icon: Icons.assignment_ind_outlined,
    group: CategoryGroupId.a,
    name: L10nText(
      ko: '비자',
      en: 'Visa',
      tr: "Vize",
      tg: "Раводид",
      fil: "Visa",
      ur: "ویزا",
      th: "วีซ่า",
      ky: "Виза",
      km: "ទិដ្ឋាការ",
      id: "Visa",
      si: "වීසා",
      bn: "ভিসা",
      my: "ဗီဇာ",
      mn: "Виз",
      lo: "ວີຊາ",
      tet: "Viza",
      ne: "भिसा",
      zh: '签证',
      vi: 'Visa',
      uz: "Viza",
    ),
    source:
        '출입국관리법 제25조(체류기간 연장)·제24조(체류자격 변경), 하이코리아(hikorea.go.kr), 법무부(moj.go.kr)',
  ),
  3: CategoryItem(
    id: 3,
    icon: Icons.work_outline,
    group: CategoryGroupId.a,
    name: L10nText(
      ko: '취업수속',
      en: 'Employment procedures',
      tr: "İstihdam prosedürleri",
      tg: "Тартиби шуғл",
      fil: "Mga pamamaraan sa pagtatrabaho",
      ur: "روزگار کے طریقہ کار",
      th: "ขั้นตอนการจ้างงาน",
      ky: "Жумушка орношуу процедуралары",
      km: "នីតិវិធីការងារ",
      id: "Prosedur Ketenagakerjaan",
      si: "රැකියා ක්‍රියා පටිපාටි",
      bn: "কর্মসংস্থান পদ্ধতি",
      my: "အလုပ်အကိုင် လုပ်ထုံးလုပ်နည်းများ",
      mn: "Ажлын журам",
      lo: "ຂັ້ນຕອນການຈ້າງງານ",
      tet: "Prosedimentu Empregu",
      ne: "रोजगार प्रक्रियाहरू",
      zh: '就业手续',
      vi: 'Thủ tục việc làm',
      uz: "Ishga joylashish tartib-qoidalari",
    ),
    source:
        "한국산업인력공단 EPS 고용허가제 통합서비스(eps.hrdkorea.or.kr), 찾기쉬운 생활법령정보(easylaw.go.kr) '외국인근로자 취업절차', 고용노동부(moel.go.kr)",
  ),
  4: CategoryItem(
    id: 4,
    icon: Icons.assignment_outlined,
    group: CategoryGroupId.a,
    name: L10nText(
      ko: '체류신고',
      en: 'Residence reporting',
      tr: "İkamet bildirimi",
      tg: "Хабар додан дар бораи истиқомат",
      fil: "Pag-uulat ng tirahan",
      ur: "رہائش کی اطلاع",
      th: "การแจ้งที่อยู่",
      ky: "Жашаган жери тууралуу билдирүү",
      km: "ការជូនដំណឹងអំពីលំនៅឋាន",
      id: "Pemberitahuan Tempat Tinggal",
      si: "පදිංචිය දැනුම්දීම",
      bn: "আবাসিক বিজ্ঞপ্তি",
      my: "နေထိုင်ခွင့် အကြောင်းကြားစာ",
      mn: "Оршин суух хаягийн мэдэгдэл",
      lo: "ການແຈ້ງທີ່ຢູ່ອາໄສ",
      tet: "Notifikasaun Rezidénsia",
      ne: "निवासको सूचना",
      zh: '居留申报',
      vi: 'Khai báo cư trú',
      uz: "Yashash joyi haqida hisobot",
    ),
    source:
        '출입국관리법 제30조·제36조·제98조, 찾기쉬운 생활법령정보(easylaw.go.kr), 하이코리아(hikorea.go.kr), 정부24(gov.kr)',
  ),

  // ── Group B · 생활 정착 ──────────────────────────────────────────
  5: CategoryItem(
    id: 5,
    icon: Icons.local_hospital_outlined,
    group: CategoryGroupId.b,
    name: L10nText(
      ko: '병원',
      en: 'Hospitals',
      tr: "Hastaneler",
      tg: "Беморхонаҳо",
      fil: "Mga Ospital",
      ur: "ہسپتال",
      th: "โรงพยาบาล",
      ky: "Ооруканалар",
      km: "មន្ទីរពេទ្យ",
      id: "Rumah Sakit",
      si: "රෝහල්",
      bn: "হাসপাতাল",
      my: "ဆေးရုံများ",
      mn: "Эмнэлгүүд",
      lo: "ໂຮງໝໍ",
      tet: "Ospitál sira",
      ne: "अस्पतालहरू",
      zh: '医院',
      vi: 'Bệnh viện',
      uz: "Shifoxonalar",
    ),
    source:
        '응급의료포털 E-Gen(e-gen.or.kr), 보건복지부(mohw.go.kr), 국민건강보험공단(nhis.or.kr), BBB코리아(bbbkorea.org)',
  ),
  6: CategoryItem(
    id: 6,
    icon: Icons.health_and_safety_outlined,
    group: CategoryGroupId.b,
    name: L10nText(
      ko: '보험',
      en: 'Insurance',
      tr: "Sigorta",
      tg: "Суғурта",
      fil: "Seguro",
      ur: "بیمہ",
      th: "ประกันภัย",
      ky: "Камсыздандыруу",
      km: "ការធានារ៉ាប់រង",
      id: "Asuransi",
      si: "රක්ෂණය",
      bn: "বীমা",
      my: "အာမခံ",
      mn: "Даатгал",
      lo: "ປະກັນໄພ",
      tet: "Seguru",
      ne: "बीमा",
      zh: '保险',
      vi: 'Bảo hiểm',
      uz: "Sugʻurta",
    ),
    source:
        "외국인근로자의 고용 등에 관한 법률, 찾기쉬운 생활법령정보(easylaw.go.kr) '4대보험·외국인근로자 전용보험', EPS 고용허가제 4대 보험안내(eps.hrdkorea.or.kr), 국민건강보험공단(nhis.or.kr)",
  ),
  7: CategoryItem(
    id: 7,
    icon: Icons.apartment_outlined,
    group: CategoryGroupId.b,
    name: L10nText(
      ko: '주거',
      en: 'Housing',
      tr: "Konut",
      tg: "Манзил",
      fil: "Pabahay",
      ur: "رہائش",
      th: "ที่พักอาศัย",
      ky: "Турак жай",
      km: "លំនៅឋាន",
      id: "Perumahan",
      si: "නිවාස",
      bn: "আবাসন",
      my: "အိမ်ရာ",
      mn: "Орон сууц",
      lo: "ທີ່ພັກອາໄສ",
      tet: "Uma",
      ne: "आवास",
      zh: '住房',
      vi: 'Nhà ở',
      uz: "Uy-joy",
    ),
    source:
        "주택임대차보호법, 찾기쉬운 생활법령정보(easylaw.go.kr) '보증금의 보호', 대법원 인터넷등기소(iros.go.kr), 주택도시보증공사 안심전세포털(khug.or.kr)",
  ),
  8: CategoryItem(
    id: 8,
    icon: Icons.directions_bus_outlined,
    group: CategoryGroupId.b,
    name: L10nText(
      ko: '교통',
      en: 'Transportation',
      tr: "Ulaşım",
      tg: "Нақлиёт",
      fil: "Transportasyon",
      ur: "نقل و حمل",
      th: "การเดินทาง",
      ky: "Транспорт",
      km: "ការដឹកជញ្ជូន",
      id: "Transportasi",
      si: "ප්‍රවාහනය",
      bn: "পরিবহন",
      my: "သယ်ယူပို့ဆောင်ရေး",
      mn: "Тээвэр",
      lo: "ການຂົນສົ່ງ",
      tet: "Transporte",
      ne: "यातायात",
      zh: '交通',
      vi: 'Giao thông',
      uz: "Transport",
    ),
    source:
        '도로교통공단 안전운전 통합민원(safedriving.or.kr), K-패스(korea-pass.kr), 국토교통부(molit.go.kr)',
  ),

  // ── Group C · 노동 권익 ──────────────────────────────────────────
  9: CategoryItem(
    id: 9,
    icon: Icons.fact_check_outlined,
    group: CategoryGroupId.c,
    name: L10nText(
      ko: '근로계약서',
      en: 'Employment contract',
      tr: "İş sözleşmesi",
      tg: "Шартномаи корӣ",
      fil: "Kontrata sa trabaho",
      ur: "کام کا معاہدہ",
      th: "สัญญาจ้างงาน",
      ky: "Эмгек келишими",
      km: "កិច្ចសន្យាការងារ",
      id: "Kontrak Kerja",
      si: "රැකියා කොන්ත්‍රාත්තුව",
      bn: "কাজের চুক্তি",
      my: "အလုပ်သမား စာချုပ်",
      mn: "Хөдөлмөрийн гэрээ",
      lo: "ສັນຍາຈ້າງງານ",
      tet: "Kontratu Traballu",
      ne: "रोजगार सम्झौता",
      zh: '劳动合同',
      vi: 'Hợp đồng lao động',
      uz: "Mehnat shartnomasi",
    ),
    source:
        '근로기준법 제17조·제20조, 고용노동부(moel.go.kr) 표준근로계약서, 찾기쉬운 생활법령정보(easylaw.go.kr)',
  ),
  10: CategoryItem(
    id: 10,
    icon: Icons.payments_outlined,
    group: CategoryGroupId.c,
    name: L10nText(
      ko: '임금체불',
      en: 'Unpaid wages',
      tr: "Ödenmemiş ücretler",
      tg: "Музди меҳнати пардохтнашуда",
      fil: "Hindi nabayarang sahod",
      ur: "غیر ادا شدہ اجرت",
      th: "ค่าจ้างค้างจ่าย",
      ky: "Төлөнбөгөн эмгек акы",
      km: "ប្រាក់ឈ្នួលមិនទាន់បានបង់",
      id: "Gaji yang Belum Dibayar",
      si: "නොගෙවූ වැටුප්",
      bn: "অপ্রদত্ত মজুরি",
      my: "မရရှိသေးသော လုပ်ခ",
      mn: "Цалин хөлс төлөгдөөгүй",
      lo: "ຄ່າຈ້າງທີ່ຄ້າງຈ່າຍ",
      tet: "Saláriu la selu",
      ne: "नतिरेको ज्याला",
      zh: '拖欠工资',
      vi: 'Nợ lương',
      uz: "Toʻlanmagan ish haqi",
    ),
    source:
        '고용노동부 노동포털(labor.moel.go.kr), 임금채권보장법(간이대지급금), 소액사건심판법, 대한법률구조공단(klac.or.kr), 근로기준법',
  ),
  11: CategoryItem(
    id: 11,
    icon: Icons.medical_services_outlined,
    group: CategoryGroupId.c,
    name: L10nText(
      ko: '산업재해',
      en: 'Workplace injury',
      tr: "İş kazası",
      tg: "Ҳодисаи корӣ",
      fil: "Aksidente sa trabaho",
      ur: "کام پر حادثہ",
      th: "อุบัติเหตุจากการทำงาน",
      ky: "Өндүрүштүк кырсык",
      km: "គ្រោះថ្នាក់ការងារ",
      id: "Kecelakaan Kerja",
      si: "රැකියා අනතුර",
      bn: "কর্মক্ষেত্রে দুর্ঘটনা",
      my: "လုပ်ငန်းခွင် မတော်တဆမှု",
      mn: "Ажлын осол",
      lo: "ອຸບັດຕິເຫດໃນບ່ອນເຮັດວຽກ",
      tet: "Asidente Traballu",
      ne: "कार्यस्थल दुर्घटना",
      zh: '工伤',
      vi: 'Tai nạn lao động',
      uz: "Ish joyidagi jarohat",
    ),
    source: '산업재해보상보험법, 근로복지공단(comwel.or.kr), 근로기준법 제23조',
  ),
  12: CategoryItem(
    id: 12,
    icon: Icons.support_agent,
    group: CategoryGroupId.c,
    name: L10nText(
      ko: '상담기관',
      en: 'Support organizations',
      tr: "Destek kuruluşları",
      tg: "Ташкилотҳои дастгирӣ",
      fil: "Mga organisasyong sumusuporta",
      ur: "معاون تنظیمیں",
      th: "องค์กรสนับสนุน",
      ky: "Колдоо уюмдары",
      km: "អង្គការជំនួយ",
      id: "Organisasi Pendukung",
      si: "ආධාරක සංවිධාන",
      bn: "সহায়তা সংস্থা",
      my: "ပံ့ပိုးကူညီရေး အဖွဲ့အစည်းများ",
      mn: "Дэмжих байгууллагууд",
      lo: "ອົງການຊ່ວຍເຫຼືອ",
      tet: "Organizasaun Apoiu",
      ne: "सहयोगी संस्थाहरू",
      zh: '咨询机构',
      vi: 'Cơ quan tư vấn',
      uz: "Qoʻllab-quvvatlash tashkilotlari",
    ),
    source:
        '법무부(moj.go.kr), 하이코리아(hikorea.go.kr), 고용노동부(moel.go.kr), 한국산업인력공단(hrdkorea.or.kr), 근로복지공단(comwel.or.kr), 경기도노동권익센터(labor.gg.go.kr), 수원시(suwon.go.kr), 수원시외국인복지센터(suwonmcs.com), 수원시비정규직노동자복지센터(swbjk.kr), 대한법률구조공단(klac.or.kr), 여성가족부 다누리콜센터(mogef.go.kr), BBB코리아(bbbkorea.org)',
  ),
};

const Map<CategoryGroupId, CategoryGroupData> categoryGroups = {
  CategoryGroupId.a: CategoryGroupData(
    id: CategoryGroupId.a,
    color: Color(0xFF2196F3),
    backgroundTint: Color(0xFFE3F2FD),
    markLabel: L10nText(
      ko: '필수행정',
      en: 'ADMIN',
      tr: "YÖNETİM",
      tg: "ИДОРАКУНӢ",
      fil: "PAMAMAHALA",
      ur: "انتظام",
      th: "การจัดการ",
      ky: "БАШКАРУУ",
      km: "ការគ្រប់គ្រង",
      id: "ADMINISTRASI",
      si: "පාලනය",
      bn: "প্রশাসন",
      my: "စီမံခန့်ခွဲမှု",
      mn: "УДИРДЛАГА",
      lo: "ການຄຸ້ມຄອງ",
      tet: "JESTAUN",
      ne: "व्यवस्थापन",
      zh: '必办手续',
      vi: 'THỦ TỤC',
      uz: "ADMIN",
    ),
    name: L10nText(
      ko: '그룹 A',
      en: 'Group A ',
      tr: "Grup A ",
      tg: "Гурӯҳи А ",
      fil: "Pangkat A ",
      ur: "گروپ A ",
      th: "กลุ่ม A ",
      ky: "А тобу ",
      km: "ក្រុម A ",
      id: "Grup A ",
      si: "කණ්ඩායම A ",
      bn: "গ্রুপ এ ",
      my: "အုပ်စု က ",
      mn: "Бүлэг А ",
      lo: "ກຸ່ມ A ",
      tet: "Grupu A ",
      ne: "समूह A",
      zh: 'A组',
      vi: 'Nhóm A',
      uz: "A guruhi ",
    ),
    title: L10nText(
      ko: '필수 행정',
      en: 'Essential admin',
      tr: "Temel yönetim",
      tg: "Идоракунии асосӣ",
      fil: "Pangunahing pamamahala",
      ur: "بنیادی انتظام",
      th: "การจัดการพื้นฐาน",
      ky: "Негизги башкаруу",
      km: "ការគ្រប់គ្រងមូលដ្ឋាន",
      id: "Administrasi dasar",
      si: "මූලික කළමනාකරණය",
      bn: "মৌলিক প্রশাসন",
      my: "အခြေခံ စီမံခန့်ခွဲမှု",
      mn: "Үндсэн удирдлага",
      lo: "ການຄຸ້ມຄອງພື້ນຖານ",
      tet: "Jestaun Bázika",
      ne: "आधारभूत व्यवस्थापन",
      zh: '必办行政',
      vi: 'Thủ tục bắt buộc',
      uz: "Muhim maʼmuriyat",
    ),
    itemIds: [1, 2, 3, 4],
  ),
  CategoryGroupId.b: CategoryGroupData(
    id: CategoryGroupId.b,
    color: Color(0xFF4CAF50),
    backgroundTint: Color(0xFFE8F5E9),
    markLabel: L10nText(
      ko: '생활정착',
      en: 'LIVING',
      tr: "YAŞAM",
      tg: "ҲАЁТ",
      fil: "PAMUMUHAY",
      ur: "زندگی",
      th: "ชีวิต",
      ky: "ЖАШОО",
      km: "ជីវិត",
      id: "KEHIDUPAN",
      si: "ජීවිතය",
      bn: "জীবন",
      my: "ဘဝ",
      mn: "АМЬДРАЛ",
      lo: "ການດຳລົງຊີວິດ",
      tet: "MORIS",
      ne: "जीवन",
      zh: '生活安顿',
      vi: 'SINH HOẠT',
      uz: "YASHASH",
    ),
    name: L10nText(
      ko: '그룹 B',
      en: 'Group B',
      tr: "Grup B",
      tg: "Гурӯҳи Б",
      fil: "Pangkat B",
      ur: "گروپ B",
      th: "กลุ่ม B",
      ky: "Б тобу",
      km: "ក្រុម B",
      id: "Grup B",
      si: "කණ්ඩායම B",
      bn: "গ্রুপ বি",
      my: "အုပ်စု ခ",
      mn: "Бүлэг Б",
      lo: "ກຸ່ມ B",
      tet: "Grupu B",
      ne: "समूह B",
      zh: 'B组',
      vi: 'Nhóm B',
      uz: "B guruhi",
    ),
    title: L10nText(
      ko: '생활 정착',
      en: 'Settling in',
      tr: "Yerleşme",
      tg: "Ҷойгиршавӣ",
      fil: "Pag-aayos",
      ur: "آباد کاری",
      th: "การตั้งถิ่นฐาน",
      ky: "Жашоо",
      km: "ការតាំងទីលំនៅ",
      id: "Penyelesaian",
      si: "පදිංචි වීම",
      bn: "বসতি স্থাপন",
      my: "အခြေချနေထိုင်ခြင်း",
      mn: "Суурьших",
      lo: "ການຕັ້ງຖິ່ນຖານ",
      tet: "Estabelesimentu",
      ne: "बसोबास",
      zh: '生活安顿',
      vi: 'Ổn định cuộc sống',
      uz: "Joylashish",
    ),
    itemIds: [5, 6, 7, 8],
  ),
  CategoryGroupId.c: CategoryGroupData(
    id: CategoryGroupId.c,
    color: Color(0xFF2196F3),
    backgroundTint: Color(0xFFE3F2FD),
    markLabel: L10nText(
      ko: '노동권익',
      en: 'RIGHTS',
      tr: "HAKLAR",
      tg: "ҲУҚУҚҲО",
      fil: "MGA KARAPATAN",
      ur: "حقوق",
      th: "สิทธิ",
      ky: "УКУКТАР",
      km: "សិទ្ធិ",
      id: "HAK",
      si: "අයිතිවාසිකම්",
      bn: "অধিকার",
      my: "အခွင့်အရေးများ",
      mn: "ЭРХ",
      lo: "ສິດທິ",
      tet: "DIREITU SIRA",
      ne: "अधिकारहरू",
      zh: '劳动权益',
      vi: 'QUYỀN LỢI',
      uz: "HUQUQLAR",
    ),
    name: L10nText(
      ko: '그룹 C',
      en: 'Group C',
      tr: "Grup C",
      tg: "Гурӯҳи В",
      fil: "Pangkat C",
      ur: "گروپ C",
      th: "กลุ่ม C",
      ky: "В тобу",
      km: "ក្រុម C",
      id: "Grup C",
      si: "කණ්ඩායම C",
      bn: "গ্রুপ সি",
      my: "အုပ်စု ဂ",
      mn: "Бүлэг В",
      lo: "ກຸ່ມ C",
      tet: "Grupu C",
      ne: "समूह C",
      zh: 'C组',
      vi: 'Nhóm C',
      uz: "C guruhi",
    ),
    title: L10nText(
      ko: '노동 권익',
      en: 'Labor rights',
      tr: "İşçi hakları",
      tg: "Ҳуқуқҳои коргарон",
      fil: "Mga karapatan ng manggagawa",
      ur: "مزدوروں کے حقوق",
      th: "สิทธิแรงงาน",
      ky: "Жумушчу укуктары",
      km: "សិទ្ធិកម្មករ",
      id: "Hak-hak pekerja",
      si: "කම්කරු අයිතිවාසිකම්",
      bn: "শ্রমিক অধিকার",
      my: "အလုပ်သမား အခွင့်အရေးများ",
      mn: "Ажилчдын эрх",
      lo: "ສິດທິຂອງແຮງງານ",
      tet: "Direitu Traballadór sira",
      ne: "श्रमिक अधिकारहरू",
      zh: '劳动权益',
      vi: 'Quyền lợi lao động',
      uz: "Mehnat huquqlari",
    ),
    itemIds: [9, 10, 11, 12],
  ),
};

/// 표지의 "자주 보는 항목" 3칩 — (categoryId, 줄바꿈 포함 짧은 라벨).
/// html_files/생활백과사전.html 홈 화면의 퀵버튼(계약서 체크·ARC 발급·권리구제)과 동일하게 맞췄다.
const quickAccessChips = [
  (
    9,
    L10nText(
      ko: '계약서\n체크',
      en: 'Contract\ncheck',
      tr: "Sözleşme\nkontrolü",
      tg: "Назорати\nшартнома",
      fil: "Pagsusuri ng\nkontrata",
      ur: "معاہدے کی\nجانچ",
      th: "การตรวจสอบ\nสัญญา",
      ky: "Келишимди\nтекшерүү",
      km: "ការត្រួតពិនិត្យ\nកិច្ចសន្យា",
      id: "Pemeriksaan\nkontrak",
      si: "කොන්ත්‍රාත්\nපරීක්ෂාව",
      bn: "চুক্তি\nপর্যালোচনা",
      my: "စာချုပ်\nစစ်ဆေးခြင်း",
      mn: "Гэрээг\nшалгах",
      lo: "ການກວດສອບ\nສັນຍາ",
      tet: "Kontrolu\nkontratu",
      ne: "सम्झौता\nजाँच",
      zh: '合同\n检查',
      vi: 'Kiểm tra\nhợp đồng',
      uz: "Shartnomani\ntekshirish",
    ),
  ),
  (
    1,
    L10nText(
      ko: 'ARC\n발급',
      en: 'ARC\nissuance',
      tr: "ARC\ndüzenleme",
      tg: "Танзими\nARC",
      fil: "Pagsasaayos ng\nARC",
      ur: "ARC\nترمیم",
      th: "การจัดทำ\nบัตรประจำตัวคนต่างด้าว (ARC)",
      ky: "ARC\nжөнгө салуу",
      km: "ការរៀបចំ\nARC",
      id: "Pengaturan\nARC",
      si: "ARC\nනියාමනය",
      bn: "এআরসি\nনিয়ন্ত্রণ",
      my: "နိုင်ငံခြားသား မှတ်ပုံတင်ကတ်\nစီစဉ်ခြင်း",
      mn: "Гадаадын иргэний бүртгэлийн\nкартыг зохицуулах",
      lo: "ການຈັດການ\nARC",
      tet: "Regulamentu\nARC",
      ne: "ARC\nव्यवस्थापन",
      zh: 'ARC\n办理',
      vi: 'Cấp thẻ\nARC',
      uz: "ARC\nberish",
    ),
  ),
  (
    10,
    L10nText(
      ko: '임금체불\n대응',
      en: 'Unpaid wage\nresponse',
      tr: "Ödenmemiş ücret\nyanıtı",
      tg: "Ҷавоб ба музди\nмеҳнати пардохтнашуда",
      fil: "Pagtugon sa hindi\nnabayarang sahod",
      ur: "غیر ادا شدہ اجرت\nکا جواب",
      th: "การตอบสนอง\nค่าจ้างค้างจ่าย",
      ky: "Төлөнбөгөн эмгек акыга\nжооп",
      km: "ការឆ្លើយតប\nប្រាក់ឈ្នួលមិនទាន់បានបង់",
      id: "Tanggapan gaji\nyang belum dibayar",
      si: "නොගෙවූ වැටුප්\nප්‍රතිචාරය",
      bn: "অপ্রদত্ত মজুরি\nপ্রতিক্রিয়া",
      my: "မရရှိသေးသော လုပ်ခ\nတုံ့ပြန်မှု",
      mn: "Төлөгдөөгүй цалингийн\nхариу",
      lo: "ການຕອບສະໜອງ\nຄ່າຈ້າງທີ່ຄ້າງຈ່າຍ",
      tet: "Resposta ba\nsaláriu la selu",
      ne: "नतिरेको ज्याला\nप्रतिक्रिया",
      zh: '拖欠工资\n应对',
      vi: 'Ứng phó\nnợ lương',
      uz: "Toʻlanmagan ish haqiga\njavob",
    ),
  ),
];
