import '../../../core/app_language.dart';

/// 백과사전 탭 UI 문구(콘텐츠가 아니라 버튼·안내문). 콘텐츠 문구(카테고리명·
/// 상세 설명)와 분리해서 관리한다 — 콘텐츠만 노무사 감수 대상이기 때문.
class EncyclopediaStrings {
  EncyclopediaStrings._();

  static const coverTitle = L10nText(
    ko: '한국 생활\n백과사전',
    en: 'Living in\nKorea',
    tr: "Kore'de\nyaşam",
    tg: "Ҳаёт дар\nКорея",
    fil: "Pamumuhay sa\nKorea",
    ur: "کوریا میں\nزندگی",
    th: "ชีวิตใน\nเกาหลี",
    ky: "Кореяда\nжашоо",
    km: "ជីវិតនៅ\nកូរ៉េ",
    id: "Hidup di\nKorea",
    si: "කොරියාවේ\nජීවිතය",
    bn: "কোরিয়ায়\nজীবন",
    my: "ကိုရီးယားတွင်\nနေထိုင်ခြင်း",
    mn: "Солонгост\nамьдрах",
    lo: "ການດຳລົງຊີວິດ\nຢູ່ເກົາຫຼີ",
    tet: "Moris iha\nKoreia",
    ne: "कोरियामा\nजीवन",
    zh: '韩国生活\n指南',
    vi: 'Cẩm nang\nsống ở Hàn Quốc',
    uz: "Koreyada\nyashash",
  );
  static const coverSubtitle = L10nText(
    ko: '한국에서 일하고 살아가는 데 필요한 절차를 정리했습니다',
    en: "We've organized the steps you need to work and live in Korea",
    tr: "Kore'de çalışmak ve yaşamak için ihtiyacınız olan adımları düzenledik",
    tg: "Мо қадамҳои заруриро барои кор ва зиндагӣ дар Корея ташкил кардем",
    fil:
        "Inayos namin ang mga hakbang na kailangan mo para magtrabaho at manirahan sa Korea",
    ur: "ہم نے کوریا میں کام کرنے اور رہنے کے لیے درکار اقدامات کو ترتیب دیا ہے۔",
    th: "เราได้จัดเตรียมขั้นตอนที่ท่านจำเป็นต้องรู้สำหรับการทำงานและการใช้ชีวิตในเกาหลี",
    ky: "Кореяда иштөө жана жашоо үчүн керектүү кадамдарды уюштурдук",
    km: "យើងបានរៀបចំជំហានដែលអ្នកត្រូវការដើម្បីធ្វើការ និងរស់នៅក្នុងប្រទេសកូរ៉េ",
    id: "Kami telah mengatur langkah-langkah yang Anda butuhkan untuk bekerja dan hidup di Korea",
    si: "කොරියාවේ වැඩ කිරීමට සහ ජීවත් වීමට ඔබට අවශ්‍ය පියවර අපි සංවිධානය කර ඇත්තෙමු",
    bn: "কোরিয়ায় কাজ করতে এবং বসবাস করতে আপনার প্রয়োজনীয় পদক্ষেপগুলি আমরা সাজিয়েছি",
    my: "ကိုရီးယားတွင် အလုပ်လုပ်ရန်နှင့် နေထိုင်ရန် လိုအပ်သော အဆင့်များကို ကျွန်ုပ်တို့ စီစဉ်ထားပါသည်။",
    mn: "Бид таныг Солонгост ажиллаж, амьдрахад шаардлагатай алхмуудыг зохион байгуулсан",
    lo: "ພວກເຮົາໄດ້ຈັດລຽງຂັ້ນຕອນທີ່ທ່ານຕ້ອງການເພື່ອເຮັດວຽກ ແລະ ດຳລົງຊີວິດຢູ່ເກົາຫຼີ",
    tet:
        "Atu serbisu no moris iha Koreia, ami organiza ona pasu sira ne'ebé presiza.",
    ne: "कोरियामा काम गर्न र बस्नका लागि तपाईंलाई आवश्यक पर्ने चरणहरू व्यवस्थित गरेका छौं",
    zh: '我们整理了在韩国工作生活所需的各项手续',
    vi: 'Chúng tôi đã tổng hợp các thủ tục cần thiết để làm việc và sinh sống tại Hàn Quốc',
    uz: "Koreyada ishlash va yashash uchun zarur boʻlgan qadamlarni tartibga soldik",
  );
  static const visaLabel = L10nText(
    ko: 'MY VISA',
    en: 'MY VISA',
    tr: "VİZEM",
    tg: "РАВОДИДИ МАН",
    fil: "AKING VISA",
    ur: "میرا ویزا",
    th: "วีซ่าของฉัน",
    ky: "МЕНИН ВИЗАМ",
    km: "ទិដ្ឋាការរបស់ខ្ញុំ",
    id: "VISA SAYA",
    si: "මගේ වීසා",
    bn: "আমার ভিসা",
    my: "ကျွန်ုပ်၏ ဗီဇာ",
    mn: "МИНИЙ ВИЗ",
    lo: "ວີຊາຂອງຂ້ອຍ",
    tet: "HA'U NIA VIZA",
    ne: "मेरो भिसा",
    zh: 'MY VISA',
    vi: 'MY VISA',
    uz: "VIZAM",
  );
  static const visaValue = L10nText(
    ko: 'E-9 비전문취업',
    en: 'E-9 Non-professional',
    tr: "E-9 Niteliksiz",
    tg: "E-9 Ғайримутахассис",
    fil: "E-9 Hindi Kwalipikado",
    ur: "E-9 غیر ہنر مند",
    th: "E-9 แรงงานไร้ฝีมือ",
    ky: "E-9 Квалификациясыз",
    km: "E-9 មិនមានជំនាញ",
    id: "E-9 Tidak Terampil",
    si: "E-9 නුපුහුණු",
    bn: "E-9 অদক্ষ",
    my: "E-9 ကျွမ်းကျင်မှုမရှိသူ",
    mn: "E-9 Ур чадваргүй",
    lo: "E-9 ບໍ່ມີທັກສະ",
    tet: "E-9 La Kualifikadu",
    ne: "E-9 अकुशल",
    zh: 'E-9 非专业就业',
    vi: 'E-9 Lao động phổ thông',
    uz: "E-9 Malakasiz ishchi",
  );
  static const visaNotSet = L10nText(
    ko: '체류자격 미설정',
    en: 'Visa status not set',
    tr: "Vize durumu ayarlanmadı",
    tg: "Вазъи раводид танзим нашудааст",
    fil: "Hindi pa naayos ang status ng visa",
    ur: "ویزا کی حیثیت ایڈجسٹ نہیں کی گئی",
    th: "สถานะวีซ่ายังไม่ได้ตั้งค่า",
    ky: "Виза статусу жөнгө салынган эмес",
    km: "ស្ថានភាពទិដ្ឋាការមិនទាន់ត្រូវបានកំណត់",
    id: "Status visa belum diatur",
    si: "වීසා තත්ත්වය සකසා නැත",
    bn: "ভিসার অবস্থা সেট করা হয়নি",
    my: "ဗီဇာ အခြေအနေ သတ်မှတ်မထားပါ",
    mn: "Визний статус тохируулагдаагүй байна",
    lo: "ສະຖານະວີຊາຍັງບໍ່ໄດ້ຕັ້ງຄ່າ",
    tet: "Estatutu viza seidauk ajusta",
    ne: "भिसा स्थिति सेट गरिएको छैन",
    zh: '未设置居留资格',
    vi: 'Chưa đặt tư cách lưu trú',
    uz: "Viza holati oʻrnatilmagan",
  );
  static const visaNote = L10nText(
    ko: '연장 절차 확인하기 →',
    en: 'Check renewal steps →',
    tr: "Yenileme adımlarını kontrol et →",
    tg: "Қадамҳои навсозиро тафтиш кунед →",
    fil: "Suriin ang mga hakbang sa pag-renew →",
    ur: "تجدید کے مراحل چیک کریں →",
    th: "ตรวจสอบขั้นตอนการต่ออายุ →",
    ky: "Жаңыртуу кадамдарын текшерүү →",
    km: "ពិនិត្យមើលជំហានបន្ត →",
    id: "Periksa langkah-langkah perpanjangan →",
    si: "අලුත් කිරීමේ පියවර පරීක්ෂා කරන්න →",
    bn: "নবায়নের ধাপগুলো দেখুন →",
    my: "သက်တမ်းတိုးခြင်း အဆင့်များကို စစ်ဆေးပါ →",
    mn: "Шинэчлэх алхмуудыг шалгах →",
    lo: "ກວດສອບຂັ້ນຕອນການຕໍ່ອາຍຸ →",
    tet: "Verifika pasu renovasaun →",
    ne: "नवीकरणका चरणहरू जाँच गर्नुहोस् →",
    zh: '查看延长手续 →',
    vi: 'Xem thủ tục gia hạn →',
    uz: "Yangilash bosqichlarini tekshirish →",
  );
  static const visaNoteNotSet = L10nText(
    ko: '설정에서 등록하세요 →',
    en: 'Register it in Settings →',
    tr: "Ayarlar → bölümünden kaydedin",
    tg: "Аз танзимот → захира кунед",
    fil: "I-save mula sa seksyong Mga Setting →",
    ur: "سیٹنگز → سے محفوظ کریں",
    th: "บันทึกจากส่วนการตั้งค่า →",
    ky: "Жөндөөлөр → бөлүмүнөн сактаңыз",
    km: "រក្សាទុកពី ការកំណត់ →",
    id: "Simpan dari Pengaturan →",
    si: "සැකසීම් → වෙතින් සුරකින්න",
    bn: "সেটিংস → থেকে সেভ করুন",
    my: "ဆက်တင်များ → တွင် သိမ်းဆည်းပါ",
    mn: "Тохиргоо → хэсгээс хадгалах",
    lo: "ບັນທຶກຈາກ → ການຕັ້ງຄ່າ",
    tet: "Rai husi 'Settings' (Konfigurasaun) →",
    ne: "सेटिङहरू → बाट बचत गर्नुहोस्",
    zh: '请在设置中登记 →',
    vi: 'Đăng ký trong Cài đặt →',
    uz: "Sozlamalarda roʻyxatdan oʻtkazish →",
  );
  static const quickAccessLabel = L10nText(
    ko: '자주 보는 항목',
    en: 'WHAT YOU OPEN MOST',
    tr: "EN ÇOK AÇTIKLARINIZ",
    tg: "Аксар вақт кушодашудаҳо",
    fil: "PINAKAMADALAS MONG BINUBUKSAN",
    ur: "سب سے زیادہ کھولے گئے",
    th: "ที่เปิดบ่อยที่สุด",
    ky: "ЭҢ КӨП АЧКАНДАРЫҢЫЗ",
    km: "អ្វីដែលអ្នកបើកញឹកញាប់បំផុត",
    id: "PALING SERING DIBUKA",
    si: "ඔබ වැඩිපුරම විවෘත කළ දේ",
    bn: "আপনার সর্বাধিক খোলা",
    my: "အများဆုံး ဖွင့်ကြည့်ထားသည်များ",
    mn: "ХАМГИЙН ИХ НЭЭГДСЭН",
    lo: "ທີ່ທ່ານເປີດຫຼາຍທີ່ສຸດ",
    tet: "NE'EBÉ ITA-NIA HAFUNGAN BARAK LIU",
    ne: "धेरै पटक खोलिएका",
    zh: '常用项目',
    vi: 'MỤC BẠN HAY MỞ',
    uz: "ENG KOʻP OCHGANINGIZ",
  );
  static const searchHint = L10nText(
    ko: '필요한 정보를 검색하세요',
    en: 'Search for what you need',
    tr: "İhtiyacınız olanı arayın",
    tg: "Он чиро, ки ба шумо лозим аст, ҷустуҷӯ кунед",
    fil: "Hanapin ang kailangan mo",
    ur: "جو آپ کو چاہیے وہ تلاش کریں",
    th: "ค้นหาสิ่งที่คุณต้องการ",
    ky: "Керектүү нерсени издеңиз",
    km: "ស្វែងរកអ្វីដែលអ្នកត្រូវការ",
    id: "Cari apa yang Anda butuhkan",
    si: "ඔබට අවශ්‍ය දේ සොයන්න",
    bn: "আপনার যা প্রয়োজন তা অনুসন্ধান করুন",
    my: "သင်လိုအပ်သည်များကို ရှာဖွေပါ",
    mn: "Танд хэрэгтэй зүйлээ хайна уу",
    lo: "ຊອກຫາສິ່ງທີ່ທ່ານຕ້ອງການ",
    tet: "Buka buat ne'ebé Ita presiza",
    ne: "तपाईंलाई चाहिएको कुरा खोज्नुहोस्",
    zh: '搜索您需要的信息',
    vi: 'Tìm thông tin bạn cần',
    uz: "Kerakli narsani qidirish",
  );
  static const searchNoResults = L10nText(
    ko: '검색 결과가 없습니다.\n다른 단어로 검색해 보세요.',
    en: 'No results found.\nTry a different search term.',
    tr: "Sonuç bulunamadı.\nFarklı bir arama terimi deneyin.",
    tg: "Натиҷа ёфт нашуд.\nИбораи дигари ҷустуҷӯро санҷед.",
    fil: "Walang nakitang resulta.\nSubukan ang ibang termino sa paghahanap.",
    ur: "کوئی نتیجہ نہیں ملا۔\nایک مختلف تلاش کی اصطلاح آزمائیں۔",
    th: "ไม่พบผลลัพธ์\nลองใช้คำค้นหาอื่น",
    ky: "Натыйжа табылган жок.\nБашка издөө сөзүн колдонуп көрүңүз.",
    km: "រកមិនឃើញលទ្ធផលទេ។\nសូមសាកល្បងពាក្យស្វែងរកផ្សេងទៀត។",
    id: "Tidak ada hasil yang ditemukan.\nCoba istilah pencarian yang berbeda.",
    si: "ප්‍රතිඵල හමු නොවීය.\nවෙනත් සෙවුම් පදයක් උත්සාහ කරන්න.",
    bn: "কোনো ফলাফল পাওয়া যায়নি।\nএকটি ভিন্ন সার্চ টার্ম ব্যবহার করে দেখুন।",
    my: "ရလဒ်မတွေ့ပါ။\nအခြားရှာဖွေမှု စကားလုံးကို စမ်းကြည့်ပါ။",
    mn: "Үр дүн олдсонгүй.\nӨөр хайлтын нэр томьёо ашиглан хайна уу.",
    lo: "ບໍ່ພົບຜົນການຄົ້ນຫາ.\nລອງໃຊ້ຄຳຄົ້ນຫາອື່ນ.",
    tet: "La hetan rezultadu.\nKoko termu buka seluk.",
    ne: "कुनै नतिजा फेला परेन।\nफरक खोज शब्द प्रयोग गर्नुहोस्।",
    zh: '没有搜索结果。\n请尝试其他关键词。',
    vi: 'Không có kết quả.\nHãy thử từ khóa khác.',
    uz: "Hech qanday natija topilmadi.\nBoshqa qidiruv soʻzini sinab koʻring.",
  );
  static const searchEmptyPrompt = L10nText(
    ko: '카테고리 이름으로 검색해 보세요',
    en: 'Try searching by category name',
    tr: "Kategori adına göre aramayı deneyin",
    tg: "Кӯшиш кунед, ки аз рӯи номи категория ҷустуҷӯ кунед",
    fil: "Subukang maghanap ayon sa pangalan ng kategorya",
    ur: "زمرہ کے نام سے تلاش کرنے کی کوشش کریں",
    th: "ลองค้นหาตามชื่อหมวดหมู่",
    ky: "Категориянын аталышы боюнча издөөнү колдонуп көрүңүз",
    km: "សូមសាកល្បងស្វែងរកតាមឈ្មោះប្រភេទ",
    id: "Coba cari berdasarkan nama kategori",
    si: "ප්‍රවර්ග නාමය අනුව සෙවීමට උත්සාහ කරන්න",
    bn: "ক্যাটাগরির নাম দিয়ে সার্চ করার চেষ্টা করুন",
    my: "အမျိုးအစားအမည်ဖြင့် ရှာဖွေကြည့်ပါ",
    mn: "Ангиллын нэрээр хайж үзээрэй",
    lo: "ລອງຊອກຫາຕາມຊື່ໝວດໝູ່",
    tet: "Koko buka tuir naran kategoria",
    ne: "श्रेणीको नाम अनुसार खोज्ने प्रयास गर्नुहोस्",
    zh: '请尝试用分类名称搜索',
    vi: 'Hãy thử tìm theo tên danh mục',
    uz: "Kategoriya nomi boʻyicha qidirib koʻring",
  );
  static const soonBadge = L10nText(
    ko: '준비 중',
    en: 'Coming soon',
    tr: "Çok yakında",
    tg: "Ба қарибӣ",
    fil: "Malapit na",
    ur: "بہت جلد",
    th: "เร็วๆ นี้",
    ky: "Жакында",
    km: "នឹងមកដល់ឆាប់ៗនេះ",
    id: "Segera hadir",
    si: "ඉක්මනින් පැමිණේ",
    bn: "শীঘ্রই আসছে",
    my: "မကြာမီလာမည်",
    mn: "Удахгүй гарах",
    lo: "ຈະມາໃນໄວໆນີ້",
    tet: "Sei mai lalais",
    ne: "चाँडै आउँदैछ",
    zh: '准备中',
    vi: 'Sắp có',
    uz: "Tez orada",
  );
  static const notReady = L10nText(
    ko: '이 항목은 2차 단계에서 채웁니다.',
    en: 'This item will be added in the next phase.',
    tr: "Bu öğe bir sonraki aşamada eklenecektir.",
    tg: "Ин банд дар марҳилаи оянда илова карда мешавад.",
    fil: "Idaragdag ang item na ito sa susunod na yugto.",
    ur: "یہ آئٹم اگلے مرحلے میں شامل کیا جائے گا۔",
    th: "รายการนี้จะถูกเพิ่มในขั้นตอนถัดไป",
    ky: "Бул нерсе кийинки этапта кошулат.",
    km: "ធាតុនេះនឹងត្រូវបានបន្ថែមនៅក្នុងដំណាក់កាលបន្ទាប់។",
    id: "Item ini akan ditambahkan pada tahap berikutnya.",
    si: "මෙම අයිතමය ඊළඟ අදියරේදී එකතු කරනු ඇත.",
    bn: "এই আইটেমটি পরবর্তী ধাপে যোগ করা হবে।",
    my: "ဤအကြောင်းအရာကို နောက်တစ်ဆင့်တွင် ထည့်သွင်းပါမည်။",
    mn: "Энэ зүйл дараагийн шатанд нэмэгдэх болно.",
    lo: "ລາຍການນີ້ຈະຖືກເພີ່ມໃນໄລຍະຕໍ່ໄປ.",
    tet: "Item ida-ne'e sei tau iha faze tuir mai.",
    ne: "यो वस्तु अर्को चरणमा थपिनेछ।",
    zh: '该项目将在第二阶段补充。',
    vi: 'Mục này sẽ được bổ sung ở giai đoạn sau.',
    uz: "Bu element keyingi bosqichda qoʻshiladi.",
  );
  static const favoritesTitle = L10nText(
    ko: '★ 즐겨찾기',
    en: '★ Favorites',
    tr: "★ Favoriler",
    tg: "★ Дӯстдоштаҳо",
    fil: "★ Mga Paborito",
    ur: "★ پسندیدہ",
    th: "★ รายการโปรด",
    ky: "★ Сүйүктүүлөр",
    km: "★ ចំណូលចិត្ត",
    id: "★ Favorit",
    si: "★ ප්‍රියතමයන්",
    bn: "★ ফেভারিট",
    my: "★ အနှစ်သက်ဆုံးများ",
    mn: "★ Дуртай",
    lo: "★ ລາຍການທີ່ມັກ",
    tet: "★ Favoritu",
    ne: "★ मनपर्नेहरू",
    zh: '★ 收藏',
    vi: '★ Mục yêu thích',
    uz: "★ Sevimlilar",
  );
  static const favoritesSubtitle = L10nText(
    ko: '그룹·카테고리 어디서든 별표로 담을 수 있습니다',
    en: 'Star any group or item to keep it here',
    tr: "Burada tutmak için herhangi bir grubu veya öğeyi yıldızlayın",
    tg: "Барои дар ин ҷо нигоҳ доштан, ягон гурӯҳ ё бандиро ситорача гузоред",
    fil: "I-star ang anumang grupo o item para panatilihin dito",
    ur: "یہاں رکھنے کے لیے کسی بھی گروپ یا آئٹم کو ستارہ لگائیں",
    th: "ติดดาวกลุ่มหรือรายการใดก็ได้เพื่อเก็บไว้ที่นี่",
    ky: "Бул жерде сактоо үчүн каалаган топту же нерсени жылдызча менен белгилеңиз",
    km: "ដាក់ផ្កាយលើក្រុម ឬធាតុណាមួយដើម្បីរក្សាទុកវានៅទីនេះ",
    id: "Beri bintang pada grup atau item apa pun untuk menyimpannya di sini",
    si: "මෙහි තබා ගැනීමට ඕනෑම කණ්ඩායමක් හෝ අයිතමයක් තරු ලකුණු කරන්න",
    bn: "এখানে রাখতে যেকোনো গ্রুপ বা আইটেমকে স্টার করুন",
    my: "ဤနေရာတွင် ထားရှိရန် မည်သည့်အဖွဲ့ သို့မဟုတ် အကြောင်းအရာကိုမဆို ကြယ်ပွင့်မှတ်သားပါ",
    mn: "Энд хадгалахын тулд дурын бүлэг эсвэл зүйлийг од дарж тэмдэглэнэ үү",
    lo: "ຕິດດາວໃສ່ກຸ່ມ ຫຼື ລາຍການໃດໜຶ່ງເພື່ອເກັບໄວ້ທີ່ນີ້",
    tet: "Marka ho fitun grupu ka item ruma atu rai iha ne'e",
    ne: "यहाँ राख्नको लागि कुनै पनि समूह वा वस्तुलाई ताराङ्कित गर्नुहोस्",
    zh: '在任意分组或分类中点击星标即可收藏',
    vi: 'Nhấn dấu sao ở bất kỳ nhóm hay mục nào để lưu tại đây',
    uz: "Har qanday guruh yoki elementni bu yerda saqlash uchun yulduzcha bosing",
  );
  static const favoritesItemsLabel = L10nText(
    ko: '저장한 항목',
    en: 'Saved items',
    tr: "Kaydedilen öğeler",
    tg: "Бандиҳои захирашуда",
    fil: "Mga na-save na item",
    ur: "محفوظ کردہ آئٹمز",
    th: "รายการที่บันทึกไว้",
    ky: "Сакталган нерселер",
    km: "ធាតុដែលបានរក្សាទុក",
    id: "Item yang disimpan",
    si: "සුරකින ලද අයිතම",
    bn: "সংরক্ষিত আইটেম",
    my: "သိမ်းဆည်းထားသော အကြောင်းအရာများ",
    mn: "Хадгалсан зүйлс",
    lo: "ລາຍການທີ່ບັນທຶກໄວ້",
    tet: "Item sira ne'ebé rai ona",
    ne: "सुरक्षित गरिएका वस्तुहरू",
    zh: '已收藏项目',
    vi: 'Mục đã lưu',
    uz: "Saqlangan elementlar",
  );
  static const favoritesGroupsLabel = L10nText(
    ko: '저장한 그룹',
    en: 'Saved groups',
    tr: "Kaydedilen gruplar",
    tg: "Гурӯҳҳои захирашуда",
    fil: "Mga na-save na grupo",
    ur: "محفوظ کردہ گروپس",
    th: "กลุ่มที่บันทึกไว้",
    ky: "Сакталган топтор",
    km: "ក្រុមដែលបានរក្សាទុក",
    id: "Grup yang disimpan",
    si: "සුරකින ලද කණ්ඩායම්",
    bn: "সংরক্ষিত গ্রুপ",
    my: "သိမ်းဆည်းထားသော အဖွဲ့များ",
    mn: "Хадгалсан бүлгүүд",
    lo: "ກຸ່ມທີ່ບັນທຶກໄວ້",
    tet: "Grupu sira ne'ebé rai ona",
    ne: "सुरक्षित गरिएका समूहहरू",
    zh: '已收藏分组',
    vi: 'Nhóm đã lưu',
    uz: "Saqlangan guruhlar",
  );
  static const favoritesEmpty = L10nText(
    ko: '아직 담은 항목이 없습니다.\n목록에서 ☆를 눌러 자주 쓰는 항목을 담아두세요.',
    en: 'Nothing saved yet.\nTap ☆ on any item to keep it here.',
    tr: "Henüz hiçbir şey kaydedilmedi.\nBurada tutmak için herhangi bir öğedeki ☆ simgesine dokunun.",
    tg: "Ҳанӯз чизе захира нашудааст.\nБарои дар ин ҷо нигоҳ доштан, тасвири ☆-ро дар ягон банд пахш кунед.",
    fil:
        "Wala pang na-save.\nI-tap ang ☆ icon sa anumang item para panatilihin dito.",
    ur: "ابھی تک کچھ بھی محفوظ نہیں کیا گیا۔\nیہاں رکھنے کے لیے کسی بھی آئٹم پر ☆ آئیکن کو تھپتھپائیں۔",
    th: "ยังไม่มีการบันทึกใดๆ\nแตะไอคอน ☆ ในรายการใดก็ได้เพื่อเก็บไว้ที่นี่",
    ky: "Азырынча эч нерсе сакталган жок.\nБул жерде сактоо үчүн каалаган нерседеги ☆ белгисин басыңыз.",
    km: "មិនទាន់មានអ្វីត្រូវបានរក្សាទុកនៅឡើយទេ។\nប៉ះរូបតំណាង ☆ នៅលើធាតុណាមួយដើម្បីរក្សាទុកវានៅទីនេះ។",
    id: "Belum ada yang disimpan.\nKetuk ☆ pada item apa pun untuk menyimpannya di sini.",
    si: "තවම කිසිවක් සුරැකී නැත.\nමෙහි තබා ගැනීමට ඕනෑම අයිතමයක ඇති ☆ නිරූපකය තට්ටු කරන්න.",
    bn: "এখনও কিছু সেভ করা হয়নি।\nএখানে রাখতে যেকোনো আইটেমের ☆ আইকনে ট্যাপ করুন।",
    my: "ဘာမှ မသိမ်းဆည်းရသေးပါ။\nဤနေရာတွင် ထားရှိရန် မည်သည့်အကြောင်းအရာ၏ ☆ အိုင်ကွန်ကိုမဆို နှိပ်ပါ။",
    mn: "Одоогоор юу ч хадгалагдаагүй байна.\nЭнд хадгалахын тулд дурын зүйлийн ☆ тэмдэг дээр дарна уу.",
    lo: "ຍັງບໍ່ມີຫຍັງຖືກບັນທຶກໄວ້ເທື່ອ.\nແຕະທີ່ໄອຄອນ ☆ ໃນລາຍການໃດໜຶ່ງເພື່ອເກັບໄວ້ທີ່ນີ້.",
    tet:
        "Seidauk rai buat ida.\nBuka simbulu ☆ iha item ruma atu rai iha ne'e.",
    ne: "अहिलेसम्म केही पनि सुरक्षित गरिएको छैन।\nयहाँ राख्नको लागि कुनै पनि वस्तुमा रहेको ☆ आइकनमा ट्याप गर्नुहोस्।",
    zh: '还没有收藏的项目。\n请在列表中点击☆收藏常用项目。',
    vi: 'Chưa lưu mục nào.\nNhấn ☆ ở mục bất kỳ để lưu tại đây.',
    uz: "Hali hech narsa saqlanmagan.\nBu yerda saqlash uchun har qanday elementdagi ☆ tugmasini bosing.",
  );
  static const formTagAuto = L10nText(
    ko: '자동입력',
    en: 'Auto-filled',
    tr: "Otomatik dolduruldu",
    tg: "Худкор пур карда шуд",
    fil: "Awtomatikong napunan",
    ur: "خودکار طور پر بھرا گیا",
    th: "กรอกอัตโนมัติ",
    ky: "Автоматтык түрдө толтурулду",
    km: "បំពេញដោយស្វ័យប្រវត្តិ",
    id: "Terisi otomatis",
    si: "ස්වයංක්‍රීයව පුරවන ලදී",
    bn: "স্বয়ংক্রিয়ভাবে পূরণ করা হয়েছে",
    my: "အလိုအလျောက် ဖြည့်သွင်းပြီး",
    mn: "Автоматаар бөглөсөн",
    lo: "ຕື່ມຂໍ້ມູນອັດຕະໂນມັດ",
    tet: "Prenxe automátiku",
    ne: "स्वतः भरियो",
    zh: '自动填写',
    vi: 'Tự động điền',
    uz: "Avtomatik toʻldirilgan",
  );
  static const formTagBlank = L10nText(
    ko: '직접입력',
    en: 'You fill in',
    tr: "Siz doldurun",
    tg: "Шумо пур кунед",
    fil: "Ikaw ang magpuno",
    ur: "آپ بھریں",
    th: "คุณกรอกเอง",
    ky: "Өзүңүз толтуруңуз",
    km: "អ្នកបំពេញ",
    id: "Isi sendiri",
    si: "ඔබ පුරවන්න",
    bn: "আপনি পূরণ করুন",
    my: "သင်ဖြည့်သွင်းပါ",
    mn: "Та бөглөнө үү",
    lo: "ທ່ານຕື່ມຂໍ້ມູນ",
    tet: "Ita prenxe",
    ne: "तपाईंले भर्नुहोस्",
    zh: '需自行填写',
    vi: 'Tự nhập',
    uz: "Siz toʻldirasiz",
  );
  static const formTagRaw = L10nText(
    ko: '그대로 옮김',
    en: 'Copied as-is',
    tr: "Olduğu gibi kopyalandı",
    tg: "Ҳамон тавре ки буд, нусхабардорӣ шуд",
    fil: "Kinopya nang buo",
    ur: "جیسا ہے ویسا ہی کاپی کیا گیا",
    th: "คัดลอกตามเดิม",
    ky: "Ошол бойдон көчүрүлдү",
    km: "ចម្លងដូចដើម",
    id: "Disalin apa adanya",
    si: "එලෙසම පිටපත් කරන ලදී",
    bn: "যেমন আছে তেমন কপি করা হয়েছে",
    my: "အတိုင်းသား ကူးယူပြီး",
    mn: "Яг байгаагаар нь хуулсан",
    lo: "ສຳເນົາຕາມເດີມ",
    tet: "Kopia hanesan",
    ne: "जस्ताको तस्तै प्रतिलिपि गरियो",
    zh: '原样填写',
    vi: 'Chép nguyên văn',
    uz: "Oʻzgarishsiz nusxalandi",
  );
  static const previousPage = L10nText(
    ko: '이전',
    en: 'Previous',
    tr: "Önceki",
    tg: "Қаблӣ",
    fil: "Nakaraang",
    ur: "پچھلا",
    th: "ก่อนหน้า",
    ky: "Мурунку",
    km: "មុន",
    id: "Sebelumnya",
    si: "පෙර",
    bn: "পূর্ববর্তী",
    my: "ယခင်",
    mn: "Өмнөх",
    lo: "ກ່ອນໜ້າ",
    tet: "Anterior",
    ne: "अघिल्लो",
    zh: '上一页',
    vi: 'Trước',
    uz: "Oldingi",
  );
  static const nextPage = L10nText(
    ko: '다음',
    en: 'Next',
    tr: "İleri",
    tg: "Баъдӣ",
    fil: "Susunod",
    ur: "اگلا",
    th: "ถัดไป",
    ky: "Кийинки",
    km: "បន្ទាប់",
    id: "Lanjut",
    si: "ඊළඟ",
    bn: "পরবর্তী",
    my: "နောက်တစ်ခု",
    mn: "Дараах",
    lo: "ຕໍ່ໄປ",
    tet: "Tuir mai",
    ne: "अगाडि बढ्नुहोस्",
    zh: '下一页',
    vi: 'Tiếp',
    uz: "Keyingi",
  );
  static const sourceLabel = L10nText(
    ko: '출처',
    en: 'Source',
    tr: "Kaynak",
    tg: "Манбаъ",
    fil: "Pinagmulan",
    ur: "ماخذ",
    th: "แหล่งที่มา",
    ky: "Булак",
    km: "ប្រភព",
    id: "Sumber",
    si: "මූලාශ්‍රය",
    bn: "উৎস",
    my: "ရင်းမြစ်",
    mn: "Эх сурвалж",
    lo: "ແຫຼ່ງຂໍ້ມູນ",
    tet: "Fonte",
    ne: "स्रोत",
    zh: '来源',
    vi: 'Nguồn',
    uz: "Manba",
  );
  static String itemCount(AppLanguage lang, int n) {
    switch (lang) {
      case AppLanguage.ko:
        return '$n개 항목';
      case AppLanguage.uz:
        return "$n elementlar";
      case AppLanguage.en:
        return '$n items';
      case AppLanguage.tr:
        return "$n öğe";
      case AppLanguage.tg:
        return "$n банд";
      case AppLanguage.fil:
        return "$n item";
      case AppLanguage.ur:
        return "$n آئٹم";
      case AppLanguage.th:
        return "$n รายการ";
      case AppLanguage.ky:
        return "$n нерсе";
      case AppLanguage.km:
        return "$n ធាតុ";
      case AppLanguage.id:
        return "$n item";
      case AppLanguage.si:
        return "$n අයිතමය";
      case AppLanguage.bn:
        return "$n আইটেম";
      case AppLanguage.my:
        return "$n အကြောင်းအရာ";
      case AppLanguage.mn:
        return "$n зүйл";
      case AppLanguage.lo:
        return "$n ລາຍການ";
      case AppLanguage.tet:
        return "Item $n";
      case AppLanguage.ne:
        return "$n वस्तु";
      case AppLanguage.zh:
        return '$n个项目';
      case AppLanguage.vi:
        return '$n mục';
    }
  }
}
