import '../../../core/app_language.dart';

class BugReportStrings {
  static const title = L10nText(
    ko: '버그 리포트',
    en: 'Report a bug',
    tr: "Hata bildir",
    tg: "Хатогиро гузориш диҳед",
    fil: "Iulat ang Error",
    ur: "غلطی کی اطلاع دیں",
    th: "รายงานข้อผิดพลาด",
    ky: "Ката жөнүндө билдирүү",
    km: "រាយការណ៍កំហុស",
    id: "Laporkan bug",
    si: "දෝෂයක් වාර්තා කරන්න",
    bn: "একটি ত্রুটির প্রতিবেদন করুন",
    my: "အမှားအယွင်းတစ်ခုကို သတင်းပို့ပါ",
    mn: "Алдаа мэдэгдэх",
    lo: "ລາຍງານຂໍ້ຜິດພາດ",
    tet: "Relata erru",
    ne: "त्रुटि रिपोर्ट गर्नुहोस्",
    zh: '报告问题',
    vi: 'Báo cáo lỗi',
    uz: "Xato haqida xabar berish",
  );
  static const subject = L10nText(
    ko: '제목',
    en: 'Subject',
    tr: "Konu",
    tg: "Мавзӯъ",
    fil: "Paksa",
    ur: "موضوع",
    th: "หัวข้อ",
    ky: "Тема",
    km: "ប្រធានបទ",
    id: "Subjek",
    si: "විෂය",
    bn: "বিষয়",
    my: "အကြောင်းအရာ",
    mn: "Сэдэв",
    lo: "ຫົວຂໍ້",
    tet: "Asuntu",
    ne: "विषय",
    zh: '标题',
    vi: 'Tiêu đề',
    uz: "Mavzu",
  );
  static const description = L10nText(
    ko: '어떤 문제가 발생했나요?',
    en: 'What went wrong?',
    tr: "Ne yanlış gitti?",
    tg: "Чӣ хато шуд?",
    fil: "Ano ang naging problema?",
    ur: "کیا غلط ہوا؟",
    th: "เกิดข้อผิดพลาดอะไรขึ้นบ้าง",
    ky: "Эмне туура эмес болду?",
    km: "មានអ្វីខុស?",
    id: "Apa yang salah?",
    si: "වැරදුණේ කුමක්ද?",
    bn: "কী ভুল হয়েছে?",
    my: "ဘာတွေမှားယွင်းခဲ့တာလဲ။",
    mn: "Юу буруу болсон бэ?",
    lo: "ມີຫຍັງຜິດພາດ?",
    tet: "Saida mak la loos?",
    ne: "के गलत भयो?",
    zh: '发生了什么问题？',
    vi: 'Bạn gặp vấn đề gì?',
    uz: "Nima notoʻgʻri ketdi?",
  );
  static const hint = L10nText(
    ko: '문제가 발생한 화면과 순서, 예상한 동작을 알려주세요.',
    en: 'Describe the screen, steps to reproduce, and expected behavior.',
    tr: "Ekranı, yeniden oluşturma adımlarını ve beklenen davranışı açıklayın.",
    tg: "Экран, қадамҳои такрорӣ ва рафтори интизоршударо тавсиф кунед.",
    fil:
        "Ilarawan ang screen, ang mga hakbang para muling gawin, at ang inaasahang mangyari.",
    ur: "اسکرین، دوبارہ بنانے کے اقدامات، اور متوقع رویے کی وضاحت کریں۔",
    th: "โปรดอธิบายหน้าจอ ขั้นตอนการทำซ้ำ และพฤติกรรมที่คาดหวัง",
    ky: "Экранды, кайра түзүү кадамдарын жана күтүлгөн жүрүм-турумду сүрөттөп бериңиз.",
    km: "សូមពន្យល់អំពីអេក្រង់ ជំហានដើម្បីបង្កើតឡើងវិញ និងអាកប្បកិរិយាដែលរំពឹងទុក។",
    id: "Jelaskan layar, langkah-langkah untuk mereproduksi, dan perilaku yang diharapkan.",
    si: "තිරය, ප්‍රතිනිෂ්පාදන පියවර සහ අපේක්ෂිත හැසිරීම විස්තර කරන්න.",
    bn: "স্ক্রিন, পুনরায় তৈরি করার ধাপ এবং প্রত্যাশিত আচরণ বর্ণনা করুন।",
    my: "မျက်နှာပြင်၊ ပြန်လည်ဖန်တီးခြင်းအဆင့်များနှင့် မျှော်မှန်းထားသည့် အပြုအမူကို ဖော်ပြပါ။",
    mn: "Дэлгэц, дахин үүсгэх алхмууд болон хүлээгдэж буй үйлдлийг тайлбарлана уу.",
    lo: "ອະທິບາຍໜ້າຈໍ, ຂັ້ນຕອນການສ້າງຄືນໃໝ່ ແລະ ການກະທຳທີ່ຄາດຫວັງ.",
    tet: "Deskreve ekran, pasu sira atu halo fali, no hahalok ne'ebé espera.",
    ne: "स्क्रिन, पुनरुत्पादन चरणहरू र अपेक्षित व्यवहारको वर्णन गर्नुहोस्।",
    zh: '请描述出错页面、操作步骤和预期结果。',
    vi: 'Mô tả màn hình, các bước gây lỗi và kết quả mong đợi.',
    uz: "Ekranni, takrorlash bosqichlarini va kutilgan xatti-harakatni tasvirlang.",
  );
  static const required = L10nText(
    ko: '내용을 입력해주세요.',
    en: 'Please fill in this field.',
    tr: "Lütfen bu alanı doldurun.",
    tg: "Лутфан ин майдонро пур кунед.",
    fil: "Mangyaring punan ang patlang na ito.",
    ur: "براہ کرم یہ خانہ پُر کریں۔",
    th: "กรุณากรอกข้อมูลในช่องนี้",
    ky: "Сураныч, бул талааны толтуруңуз.",
    km: "សូមបំពេញក្នុងប្រអប់នេះ។",
    id: "Mohon isi kolom ini.",
    si: "කරුණාකර මෙම ක්ෂේත්‍රය පුරවන්න.",
    bn: "অনুগ্রহ করে এই ক্ষেত্রটি পূরণ করুন।",
    my: "ကျေးဇူးပြု၍ ဤအကွက်ကို ဖြည့်ပါ။",
    mn: "Энэ талбарыг бөглөнө үү.",
    lo: "ກະລຸນາຕື່ມຂໍ້ມູນໃສ່ຊ່ອງນີ້.",
    tet: "Favor preenxe kampu ne'e.",
    ne: "कृपया यो क्षेत्र भर्नुहोस्।",
    zh: '请填写此项。',
    vi: 'Vui lòng điền mục này.',
    uz: "Iltimos, ushbu maydonni toʻldiring.",
  );
  static const open = L10nText(
    ko: '메일 앱에서 보내기',
    en: 'Send using email app',
    tr: "E-posta uygulaması kullanarak gönder",
    tg: "Бо истифода аз барномаи почтаи электронӣ фиристед",
    fil: "Ipadala gamit ang email app",
    ur: "ای میل ایپ کا استعمال کرتے ہوئے بھیجیں",
    th: "ส่งโดยใช้แอปอีเมล",
    ky: "Электрондук почта тиркемесин колдонуп жөнөтүү",
    km: "ផ្ញើដោយប្រើកម្មវិធីអ៊ីមែល",
    id: "Kirim menggunakan aplikasi email",
    si: "විද්‍යුත් තැපැල් යෙදුම භාවිතයෙන් යවන්න",
    bn: "ইমেল অ্যাপ ব্যবহার করে পাঠান",
    my: "အီးမေးလ်အက်ပ်ကို အသုံးပြု၍ ပေးပို့ပါ",
    mn: "Имэйл апп ашиглан илгээх",
    lo: "ສົ່ງໂດຍໃຊ້ແອັບອີເມວ",
    tet: "Haruka uza aplikasaun email",
    ne: "इमेल एप प्रयोग गरेर पठाउनुहोस्",
    zh: '通过邮件应用发送',
    vi: 'Gửi bằng ứng dụng email',
    uz: "Elektron pochta ilovasi orqali yuborish",
  );
  static const note = L10nText(
    ko: '메일 작성창에서 내용을 확인하고 전송해주세요.',
    en: 'Review and send the report in your email app.',
    tr: "Raporu e-posta uygulamanızda inceleyin ve gönderin.",
    tg: "Гузоришро дар барномаи почтаи электронии худ баррасӣ кунед ва фиристед.",
    fil: "Suriin at ipadala ang ulat sa iyong email app.",
    ur: "اپنی ای میل ایپ میں رپورٹ کا جائزہ لیں اور بھیجیں۔",
    th: "ตรวจสอบและส่งรายงานในแอปอีเมลของคุณ",
    ky: "Отчетту электрондук почта тиркемеңизде карап чыгып, жөнөтүңүз.",
    km: "សូមពិនិត្យមើល និងផ្ញើរបាយការណ៍នៅក្នុងកម្មវិធីអ៊ីមែលរបស់អ្នក។",
    id: "Tinjau dan kirim laporan di aplikasi email Anda.",
    si: "ඔබගේ විද්‍යුත් තැපැල් යෙදුම තුළ වාර්තාව සමාලෝචනය කර යවන්න.",
    bn: "আপনার ইমেল অ্যাপে প্রতিবেদনটি পর্যালোচনা করুন এবং পাঠান।",
    my: "သင်၏အီးမေးလ်အက်ပ်တွင် အစီရင်ခံစာကို ပြန်လည်သုံးသပ်ပြီး ပေးပို့ပါ။",
    mn: "Имэйл апп дотроо тайланг хянаж илгээнэ үү.",
    lo: "ກວດສອບ ແລະ ສົ່ງລາຍງານໃນແອັບອີເມວຂອງທ່ານ.",
    tet: "Haree no haruka relatóriu iha ita-nia aplikasaun email.",
    ne: "आफ्नो इमेल एपमा रिपोर्ट समीक्षा गर्नुहोस् र पठाउनुहोस्।",
    zh: '请在邮件应用中确认内容并发送。',
    vi: 'Kiểm tra và gửi báo cáo trong ứng dụng email.',
    uz: "Hisobotni elektron pochta ilovangizda koʻrib chiqing va yuboring.",
  );
  static const copy = L10nText(
    ko: '내용 복사',
    en: 'Copy report',
    tr: "Raporu kopyala",
    tg: "Гузоришро нусхабардорӣ кунед",
    fil: "Kopyahin ang Ulat",
    ur: "رپورٹ کاپی کریں",
    th: "คัดลอกรายงาน",
    ky: "Отчетту көчүрүү",
    km: "ចម្លងរបាយការណ៍",
    id: "Salin laporan",
    si: "වාර්තාව පිටපත් කරන්න",
    bn: "প্রতিবেদন কপি করুন",
    my: "အစီရင်ခံစာကို ကူးယူပါ",
    mn: "Тайланг хуулах",
    lo: "ສຳເນົາລາຍງານ",
    tet: "Kopia relatóriu",
    ne: "रिपोर्ट प्रतिलिपि गर्नुहोस्",
    zh: '复制报告',
    vi: 'Sao chép báo cáo',
    uz: "Hisobotni nusxalash",
  );
  static const copied = L10nText(
    ko: '수신 주소와 내용을 복사했습니다.',
    en: 'Recipient and report copied.',
    tr: "Alıcı ve rapor kopyalandı.",
    tg: "Қабулкунанда ва гузориш нусхабардорӣ шуд.",
    fil: "Kinopya ang tatanggap at ulat.",
    ur: "وصول کنندہ اور رپورٹ کاپی کر لی گئی ہے۔",
    th: "ผู้รับและรายงานถูกคัดลอกแล้ว",
    ky: "Алуучу жана отчет көчүрүлдү.",
    km: "អ្នកទទួល និងរបាយការណ៍ត្រូវបានចម្លងហើយ។",
    id: "Penerima dan laporan telah disalin.",
    si: "ලබන්නා සහ වාර්තාව පිටපත් කරන ලදී.",
    bn: "প্রাপক এবং প্রতিবেদন কপি করা হয়েছে।",
    my: "လက်ခံသူနှင့် အစီရင်ခံစာကို ကူးယူပြီးပါပြီ။",
    mn: "Хүлээн авагч болон тайланг хуулсан.",
    lo: "ຜູ້ຮັບ ແລະ ລາຍງານຖືກສຳເນົາແລ້ວ.",
    tet: "Simu-na'in no relatóriu kopia ona.",
    ne: "प्राप्तकर्ता र रिपोर्ट प्रतिलिपि गरियो।",
    zh: '已复制收件地址和报告。',
    vi: 'Đã sao chép địa chỉ nhận và báo cáo.',
    uz: "Qabul qiluvchi va hisobot nusxalandi.",
  );
  static const copyFailed = L10nText(
    ko: '복사하지 못했습니다. 입력한 내용을 직접 복사해주세요.',
    en: 'Could not copy. Please copy the text manually.',
    tr: "Kopyalanamadı. Lütfen metni manuel olarak kopyalayın.",
    tg: "Нусхабардорӣ нашуд. Лутфан матнро дастӣ нусхабардорӣ кунед.",
    fil: "Hindi makopya. Mangyaring kopyahin nang mano-mano ang teksto.",
    ur: "کاپی نہیں ہو سکی۔ براہ کرم متن کو دستی طور پر کاپی کریں۔",
    th: "ไม่สามารถคัดลอกได้ โปรดคัดลอกข้อความด้วยตนเอง",
    ky: "Көчүрүлгөн жок. Сураныч, текстти кол менен көчүрүңүз.",
    km: "មិនអាចចម្លងបានទេ។ សូមចម្លងអត្ថបទដោយដៃ។",
    id: "Gagal menyalin. Mohon salin teks secara manual.",
    si: "පිටපත් කිරීමට නොහැකි විය. කරුණාකර අතින් පිටපත් කරන්න.",
    bn: "কপি করা যায়নি। অনুগ্রহ করে ম্যানুয়ালি টেক্সট কপি করুন।",
    my: "ကူးယူ၍မရပါ။ ကျေးဇူးပြု၍ စာသားကို ကိုယ်တိုင်ကူးယူပါ။",
    mn: "Хуулж чадсангүй. Текстийг гараар хуулна уу.",
    lo: "ບໍ່ສາມາດສຳເນົາໄດ້. ກະລຸນາສຳເນົາຂໍ້ຄວາມດ້ວຍຕົນເອງ.",
    tet: "La konsege kopia. Favor kopia testu ho liman.",
    ne: "प्रतिलिपि गर्न सकिएन। कृपया पाठ म्यानुअल रूपमा प्रतिलिपि गर्नुहोस्।",
    zh: '无法复制，请手动复制内容。',
    vi: 'Không thể sao chép. Vui lòng sao chép thủ công.',
    uz: "Nusxalashning iloji boʻlmadi. Iltimos, matnni qoʻlda nusxalang.",
  );
  static const failed = L10nText(
    ko: '메일 앱을 열지 못했습니다. 내용을 복사해 아래 주소로 보내주세요.',
    en: 'Could not open an email app. Copy the report and send it to the address below.',
    tr: "E-posta uygulaması açılamadı. Raporu kopyalayın ve aşağıdaki adrese gönderin.",
    tg: "Барномаи почтаи электронӣ кушода нашуд. Гузоришро нусхабардорӣ кунед ва ба суроғаи зерин фиристед.",
    fil:
        "Hindi mabuksan ang email app. Kopyahin ang ulat at ipadala sa sumusunod na address.",
    ur: "ای میل ایپ نہیں کھولی جا سکی۔ رپورٹ کاپی کریں اور درج ذیل پتے پر بھیجیں۔",
    th: "ไม่สามารถเปิดแอปอีเมลได้ โปรดคัดลอกรายงานและส่งไปยังที่อยู่ด้านล่าง",
    ky: "Электрондук почта тиркемеси ачылган жок. Отчетту көчүрүп, төмөнкү дарекке жөнөтүңүз.",
    km: "មិនអាចបើកកម្មវិធីអ៊ីមែលបានទេ។ សូមចម្លងរបាយការណ៍ ហើយផ្ញើទៅកាន់អាសយដ្ឋានខាងក្រោម។",
    id: "Gagal membuka aplikasi email. Mohon salin laporan dan kirim ke alamat berikut.",
    si: "විද්‍යුත් තැපැල් යෙදුම විවෘත කිරීමට නොහැකි විය. වාර්තාව පිටපත් කර පහත ලිපිනයට යවන්න.",
    bn: "ইমেল অ্যাপ খোলা যায়নি। প্রতিবেদনটি কপি করুন এবং নিম্নলিখিত ঠিকানায় পাঠান।",
    my: "အီးမေးလ်အက်ပ်ကို ဖွင့်၍မရပါ။ အစီရင်ခံစာကို ကူးယူပြီး အောက်ပါလိပ်စာသို့ ပေးပို့ပါ။",
    mn: "Имэйл апп нээгдсэнгүй. Тайланг хуулаад дараах хаягаар илгээнэ үү.",
    lo: "ບໍ່ສາມາດເປີດແອັບອີເມວໄດ້. ກະລຸນາສຳເນົາລາຍງານ ແລະ ສົ່ງໄປທີ່ທີ່ຢູ່ລຸ່ມນີ້.",
    tet:
        "Aplikasaun email la bele loke. Kopia relatóriu no haruka ba enderezu iha kraik.",
    ne: "इमेल एप खोल्न सकिएन। रिपोर्ट प्रतिलिपि गर्नुहोस् र तलको ठेगानामा पठाउनुहोस्।",
    zh: '无法打开邮件应用，请复制报告并发送至以下地址。',
    vi: 'Không mở được ứng dụng email. Sao chép báo cáo và gửi đến địa chỉ bên dưới.',
    uz: "Elektron pochta ilovasini ochib boʻlmadi. Hisobotni nusxalang va quyidagi manzilga yuboring.",
  );
}
