import '../../../core/app_language.dart';

/// 설정 탭 UI 문구.
class SettingsStrings {
  SettingsStrings._();

  static const eyebrow = L10nText(
    ko: 'MY SETTINGS',
    en: 'MY SETTINGS',
    tr: "AYARLARIM",
    tg: "ТАНЗИМОТИ МАН",
    fil: "AKING MGA SETTING",
    ur: "میری ترتیبات",
    th: "การตั้งค่าของฉัน",
    ky: "МЕНИН ЖӨНДӨӨЛӨРҮМ",
    km: "ការកំណត់របស់ខ្ញុំ",
    id: "PENGATURAN SAYA",
    si: "මගේ සැකසුම්",
    bn: "আমার সেটিংস",
    my: "ကျွန်ုပ်၏ ဆက်တင်များ",
    mn: "МИНЬ ТОХИРГОО",
    lo: "ການຕັ້ງຄ່າຂອງຂ້ອຍ",
    tet: "HA'U-NIA DEFINISAUN SIRA",
    ne: "मेरा सेटिङहरू",
    zh: 'MY SETTINGS',
    vi: 'MY SETTINGS',
    uz: "MENING SOZLAMALARIM",
  );
  static const tabTitle = L10nText(
    ko: '설정',
    en: 'Settings',
    tr: "Ayarlar",
    tg: "Танзимот",
    fil: "Mga Setting",
    ur: "ترتیبات",
    th: "การตั้งค่า",
    ky: "Жөндөөлөр",
    km: "ការកំណត់",
    id: "Pengaturan",
    si: "සැකසීම්",
    bn: "সেটিংস",
    my: "ဆက်တင်များ",
    mn: "Тохиргоо",
    lo: "ການຕັ້ງຄ່າ",
    tet: "Definisaun",
    ne: "सेटिङहरू",
    zh: '设置',
    vi: 'Cài đặt',
    uz: "Sozlamalar",
  );

  // ---------- 프로필 요약 카드 ----------
  static const guestName = L10nText(
    ko: '게스트',
    en: 'Guest',
    tr: "Misafir",
    tg: "Меҳмон",
    fil: "Bisita",
    ur: "مہمان",
    th: "ผู้เยี่ยมชม",
    ky: "Конок",
    km: "ភ្ញៀវ",
    id: "Tamu",
    si: "ආගන්තුක",
    bn: "অতিথি",
    my: "ဧည့်သည်",
    mn: "Зочин",
    lo: "ແຂກ",
    tet: "Vizitante",
    ne: "अतिथि",
    zh: '访客',
    vi: 'Khách',
    uz: "Mehmon",
  );
  static const guestSubtitle = L10nText(
    ko: '모든 기록을 안전하게 이어가세요.',
    en: 'Keep all your records safely.',
    tr: "Tüm kayıtlarınızı güvenle saklayın.",
    tg: "Ҳама сабтҳои худро бехатар нигоҳ доред.",
    fil: "Ligtas na itago ang lahat ng iyong tala.",
    ur: "اپنے تمام ریکارڈز کو محفوظ طریقے سے رکھیں۔",
    th: "จัดเก็บข้อมูลบันทึกทั้งหมดของคุณอย่างปลอดภัย",
    ky: "Бардык жазууларыңызды коопсуз сактаңыз.",
    km: "រក្សាទុកកំណត់ត្រាទាំងអស់របស់អ្នកដោយសុវត្ថិភាព។",
    id: "Simpan semua catatan Anda dengan aman.",
    si: "ඔබගේ සියලු වාර්තා ආරක්ෂිතව තබා ගන්න.",
    bn: "আপনার সমস্ত রেকর্ড নিরাপদে রাখুন।",
    my: "သင်၏ မှတ်တမ်းအားလုံးကို လုံခြုံစွာ သိမ်းဆည်းပါ။",
    mn: "Бүх бүртгэлээ найдвартай хадгалаарай.",
    lo: "ເກັບຮັກສາບັນທຶກທັງໝົດຂອງທ່ານຢ່າງປອດໄພ.",
    tet: "Rai didi'ak ita-nia rejistu hotu-hotu.",
    ne: "आफ्ना सबै रेकर्डहरू सुरक्षित रूपमा भण्डारण गर्नुहोस्।",
    zh: '安全地延续您的所有记录。',
    vi: 'Giữ an toàn mọi bản ghi của bạn.',
    uz: "Barcha yozuvlaringizni xavfsiz saqlang.",
  );
  static const loginButton = L10nText(
    ko: '로그인',
    en: 'Log in',
    tr: "Giriş yap",
    tg: "Ворид шудан",
    fil: "Mag-log in",
    ur: "لاگ ان کریں",
    th: "เข้าสู่ระบบ",
    ky: "Кирүү",
    km: "ចូលគណនី",
    id: "Masuk",
    si: "පිවිසෙන්න",
    bn: "লগ ইন করুন",
    my: "ဝင်ရောက်ပါ",
    mn: "Нэвтрэх",
    lo: "ເຂົ້າສູ່ລະບົບ",
    tet: "Login",
    ne: "लगइन गर्नुहोस्",
    zh: '登录',
    vi: 'Đăng nhập',
    uz: "Kirish",
  );

  // ---------- 기본 설정 카드 ----------
  static const languageLabel = L10nText(
    ko: '언어 설정',
    en: 'Language',
    tr: "Dil",
    tg: "Забон",
    fil: "Wika",
    ur: "زبان",
    th: "ภาษา",
    ky: "Тил",
    km: "ភាសា",
    id: "Bahasa",
    si: "භාෂාව",
    bn: "ভাষা",
    my: "ဘာသာစကား",
    mn: "Хэл",
    lo: "ພາສາ",
    tet: "Lian",
    ne: "भाषा",
    zh: '语言设置',
    vi: 'Ngôn ngữ',
    uz: "Til",
  );
  static const visaLabel = L10nText(
    ko: '비자 정보',
    en: 'Visa info',
    tr: "Vize bilgileri",
    tg: "Маълумоти раводид",
    fil: "Impormasyon sa visa",
    ur: "ویزا کی معلومات",
    th: "ข้อมูลวีซ่า",
    ky: "Виза маалыматы",
    km: "ព័ត៌មានទិដ្ឋាការ",
    id: "Informasi visa",
    si: "වීසා තොරතුරු",
    bn: "ভিসার তথ্য",
    my: "ဗီဇာအချက်အလက်",
    mn: "Визний мэдээлэл",
    lo: "ຂໍ້ມູນວີຊາ",
    tet: "Informasaun viza",
    ne: "भिसा जानकारी",
    zh: '签证信息',
    vi: 'Thông tin visa',
    uz: "Viza maʼlumotlari",
  );
  static const profileLabel = L10nText(
    ko: '프로필',
    en: 'Profile',
    tr: "Profil",
    tg: "Профил",
    fil: "Profile",
    ur: "پروفائل",
    th: "โปรไฟล์",
    ky: "Профиль",
    km: "ប្រវត្តិរូប",
    id: "Profil",
    si: "පැතිකඩ",
    bn: "প্রোফাইল",
    my: "ပရိုဖိုင်",
    mn: "Профайл",
    lo: "ໂປຣໄຟລ໌",
    tet: "Profil",
    ne: "प्रोफाइल",
    zh: '个人资料',
    vi: 'Hồ sơ',
    uz: "Profil",
  );
  static const notificationLabel = L10nText(
    ko: '알림 설정',
    en: 'Notifications',
    tr: "Bildirimler",
    tg: "Огоҳиҳо",
    fil: "Mga Abiso",
    ur: "اطلاعات",
    th: "การแจ้งเตือน",
    ky: "Эскертмелер",
    km: "ការជូនដំណឹង",
    id: "Notifikasi",
    si: "දැනුම්දීම්",
    bn: "বিজ্ঞপ্তি",
    my: "အသိပေးချက်များ",
    mn: "Мэдэгдлүүд",
    lo: "ການແຈ້ງເຕືອນ",
    tet: "Notifikasaun sira",
    ne: "सूचनाहरू",
    zh: '通知设置',
    vi: 'Thông báo',
    uz: "Bildirishnomalar",
  );
  static const notificationOn = L10nText(
    ko: '켜짐',
    en: 'On',
    tr: "Açık",
    tg: "Офтобӣ",
    fil: "Maaliwalas",
    ur: "صاف",
    th: "แจ่มใส",
    ky: "Ачык",
    km: "អាកាសធាតុស្រឡះ",
    id: "Cerah",
    si: "පැහැදිලියි",
    bn: "পরিষ্কার",
    my: "သာယာကြည်လင်",
    mn: "Цэлмэг",
    lo: "ແຈ່ມໃສ",
    tet: "Nakloke",
    ne: "खुला",
    zh: '已开启',
    vi: 'Bật',
    uz: "Yoqish",
  );
  static const notificationOff = L10nText(
    ko: '꺼짐',
    en: 'Off',
    tr: "Kapalı",
    tg: "Хомӯш",
    fil: "Naka-off",
    ur: "بند",
    th: "ปิด",
    ky: "Өчүк",
    km: "បិទ",
    id: "Mati",
    si: "අක්‍රියයි",
    bn: "বন্ধ",
    my: "ပိတ်ထားသည်",
    mn: "Унтраалттай",
    lo: "ປິດ",
    tet: "Mate",
    ne: "बन्द",
    zh: '已关闭',
    vi: 'Tắt',
    uz: "Oʻchirish",
  );
  static const notificationToast = L10nText(
    ko: '알림 설정은 이 기기에만 저장돼요.',
    en: 'Notification settings are saved on this device only.',
    tr: "Bildirim ayarları yalnızca bu cihaza kaydedilir.",
    tg: "Танзимоти огоҳиҳо танҳо дар ин дастгоҳ сабт мешаванд.",
    fil: "Ang mga setting ng abiso ay nai-save lamang sa device na ito.",
    ur: "اطلاعات کی ترتیبات صرف اس ڈیوائس پر محفوظ کی جاتی ہیں۔",
    th: "การตั้งค่าการแจ้งเตือนจะถูกบันทึกไว้ในอุปกรณ์นี้เท่านั้น",
    ky: "Эскертме жөндөөлөрү бул түзмөккө гана сакталат.",
    km: "ការកំណត់ការជូនដំណឹងត្រូវបានរក្សាទុកសម្រាប់តែឧបករណ៍នេះប៉ុណ្ណោះ។",
    id: "Pengaturan notifikasi hanya disimpan di perangkat ini.",
    si: "දැනුම්දීම් සැකසීම් මෙම උපාංගයේ පමණක් සුරැකේ.",
    bn: "বিজ্ঞপ্তি সেটিংস শুধুমাত্র এই ডিভাইসে সংরক্ষিত হয়।",
    my: "အသိပေးချက်ဆက်တင်များကို ဤစက်ပစ္စည်းတွင်သာ သိမ်းဆည်းထားသည်။",
    mn: "Мэдэгдлийн тохиргоог зөвхөн энэ төхөөрөмжид хадгална.",
    lo: "ການຕັ້ງຄ່າການແຈ້ງເຕືອນຈະຖືກບັນທຶກໄວ້ໃນອຸປະກອນນີ້ເທົ່ານັ້ນ.",
    tet: "Definisaun notifikasaun sira rai de'it iha aparatu ne'e.",
    ne: "सूचना सेटिङहरू यस यन्त्रमा मात्र सुरक्षित हुन्छन्।",
    zh: '通知设置仅保存在此设备上。',
    vi: 'Cài đặt thông báo chỉ được lưu trên thiết bị này.',
    uz: "Bildirishnoma sozlamalari faqat shu qurilmada saqlanadi.",
  );
  static const visaNotSet = L10nText(
    ko: '미설정',
    en: 'Not set',
    tr: "Ayarlanmadı",
    tg: "Танзим нашудааст",
    fil: "Hindi Naitakda",
    ur: "سیٹ نہیں کیا گیا",
    th: "ยังไม่ได้ตั้งค่า",
    ky: "Орнотулган эмес",
    km: "មិនបានកំណត់",
    id: "Belum diatur",
    si: "සකසා නැත",
    bn: "সেট করা হয়নি",
    my: "သတ်မှတ်မထားပါ",
    mn: "Тохируулагдаагүй",
    lo: "ບໍ່ໄດ້ຕັ້ງຄ່າ",
    tet: "La define",
    ne: "सेट गरिएको छैन",
    zh: '未设置',
    vi: 'Chưa đặt',
    uz: "Oʻrnatilmagan",
  );

  // ---------- 부가 설정 카드 ----------
  static const vaultLabel = L10nText(
    ko: '내 증빙 보관함',
    en: 'My document vault',
    tr: "Belge kasam",
    tg: "Ҷузвдони ҳуҷҷатҳои ман",
    fil: "Aking document vault",
    ur: "دستاویزات کا والٹ",
    th: "ตู้เก็บเอกสารของฉัน",
    ky: "Документтерим",
    km: "កន្លែងផ្ទុកឯកសាររបស់ខ្ញុំ",
    id: "Kotak dokumen saya",
    si: "මගේ ලේඛන ගබඩාව",
    bn: "আমার ডকুমেন্ট বক্স",
    my: "ကျွန်ုပ်၏ စာရွက်စာတမ်းသေတ္တာ",
    mn: "Баримт бичгийн сан",
    lo: "ຕູ້ເກັບເອກະສານຂອງຂ້ອຍ",
    tet: "Ha'u-nia kofre dokumentu",
    ne: "मेरो कागजात भण्डार",
    zh: '我的证明保管箱',
    vi: 'Kho tài liệu của tôi',
    uz: "Mening hujjatlar omborim",
  );
  static const closeButton = L10nText(
    ko: '닫기',
    en: 'Close',
    tr: "Kapat",
    tg: "Пӯшидан",
    fil: "Isara",
    ur: "بند کریں",
    th: "ปิด",
    ky: "Жабуу",
    km: "បិទ",
    id: "Tutup",
    si: "වසා දමන්න",
    bn: "বন্ধ করুন",
    my: "ပိတ်မည်",
    mn: "Хаах",
    lo: "ປິດ",
    tet: "Taka",
    ne: "बन्द गर्नुहोस्",
    zh: '关闭',
    vi: 'Đóng',
    uz: "Yopish",
  );
  static const guideLabel = L10nText(
    ko: '사용 가이드',
    en: 'User guide',
    tr: "Kullanım kılavuzu",
    tg: "Дастури истифодабарӣ",
    fil: "Manwal ng Gumagamit",
    ur: "استعمال کا دستور العمل",
    th: "คู่มือการใช้งาน",
    ky: "Колдонуучунун колдонмосу",
    km: "សៀវភៅណែនាំអ្នកប្រើប្រាស់",
    id: "Panduan pengguna",
    si: "පරිශීලක අත්පොත",
    bn: "ব্যবহারের নির্দেশিকা",
    my: "အသုံးပြုသူလက်စွဲ",
    mn: "Хэрэглэгчийн гарын авлага",
    lo: "ຄູ່ມືການນຳໃຊ້",
    tet: "Guia utilizadór",
    ne: "प्रयोगकर्ता पुस्तिका",
    zh: '使用说明',
    vi: 'Hướng dẫn sử dụng',
    uz: "Foydalanuvchi qoʻllanmasi",
  );
  static const aiGuideLabel = L10nText(
    ko: 'AI 가이드',
    en: 'AI guide',
    tr: "Yapay zeka rehberi",
    tg: "Роҳнамоии зеҳни сунъӣ",
    fil: "AI Guide",
    ur: "مصنوعی ذہانت کا رہنما",
    th: "คู่มือ AI",
    ky: "Жасалма интеллект жол көрсөткүчү",
    km: "មគ្គុទ្ទេសក៍ AI",
    id: "Panduan AI",
    si: "AI මාර්ගෝපදේශය",
    bn: "এআই গাইড",
    my: "AI လမ်းညွှန်",
    mn: "Хиймэл оюун ухааны удирдамж",
    lo: "ຄູ່ມື AI",
    tet: "Gia intelijénsia artifisiál",
    ne: "एआई गाइड",
    zh: 'AI向导',
    vi: 'Hướng dẫn AI',
    uz: "AI yoʻriqnomasi",
  );

  // ---------- 프로필 편집 모달 ----------
  static const profileEditTitle = L10nText(
    ko: '프로필',
    en: 'Profile',
    tr: "Profil",
    tg: "Профил",
    fil: "Profile",
    ur: "پروفائل",
    th: "โปรไฟล์",
    ky: "Профиль",
    km: "ប្រវត្តិរូប",
    id: "Profil",
    si: "පැතිකඩ",
    bn: "প্রোফাইল",
    my: "ပရိုဖိုင်",
    mn: "Профайл",
    lo: "ໂປຣໄຟລ໌",
    tet: "Profil",
    ne: "प्रोफाइल",
    zh: '个人资料',
    vi: 'Hồ sơ',
    uz: "Profil",
  );
  static const nameFieldLabel = L10nText(
    ko: '이름',
    en: 'Name',
    tr: "Ad",
    tg: "Ном",
    fil: "Pangalan",
    ur: "نام",
    th: "ชื่อ",
    ky: "Аты-жөнү",
    km: "ឈ្មោះ",
    id: "Nama",
    si: "නම",
    bn: "নাম",
    my: "အမည်",
    mn: "Нэр",
    lo: "ຊື່",
    tet: "Naran",
    ne: "नाम",
    zh: '姓名',
    vi: 'Họ tên',
    uz: "Ism",
  );
  static const nationalityFieldLabel = L10nText(
    ko: '국적',
    en: 'Nationality',
    tr: "Uyruk",
    tg: "Миллат",
    fil: "Nasyonalidad",
    ur: "قومیت",
    th: "สัญชาติ",
    ky: "Улуту",
    km: "សញ្ជាតិ",
    id: "Kebangsaan",
    si: "ජාතිකත්වය",
    bn: "জাতীয়তা",
    my: "နိုင်ငံသား",
    mn: "Иргэншил",
    lo: "ສັນຊາດ",
    tet: "Nasaun",
    ne: "राष्ट्रियता",
    zh: '国籍',
    vi: 'Quốc tịch',
    uz: "Millat",
  );
  static const nationalityPlaceholder = L10nText(
    ko: '국적을 선택해주세요',
    en: 'Select your nationality',
    tr: "Uyruğunuzu seçin",
    tg: "Миллати худро интихоб кунед",
    fil: "Piliin ang iyong nasyonalidad",
    ur: "اپنی قومیت منتخب کریں",
    th: "เลือกสัญชาติของคุณ",
    ky: "Улутуңузду тандаңыз",
    km: "ជ្រើសរើសសញ្ជាតិរបស់អ្នក។",
    id: "Pilih kebangsaan Anda",
    si: "ඔබගේ ජාතිකත්වය තෝරන්න",
    bn: "আপনার জাতীয়তা নির্বাচন করুন",
    my: "သင်၏ နိုင်ငံသားကို ရွေးချယ်ပါ",
    mn: "Иргэншлээ сонгоно уу",
    lo: "ເລືອກສັນຊາດຂອງທ່ານ",
    tet: "Hili Ita-nia nasaun",
    ne: "आफ्नो राष्ट्रियता छान्नुहोस्",
    zh: '请选择国籍',
    vi: 'Chọn quốc tịch của bạn',
    uz: "Millatingizni tanlang",
  );
  static const saveButton = L10nText(
    ko: '저장',
    en: 'Save',
    tr: "Kaydet",
    tg: "Захира кардан",
    fil: "I-save",
    ur: "محفوظ کریں",
    th: "บันทึก",
    ky: "Сактоо",
    km: "រក្សាទុក",
    id: "Simpan",
    si: "සුරකින්න",
    bn: "সংরক্ষণ করুন",
    my: "သိမ်းဆည်းရန်",
    mn: "Хадгалах",
    lo: "ບັນທຶກ",
    tet: "Rai",
    ne: "बचत गर्नुहोस्",
    zh: '保存',
    vi: 'Lưu',
    uz: "Saqlash",
  );
  static const profileSaved = L10nText(
    ko: '저장했어요.',
    en: 'Saved.',
    tr: "Kaydedildi.",
    tg: "Захира шуд.",
    fil: "Nai-save.",
    ur: "محفوظ کر لیا گیا۔",
    th: "บันทึกแล้ว",
    ky: "Сакталды.",
    km: "បានរក្សាទុកហើយ។",
    id: "Tersimpan.",
    si: "සුරැකිණි.",
    bn: "সংরক্ষিত হয়েছে।",
    my: "သိမ်းဆည်းပြီးပါပြီ။",
    mn: "Хадгалагдсан.",
    lo: "ບັນທຶກແລ້ວ.",
    tet: "Rai ona.",
    ne: "बचत गरियो।",
    zh: '已保存。',
    vi: 'Đã lưu.',
    uz: "Saqlandi.",
  );
  static const errorName = L10nText(
    ko: '이름을 입력해주세요',
    en: 'Please enter your name',
    tr: "Lütfen adınızı girin",
    tg: "Лутфан, номи худро ворид кунед",
    fil: "Pakipasok ang iyong pangalan",
    ur: "براہ کرم اپنا نام درج کریں۔",
    th: "กรุณากรอกชื่อของคุณ",
    ky: "Сураныч, атыңызды киргизиңиз",
    km: "សូមបញ្ចូលឈ្មោះរបស់អ្នក។",
    id: "Mohon masukkan nama Anda",
    si: "කරුණාකර ඔබගේ නම ඇතුළත් කරන්න",
    bn: "অনুগ্রহ করে আপনার নাম লিখুন",
    my: "ကျေးဇူးပြု၍ သင့်အမည်ကို ထည့်သွင်းပါ",
    mn: "Та өөрийн нэрийг оруулна уу",
    lo: "ກະລຸນາໃສ່ຊື່ຂອງທ່ານ",
    tet: "Favor ida, hatama Ita-nia naran",
    ne: "कृपया आफ्नो नाम प्रविष्ट गर्नुहोस्",
    zh: '请输入姓名',
    vi: 'Vui lòng nhập họ tên',
    uz: "Iltimos, ismingizni kiriting",
  );
  static const errorCustomVisa = L10nText(
    ko: '체류자격을 입력해주세요',
    en: 'Please enter your visa status',
    tr: "Lütfen vize durumunuzu girin",
    tg: "Лутфан, ҳолати раводиди худро ворид кунед",
    fil: "Pakipasok ang iyong visa status",
    ur: "براہ کرم اپنی ویزا کی حیثیت درج کریں۔",
    th: "กรุณากรอกสถานะวีซ่าของคุณ",
    ky: "Сураныч, виза статусуңузду киргизиңиз",
    km: "សូមបញ្ចូលស្ថានភាពទិដ្ឋាការរបស់អ្នក។",
    id: "Mohon masukkan status visa Anda",
    si: "කරුණාකර ඔබගේ වීසා තත්ත්වය ඇතුළත් කරන්න",
    bn: "অনুগ্রহ করে আপনার ভিসার অবস্থা লিখুন",
    my: "ကျေးဇူးပြု၍ သင်၏ ဗီဇာအခြေအနေကို ထည့်သွင်းပါ",
    mn: "Та визийн статусаа оруулна уу",
    lo: "ກະລຸນາໃສ່ສະຖານະວີຊາຂອງທ່ານ",
    tet: "Favor ida, hatama Ita-nia estatutu viza",
    ne: "कृपया आफ्नो भिसा स्थिति प्रविष्ट गर्नुहोस्",
    zh: '请输入居留资格',
    vi: 'Vui lòng nhập tư cách lưu trú',
    uz: "Iltimos, viza holatingizni kiriting",
  );

  // ---------- 로그아웃 / 하단 ----------
  static const logoutButton = L10nText(
    ko: '로그아웃',
    en: 'Log out',
    tr: "Çıkış yap",
    tg: "Баромадан",
    fil: "Mag-log out",
    ur: "لاگ آؤٹ کریں",
    th: "ออกจากระบบ",
    ky: "Чыгуу",
    km: "ចេញពីគណនី",
    id: "Keluar",
    si: "ලොග් අවුට් වන්න",
    bn: "লগ আউট করুন",
    my: "အကောင့်ထွက်ရန်",
    mn: "Гарах",
    lo: "ອອກຈາກລະບົບ",
    tet: "Sai",
    ne: "लग आउट गर्नुहोस्",
    zh: '登出',
    vi: 'Đăng xuất',
    uz: "Chiqish",
  );
  static const bottomNote = L10nText(
    ko: 'Local Bridge\n수원시 이주민 노동·생활 정보',
    en: 'Local Bridge\nSuwon migrant worker & daily-life information',
    tr: "Local Bridge\nSuwon göçmen işçi ve günlük yaşam bilgileri",
    tg: "Local Bridge\nМаълумот барои коргарони муҳоҷир ва ҳаёти ҳаррӯза дар Сувон",
    fil:
        "Local Bridge\nImpormasyon para sa migranteng manggagawa at pang-araw-araw na buhay sa Suwon",
    ur: "Local Bridge\nسوون تارکین وطن مزدور اور روزمرہ زندگی کی معلومات",
    th: "Local Bridge\nข้อมูลแรงงานข้ามชาติและชีวิตประจำวันในซูวอน",
    ky: "Local Bridge\nСувон шаарындагы мигрант жумушчулар жана күнүмдүк жашоо маалыматы",
    km: "Local Bridge\nព័ត៌មានសម្រាប់ពលករចំណាកស្រុក និងជីវភាពរស់នៅប្រចាំថ្ងៃនៅ Suwon",
    id: "Local Bridge\nInformasi pekerja migran dan kehidupan sehari-hari Suwon",
    si: "Local Bridge\nසුවොන් සංක්‍රමණික සේවක සහ දෛනික ජීවිත තොරතුරු",
    bn: "Local Bridge\nসুওন অভিবাসী শ্রমিক এবং দৈনন্দিন জীবনের তথ্য",
    my: "Local Bridge\nဆူဝမ် ရွှေ့ပြောင်းလုပ်သားနှင့် နေ့စဉ်ဘဝအချက်အလက်များ",
    mn: "Local Bridge\nСувон хот дахь цагаач ажилчдын хөдөлмөр ба өдөр тутмын амьдралын мэдээлэл",
    lo: "Local Bridge\nຂໍ້ມູນແຮງງານເຄື່ອນຍ້າຍ ແລະ ຊີວິດປະຈຳວັນຂອງເມືອງຊູວອນ",
    tet:
        "Local Bridge\nInformasaun ba traballadór migrante no moris loron-loron iha Suwon",
    ne: "लोकल ब्रिज\nसुवन आप्रवासी कामदार र दैनिक जीवन जानकारी",
    zh: 'Local Bridge\n水原市移民劳动·生活信息',
    vi: 'Local Bridge\nThông tin lao động & đời sống người di cư Suwon',
    uz: "Local Bridge\nSuvonlik migrant ishchilar va kundalik hayot maʼlumotlari",
  );
}
