import '../../../core/app_language.dart';

class OnboardingGuideModuleText {
  const OnboardingGuideModuleText({
    required this.title,
    required this.description,
  });

  final L10nText title;
  final L10nText description;
}

class OnboardingGuideStrings {
  OnboardingGuideStrings._();

  static const pageTitle = L10nText(
    ko: 'Local Bridge 사용 설명서',
    en: 'Local Bridge User Guide',
    tr: "Local Bridge Kullanım Kılavuzu",
    tg: "Local Bridge Дастури истифодабарӣ",
    fil: "Local Bridge Gabay sa Paggamit",
    ur: "Local Bridge استعمال کا دستور العمل",
    th: "คู่มือการใช้งาน Local Bridge",
    ky: "Local Bridge Колдонуучунун колдонмосу",
    km: "Local Bridge សៀវភៅណែនាំអ្នកប្រើប្រាស់",
    id: "Panduan Pengguna Local Bridge",
    si: "Local Bridge පරිශීලක මාර්ගෝපදේශය",
    bn: "Local Bridge ব্যবহারকারী নির্দেশিকা",
    my: "Local Bridge အသုံးပြုသူလမ်းညွှန်",
    mn: "Local Bridge-ийн хэрэглээний гарын авлага",
    lo: "ຄູ່ມືການໃຊ້ງານ Local Bridge",
    tet: "Manuais Uzu Local Bridge",
    ne: "लोकल ब्रिज प्रयोगकर्ता पुस्तिका",
    zh: 'Local Bridge 使用指南',
    vi: 'Hướng dẫn sử dụng Local Bridge',
    uz: "Local Bridge foydalanuvchi qoʻllanmasi",
  );

  static const pageSubtitle = L10nText(
    ko: '주요 기능과 이용 방법을 한눈에 확인하세요.',
    en: 'See the main features and how to use them at a glance.',
    tr: "Ana özellikleri ve nasıl kullanılacağını bir bakışta görün.",
    tg: "Хусусиятҳои асосӣ ва тарзи истифодаи онҳоро дар як нигоҳ бубинед.",
    fil:
        "Tingnan ang mga pangunahing tampok at kung paano gamitin ang mga ito sa isang sulyap.",
    ur: "ایک نظر میں اہم خصوصیات اور ان کے استعمال کا طریقہ دیکھیں۔",
    th: "ดูคุณสมบัติหลักและวิธีใช้งานได้อย่างรวดเร็ว",
    ky: "Негизги функцияларды жана аларды кантип колдонууну бир карап көрүңүз.",
    km: "មើលលក្ខណៈពិសេសសំខាន់ៗ និងរបៀបប្រើប្រាស់វាដោយក្រឡេកមើល។",
    id: "Lihat fitur utama dan cara menggunakannya secara sekilas.",
    si: "ප්‍රධාන විශේෂාංග සහ ඒවා භාවිතා කරන ආකාරය එකවර බලන්න.",
    bn: "এক নজরে প্রধান বৈশিষ্ট্য এবং কিভাবে এটি ব্যবহার করতে হয় তা দেখুন।",
    my: "အဓိကလုပ်ဆောင်ချက်များနှင့် အသုံးပြုပုံကို တစ်ချက်ကြည့်လိုက်ပါ။",
    mn: "Үндсэн функцууд болон тэдгээрийг хэрхэн ашиглахыг нэг дороос харна уу.",
    lo: "ເບິ່ງຄຸນສົມບັດຫຼັກ ແລະ ວິທີໃຊ້ງານໄດ້ຢ່າງວ່ອງໄວ.",
    tet: "Haree karakterístika prinsipál no oinsá uza sira ho lalais.",
    ne: "मुख्य विशेषताहरू र कसरी प्रयोग गर्ने भन्ने एक नजरमा हेर्नुहोस्।",
    zh: '快速了解主要功能及使用方法。',
    vi: 'Xem nhanh các chức năng chính và cách sử dụng.',
    uz: "Asosiy xususiyatlar va ulardan qanday foydalanishni bir qarashda koʻring.",
  );

  static const tagline = L10nText(
    ko: 'AI 기반 외국인 노동자를 위한 정보제공 및 권익보호 플랫폼',
    en: 'An AI-powered information and rights protection platform for migrant workers',
    tr: "Göçmen işçiler için yapay zeka destekli bilgi ve hak koruma platformu",
    tg: "Платформаи иттилоотӣ ва ҳифзи ҳуқуқ бо дастгирии зеҳни сунъӣ барои коргарони муҳоҷир",
    fil:
        "AI-powered na impormasyon at platform sa pagprotekta ng karapatan para sa mga migranteng manggagawa",
    ur: "مہاجر کارکنوں کے لیے اے آئی سے چلنے والا معلومات اور حقوق کے تحفظ کا پلیٹ فارم",
    th: "แพลตฟอร์มข้อมูลและการคุ้มครองสิทธิ์ที่ขับเคลื่อนด้วย AI สำหรับแรงงานข้ามชาติ",
    ky: "Мигрант жумушчулар үчүн жасалма интеллект колдогон маалымат жана укуктарды коргоо платформасы",
    km: "វេទិកាការពារសិទ្ធិ និងព័ត៌មានដែលគាំទ្រដោយ AI សម្រាប់ពលករចំណាកស្រុក",
    id: "Platform perlindungan hak dan informasi yang didukung AI untuk pekerja migran",
    si: "සංක්‍රමණික සේවකයන් සඳහා AI-බලයෙන් ක්‍රියාත්මක වන තොරතුරු සහ අයිතිවාසිකම් ආරක්ෂණ වේදිකාව",
    bn: "অভিবাসী কর্মীদের জন্য এআই-চালিত তথ্য এবং অধিকার সুরক্ষা প্ল্যাটফর্ম",
    my: "ရွှေ့ပြောင်းအလုပ်သမားများအတွက် AI-အထောက်အပံ့ပေးသော အချက်အလက်နှင့် အခွင့်အရေးကာကွယ်ရေး ပလက်ဖောင်း",
    mn: "Цагаач ажилчдад зориулсан хиймэл оюун ухаанд суурилсан мэдээлэл, эрх хамгаалах платформ",
    lo: "ແພລດຟອມຂໍ້ມູນ ແລະ ການປົກປ້ອງສິດທິທີ່ຮອງຮັບດ້ວຍ AI ສຳລັບແຮງງານເຄື່ອນຍ້າຍ",
    tet:
        "Plataforma informasaun no protesaun direitu ho intelijénsia artifisiál ba traballadór migrante sira",
    ne: "आप्रावासी कामदारहरूको लागि एआई-समर्थित जानकारी र अधिकार संरक्षण प्लेटफर्म",
    zh: '面向外籍劳动者的 AI 信息服务与权益保护平台',
    vi: 'Nền tảng AI cung cấp thông tin và bảo vệ quyền lợi cho lao động nước ngoài',
    uz: "Migrant ishchilar uchun sunʼiy intellektga asoslangan axborot va huquqlarni himoya qilish platformasi",
  );

  static const introduction = L10nText(
    ko: "'Local Bridge'는 지역 사회(Local)와 외국인 노동자를 유기적으로 연결(Bridge)한다는 뜻으로, 외국인 노동자들의 정보 격차 문제를 해소하고 모국어 기반의 사전 권익 보호와 사후 문제 해결을 추구하는 AI 통합 플랫폼입니다.",
    en: "'Local Bridge' means organically connecting local communities with migrant workers. It is an integrated AI platform that aims to close information gaps and support both preventive rights protection and post-incident problem solving in each worker's native language.",
    tr: "'Local Bridge', yerel toplulukları göçmen işçilerle organik olarak birleştirmek anlamına gelir. Bilgi boşluklarını kapatmayı ve her işçinin ana dilinde hem önleyici hak korumasını hem de olay sonrası problem çözmeyi desteklemeyi amaçlayan entegre bir yapay zeka platformudur.",
    tg: "'Local Bridge' маънои ба таври органикӣ муттаҳид кардани ҷомеаҳои маҳаллӣ бо коргарони муҳоҷирро дорад. Ин як платформаи муттаҳидшудаи зеҳни сунъӣ мебошад, ки ҳадафаш бартараф кардани камбудиҳои иттилоотӣ ва дастгирии ҳам ҳифзи пешгирикунандаи ҳуқуқ ва ҳам ҳалли мушкилоти пас аз ҳодиса бо забони модарии ҳар як коргар аст.",
    fil:
        "Ang 'Local Bridge' ay nangangahulugang organikong pag-uugnay ng mga lokal na komunidad sa mga migranteng manggagawa. Ito ay isang pinagsamang AI platform na naglalayong tulay ang mga agwat sa impormasyon at suportahan ang parehong preventive na proteksyon ng karapatan at post-incident na paglutas ng problema sa sariling wika ng bawat manggagawa.",
    ur: "'Local Bridge' کا مطلب ہے مقامی کمیونٹیز کو مہاجر کارکنوں کے ساتھ باضابطہ طور پر جوڑنا۔ یہ ایک مربوط اے آئی پلیٹ فارم ہے جس کا مقصد معلومات کے خلا کو پُر کرنا اور ہر کارکن کی مادری زبان میں قبل از وقت حقوق کے تحفظ اور واقعہ کے بعد مسائل کے حل دونوں کی حمایت کرنا ہے۔",
    th: "'Local Bridge' หมายถึงการเชื่อมโยงชุมชนท้องถิ่นเข้ากับแรงงานข้ามชาติอย่างเป็นธรรมชาติ เป็นแพลตฟอร์ม AI แบบบูรณาการที่มุ่งปิดช่องว่างข้อมูลและสนับสนุนการคุ้มครองสิทธิ์เชิงป้องกันและการแก้ไขปัญหาหลังเกิดเหตุการณ์ในภาษาแม่ของแรงงานแต่ละคน",
    ky: "'Local Bridge' жергиликтүү жамааттарды мигрант жумушчулар менен органикалык түрдө бириктирүүнү билдирет. Бул маалыматтык боштуктарды жоюуга жана ар бир жумушчунун эне тилинде алдын алуучу укуктарды коргоого, ошондой эле окуядан кийинки көйгөйлөрдү чечүүгө жардам берүүгө багытталган интеграцияланган жасалма интеллект платформасы.",
    km: "'Local Bridge' មានន័យថាការភ្ជាប់សហគមន៍មូលដ្ឋានជាមួយពលករចំណាកស្រុកដោយសរីរាង្គ។ វាគឺជាវេទិកា AI រួមបញ្ចូលគ្នាដែលមានគោលបំណងបិទគម្លាតព័ត៌មាន និងគាំទ្រទាំងការការពារសិទ្ធិបង្ការ និងការដោះស្រាយបញ្ហាក្រោយហេតុការណ៍ជាភាសាកំណើតរបស់កម្មករម្នាក់ៗ។",
    id: "'Local Bridge' berarti secara organik menghubungkan komunitas lokal dengan pekerja migran. Ini adalah platform AI terintegrasi yang bertujuan untuk menjembatani kesenjangan informasi dan mendukung perlindungan hak preventif serta penyelesaian masalah pasca-insiden dalam bahasa ibu setiap pekerja.",
    si: "'Local Bridge' යනු දේශීය ප්‍රජාවන් සංක්‍රමණික සේවකයන් සමඟ කාබනිකව සම්බන්ධ කිරීමයි. එය තොරතුරු පරතරයන් පියවා ගැනීමට සහ සෑම සේවකයෙකුගේම මව් භාෂාවෙන් පූර්ව ආරක්ෂණ අයිතිවාසිකම් ආරක්ෂාවට සහ සිදුවීමෙන් පසු ගැටළු විසඳීමට සහාය වීම අරමුණු කරගත් ඒකාබද්ධ AI වේදිකාවකි.",
    bn: "'Local Bridge' মানে স্থানীয় সম্প্রদায়কে অভিবাসী কর্মীদের সাথে জৈবিকভাবে সংযুক্ত করা। এটি একটি সমন্বিত এআই প্ল্যাটফর্ম যার লক্ষ্য হল তথ্যের ব্যবধান পূরণ করা এবং প্রতিটি কর্মীর মাতৃভাষায় প্রতিরোধমূলক অধিকার সুরক্ষা এবং ঘটনার পরে সমস্যা সমাধান উভয়কেই সমর্থন করা।",
    my: "'Local Bridge' ဆိုသည်မှာ ဒေသခံလူမှုအသိုင်းအဝိုင်းများကို ရွှေ့ပြောင်းအလုပ်သမားများနှင့် သဘာဝအတိုင်း ချိတ်ဆက်ပေးခြင်းကို ဆိုလိုသည်။ ၎င်းသည် အချက်အလက်ကွာဟမှုများကို ပေါင်းကူးပေးရန်နှင့် အလုပ်သမားတစ်ဦးစီ၏ မိခင်ဘာသာစကားဖြင့် ကြိုတင်ကာကွယ်ရေးအခွင့်အရေးကာကွယ်မှုနှင့် ဖြစ်ရပ်ပြီးနောက် ပြဿနာဖြေရှင်းမှု နှစ်ခုလုံးကို ပံ့ပိုးပေးရန် ရည်ရွယ်သည့် ပေါင်းစပ် AI ပလက်ဖောင်းတစ်ခုဖြစ်သည်။",
    mn: "'Local Bridge' гэдэг нь орон нутгийн иргэдийг цагаач ажилчидтай органик байдлаар холбох гэсэн утгатай. Энэ нь мэдээллийн цоорхойг нөхөж, ажилчин бүрийн эх хэлээр эрхийг урьдчилан хамгаалах, мөн асуудал гарсан үед шийдвэрлэхэд дэмжлэг үзүүлэх зорилготой нэгдсэн хиймэл оюун ухааны платформ юм.",
    lo: "'Local Bridge' ໝາຍເຖິງການເຊື່ອມໂຍງຊຸມຊົນທ້ອງຖິ່ນເຂົ້າກັບແຮງງານເຄື່ອນຍ້າຍຢ່າງເປັນລະບົບ. ມັນເປັນແພລດຟອມ AI ແບບລວມສູນທີ່ແນໃສ່ປິດຊ່ອງຫວ່າງຂໍ້ມູນ ແລະ ສະໜັບສະໜູນທັງການປົກປ້ອງສິດທິແບບປ້ອງກັນ ແລະ ການແກ້ໄຂບັນຫາຫຼັງເກີດເຫດໃນພາສາກຳເນີດຂອງແຮງງານແຕ່ລະຄົນ.",
    tet:
        "'Local Bridge' signifika liga komunidade lokál ho traballadór migrante sira ho orgániku. Neʼe mak plataforma intelijénsia artifisiál integradu ida neʼebé ho objetivu atu taka informasaun neʼebé la kompletu no fó apoiu ba protesaun direitu preventivu no rezolusaun problema depois akontesimentu iha lian inan traballadór ida-idak nian.",
    ne: "'लोकल ब्रिज' को अर्थ स्थानीय समुदायहरूलाई आप्रावासी कामदारहरूसँग जैविक रूपमा जोड्नु हो। यसले जानकारीको कमीलाई पूरा गर्ने र प्रत्येक कामदारको मातृभाषामा दुवै निवारक अधिकार संरक्षण र घटना पछिको समस्या समाधानलाई समर्थन गर्ने लक्ष्य राखेको एक एकीकृत एआई प्लेटफर्म हो।",
    zh: '“Local Bridge”寓意将地方社区（Local）与外籍劳动者有机连接（Bridge）。这是一个 AI 综合平台，旨在缩小外籍劳动者的信息差距，并以其母语提供事前权益保护和事后问题解决支持。',
    vi: "'Local Bridge' mang ý nghĩa kết nối chặt chẽ cộng đồng địa phương (Local) với người lao động nước ngoài (Bridge). Đây là nền tảng AI tích hợp nhằm thu hẹp khoảng cách thông tin, bảo vệ quyền lợi từ sớm và hỗ trợ giải quyết vấn đề sau khi phát sinh bằng tiếng mẹ đẻ của người lao động.",
    uz: "'Local Bridge' mahalliy jamoalarni migrant ishchilar bilan organik ravishda bogʻlashni anglatadi. Bu axborot boʻshliqlarini yopish va har bir ishchining ona tilida ham profilaktik huquqlarni himoya qilishni, ham hodisadan keyingi muammolarni hal qilishni qoʻllab-quvvatlashga qaratilgan integratsiyalashgan sunʼiy intellekt platformasidir.",
  );

  static const modules = <OnboardingGuideModuleText>[
    OnboardingGuideModuleText(
      title: L10nText(
        ko: '네비게이터',
        en: 'Navigator',
        tr: "Rehber",
        tg: "Роҳнамо",
        fil: "Gabay",
        ur: "رہنما",
        th: "คู่มือ",
        ky: "Жол көрсөткүч",
        km: "មគ្គុទ្ទេសក៍",
        id: "Panduan",
        si: "මාර්ගෝපදේශය",
        bn: "গাইড",
        my: "လမ်းညွှန်",
        mn: "Удирдамж",
        lo: "ຄູ່ມື",
        tet: "Gia",
        ne: "गाइड",
        zh: '导航',
        vi: 'Điều hướng',
        uz: "Navigator",
      ),
      description: L10nText(
        ko: '임금체불·산재처리 중 필요한 것을 고르면 신고·신청서 작성까지 단계별로 안내합니다.',
        en: 'Choose whether you need help with unpaid wages or a workplace injury, and get step-by-step guidance all the way to filling out the report.',
        tr: "Ödenmemiş ücretler veya iş kazası konusunda yardıma ihtiyacınız olup olmadığını seçin ve raporu doldurmaya kadar adım adım rehberlik alın.",
        tg: "Интихоб кунед, ки оё ба шумо дар мавриди музди меҳнати пардохтнашуда ё садамаи корӣ кӯмак лозим аст ва дастури қадам ба қадамро то пур кардани гузориш гиред.",
        fil:
            "Piliin kung kailangan mo ng tulong sa hindi nabayarang sahod o aksidente sa trabaho, at makakuha ng sunud-sunod na gabay hanggang sa pagpuno ng ulat.",
        ur: "منتخب کریں کہ آیا آپ کو غیر ادا شدہ اجرت یا کام کے حادثے کے بارے میں مدد کی ضرورت ہے، اور رپورٹ پُر کرنے تک قدم بہ قدم رہنمائی حاصل کریں۔",
        th: "เลือกความช่วยเหลือที่คุณต้องการ ไม่ว่าจะเป็นค่าจ้างค้างจ่ายหรืออุบัติเหตุจากการทำงาน และรับคำแนะนำทีละขั้นตอนจนกว่าจะกรอกรายงานเสร็จสมบูรณ์",
        ky: "Төлөнбөгөн эмгек акы же өндүрүштүк кырсык боюнча жардам керекпи же жокпу тандаңыз жана отчетту толтурууга чейинки кадам-кадам көрсөтмөлөрдү алыңыз.",
        km: "ជ្រើសរើសថាតើអ្នកត្រូវការជំនួយសម្រាប់ប្រាក់ឈ្នួលមិនទាន់បានបង់ ឬគ្រោះថ្នាក់ការងារ ហើយទទួលបានការណែនាំជាជំហានៗរហូតដល់ការបំពេញរបាយការណ៍។",
        id: "Pilih apakah Anda memerlukan bantuan dengan upah yang belum dibayar atau kecelakaan kerja, dan dapatkan panduan langkah demi langkah hingga mengisi laporan.",
        si: "ගෙවා නොමැති වැටුප් හෝ කාර්මික අනතුරක් සම්බන්ධයෙන් ඔබට උපකාර අවශ්‍ය දැයි තෝරාගෙන, වාර්තාවක් ගොනු කිරීම දක්වා පියවරෙන් පියවර මඟ පෙන්වීමක් ලබා ගන්න.",
        bn: "আপনার বকেয়া বেতন বা কর্মক্ষেত্রে আঘাতের বিষয়ে সাহায্যের প্রয়োজন আছে কিনা তা নির্বাচন করুন এবং রিপোর্ট পূরণ করা পর্যন্ত ধাপে ধাপে নির্দেশনা পান।",
        my: "လုပ်ခမရရှိခြင်း သို့မဟုတ် လုပ်ငန်းခွင်ထိခိုက်မှုအတွက် အကူအညီလိုအပ်ခြင်းရှိမရှိ ရွေးချယ်ပြီး အစီရင်ခံစာဖြည့်သွင်းခြင်းအထိ အဆင့်ဆင့်လမ်းညွှန်မှုကို ရယူပါ။",
        mn: "Цалин хөлсөө аваагүй эсвэл үйлдвэрлэлийн ослын талаар тусламж хэрэгтэй эсэхийг сонгоод, тайланг бөглөх хүртэл алхам алхмаар зааварчилгаа аваарай.",
        lo: "ເລືອກວ່າທ່ານຕ້ອງການຄວາມຊ່ວຍເຫຼືອດ້ານຄ່າຈ້າງທີ່ຄ້າງຈ່າຍ ຫຼື ອຸບັດຕິເຫດໃນບ່ອນເຮັດວຽກ ແລະ ຮັບຄຳແນະນຳເທື່ອລະຂັ້ນຕອນຈົນເຖິງການຕື່ມບົດລາຍງານ.",
        tet:
            "Hili se imi presiza ajuda kona-ba saláriu la selu ka asidente servisu, no simu orientasaun pasu-ba-pasu toʼo preenche relatóriu.",
        ne: "तपाईंलाई नतिरेको तलब वा कार्यस्थल दुर्घटनाको बारेमा मद्दत चाहिन्छ कि छैन छान्नुहोस् र रिपोर्ट भर्नसम्म चरण-दर-चरण मार्गदर्शन प्राप्त गर्नुहोस्।",
        zh: '选择您需要处理欠薪还是工伤，逐步引导您完成申诉书或申请书的撰写。',
        vi: 'Chọn bạn cần hỗ trợ về nợ lương hay tai nạn lao động, được hướng dẫn từng bước đến khi hoàn thành đơn.',
        uz: "Toʻlanmagan ish haqi yoki ish joyidagi jarohat boʻyicha yordam kerakligini tanlang va hisobotni toʻldirishgacha boʻlgan bosqichma-bosqich koʻrsatmalarni oling.",
      ),
    ),
    OnboardingGuideModuleText(
      title: L10nText(
        ko: 'AI 챗봇',
        en: 'AI Chatbot',
        tr: "Yapay Zeka Sohbet Robotu",
        tg: "Чатботи зеҳни сунъӣ",
        fil: "AI Chatbot",
        ur: "اے آئی چیٹ بوٹ",
        th: "แชทบอท AI",
        ky: "Жасалма Интеллект Чатботу",
        km: "AI Chatbot",
        id: "Chatbot AI",
        si: "AI චැට්බෝට්",
        bn: "এআই চ্যাটবট",
        my: "AI Chatbot",
        mn: "Хиймэл оюун ухааны чатбот",
        lo: "AI Chatbot",
        tet: "Chatbot Intelijénsia Artifisiál",
        ne: "एआई च्याटबोट",
        zh: 'AI 聊天助手',
        vi: 'Chatbot AI',
        uz: "AI Chatbot",
      ),
      description: L10nText(
        ko: '백과사전 카드, 근무기록장, 임금계산기 등 필요한 기능과 관할 기관으로 연결하는 AI Agent 챗봇 도우미입니다.',
        en: 'An AI Agent assistant that connects users to the right features—such as encyclopedia cards, the work log, and the wage calculator—and to the relevant authorities.',
        tr: "Kullanıcıları ansiklopedi kartları, çalışma günlüğü ve ücret hesaplayıcı gibi doğru özelliklere ve ilgili yetkililere bağlayan bir Yapay Zeka Temsilcisi asistanı.",
        tg: "Ёвари агенти зеҳни сунъӣ, ки корбаронро ба хусусиятҳои дуруст, ба монанди кортҳои энсиклопедӣ, рӯзномаи корӣ ва ҳисобкунаки музди меҳнат, ва ба мақомоти дахлдор мепайвандад.",
        fil:
            "Isang AI Agent assistant na nag-uugnay sa mga user sa tamang feature tulad ng encyclopedia cards, work log, at wage calculator, at sa mga nauugnay na awtoridad.",
        ur: "ایک اے آئی ایجنٹ اسسٹنٹ جو صارفین کو درست خصوصیات جیسے انسائیکلوپیڈیا کارڈز، ورک لاگ، اور اجرت کیلکولیٹر، اور متعلقہ حکام سے جوڑتا ہے۔",
        th: "ผู้ช่วยตัวแทน AI ที่เชื่อมโยงผู้ใช้กับคุณสมบัติที่ถูกต้อง เช่น บัตรสารานุกรม บันทึกการทำงาน และเครื่องคำนวณค่าจ้าง รวมถึงเจ้าหน้าที่ที่เกี่ยวข้อง",
        ky: "Колдонуучуларды энциклопедиялык карталар, жумуш журналы жана эмгек акы калькулятору сыяктуу так функцияларга жана тиешелүү органдарга туташтырган Жасалма Интеллект Агентинин жардамчысы.",
        km: "ជំនួយការភ្នាក់ងារ AI ដែលភ្ជាប់អ្នកប្រើប្រាស់ទៅកាន់មុខងារត្រឹមត្រូវ និងអាជ្ញាធរពាក់ព័ន្ធ ដូចជាកាតសព្វវចនាធិប្បាយ កំណត់ហេតុការងារ និងម៉ាស៊ីនគិតប្រាក់ឈ្នួល។",
        id: "Asisten Agen AI yang menghubungkan pengguna ke fitur yang tepat seperti kartu ensiklopedia, buku kerja, dan kalkulator upah, serta otoritas terkait.",
        si: "විශ්වකෝෂ කාඩ්පත්, වැඩ ලොගය සහ වැටුප් කැල්කියුලේටරය වැනි නිවැරදි විශේෂාංග සහ අදාළ බලධාරීන් වෙත පරිශීලකයන් සම්බන්ධ කරන AI නියෝජිත සහායකයෙකි.",
        bn: "একটি এআই এজেন্ট সহকারী যা ব্যবহারকারীদের সঠিক বৈশিষ্ট্য যেমন এনসাইক্লোপিডিয়া কার্ড, কাজের ডায়েরি এবং বেতন ক্যালকুলেটর এবং প্রাসঙ্গিক কর্তৃপক্ষের সাথে সংযুক্ত করে।",
        my: "အသုံးပြုသူများကို စွယ်စုံကျမ်းကတ်များ၊ အလုပ်မှတ်တမ်းနှင့် လုပ်ခတွက်ချက်စက်ကဲ့သို့သော မှန်ကန်သည့်လုပ်ဆောင်ချက်များနှင့် သက်ဆိုင်ရာအာဏာပိုင်များထံ ချိတ်ဆက်ပေးသည့် AI Agent လက်ထောက်။",
        mn: "Хэрэглэгчдийг нэвтэрхий толь бичгийн картууд, ажлын бүртгэл, цалингийн тооцоолуур зэрэг зөв функцууд болон холбогдох албан тушаалтнуудтай холбодог хиймэл оюун ухааны төлөөлөгчийн туслах.",
        lo: "ຜູ້ຊ່ວຍຕົວແທນ AI ທີ່ເຊື່ອມຕໍ່ຜູ້ໃຊ້ກັບຄຸນສົມບັດທີ່ຖືກຕ້ອງເຊັ່ນ: ບັດສານຸກົມ, ບັນທຶກການເຮັດວຽກ, ແລະ ເຄື່ອງຄິດໄລ່ຄ່າຈ້າງ, ລວມທັງເຈົ້າໜ້າທີ່ທີ່ກ່ຽວຂ້ອງ.",
        tet:
            "Asistente Reprezentante Intelijénsia Artifisiál ida neʼebé liga utilizadór sira ba karakterístika loos hanesan karta ensiklopédia, rejistu servisu, no kalkuladór saláriu, no ba autoridade relevante sira.",
        ne: "प्रयोगकर्ताहरूलाई सही सुविधाहरू जस्तै विश्वकोश कार्डहरू, कार्य लग, र तलब क्यालकुलेटर, र सम्बन्धित अधिकारीहरूसँग जोड्ने एक एआई एजेन्ट सहायक।",
        zh: 'AI Agent 聊天助手，可将用户连接到百科卡片、工作记录本、工资计算器等所需功能及相关主管机构。',
        vi: 'Trợ lý chatbot AI Agent kết nối người dùng với các chức năng cần thiết như thẻ bách khoa, nhật ký làm việc, máy tính lương và các cơ quan có thẩm quyền.',
        uz: "Foydalanuvchilarni ensiklopediya kartalari, ish jurnali va ish haqi kalkulyatori kabi toʻgʻri funksiyalarga va tegishli organlarga bogʻlaydigan AI Agent yordamchisi.",
      ),
    ),
    OnboardingGuideModuleText(
      title: L10nText(
        ko: '근무기록장',
        en: 'Work Log',
        tr: "Çalışma Günlüğü",
        tg: "Рӯзномаи корӣ",
        fil: "Work Log",
        ur: "ورک لاگ",
        th: "บันทึกการทำงาน",
        ky: "Жумуш Журналы",
        km: "កំណត់ហេតុការងារ",
        id: "Buku Kerja",
        si: "වැඩ ලොගය",
        bn: "কাজের ডায়েরি",
        my: "အလုပ်မှတ်တမ်း",
        mn: "Ажлын бүртгэл",
        lo: "ບັນທຶກການເຮັດວຽກ",
        tet: "Rejistu Servisu",
        ne: "कार्य लग",
        zh: '工作记录本',
        vi: 'Nhật ký làm việc',
        uz: "Ish jurnali",
      ),
      description: L10nText(
        ko: '출퇴근, 휴게, GPS 위치 인증, 타임스탬프 사진, 버스카드 기록 등을 근로자 단독 계정에 축적합니다.',
        en: "Stores clock-in/out times, breaks, GPS verification, timestamped photos, transit-card records, and more in the worker's private account.",
        tr: "İşçinin özel hesabında giriş/çıkış saatlerini, molaları, GPS doğrulamasını, zaman damgalı fotoğrafları, toplu taşıma kartı kayıtlarını ve daha fazlasını saklar.",
        tg: "Вақтҳои дохилшавӣ/хориҷшавӣ, танаффусҳо, тасдиқи GPS, аксҳои мӯҳрдор, сабтҳои корти нақлиёти ҷамъиятӣ ва ғайраро дар ҳисоби шахсии коргар нигоҳ медорад.",
        fil:
            "Nag-iimbak ng oras ng pagpasok/paglabas, break, pag-verify ng GPS, mga larawang may timestamp, mga record ng card ng pampublikong transportasyon, at higit pa sa pribadong account ng manggagawa.",
        ur: "کارکن کے نجی اکاؤنٹ میں ان/آؤٹ اوقات، وقفے، GPS تصدیق، ٹائم اسٹیمپ شدہ تصاویر، پبلک ٹرانسپورٹ کارڈ کے ریکارڈ اور بہت کچھ محفوظ کرتا ہے۔",
        th: "จัดเก็บเวลาเข้า/ออก การพัก การยืนยัน GPS รูปภาพพร้อมประทับเวลา บันทึกบัตรโดยสารสาธารณะ และอื่น ๆ ในบัญชีส่วนตัวของพนักงาน",
        ky: "Жумушчунун жеке эсебинде кирүү/чыгуу убакыттарын, тыныгууларды, GPS текшерүүсүн, убакыт белгиси бар сүрөттөрдү, коомдук транспорт картасынын жазууларын жана башкаларды сактайт.",
        km: "រក្សាទុកម៉ោងចូល/ចេញ ការសម្រាក ការផ្ទៀងផ្ទាត់ GPS រូបថតដែលមានត្រាពេលវេលា កំណត់ត្រាកាតដឹកជញ្ជូនសាធារណៈ និងច្រើនទៀតនៅក្នុងគណនីឯកជនរបស់កម្មករ។",
        id: "Menyimpan waktu masuk/keluar, istirahat, verifikasi GPS, foto dengan stempel waktu, catatan kartu transportasi umum, dan lainnya di akun pribadi pekerja.",
        si: "සේවකයාගේ පුද්ගලික ගිණුමේ ඇතුල්වීමේ/පිටවීමේ වේලාවන්, විවේක, GPS සත්‍යාපනය, වේලා මුද්‍රා සහිත ඡායාරූප, පොදු ප්‍රවාහන කාඩ්පත් වාර්තා සහ තවත් දේ ගබඩා කරයි.",
        bn: "কর্মীর ব্যক্তিগত অ্যাকাউন্টে ইন/আউট সময়, বিরতি, জিপিএস যাচাইকরণ, টাইমস্ট্যাম্প করা ছবি, পাবলিক ট্রান্সপোর্ট কার্ড রেকর্ড এবং আরও অনেক কিছু সংরক্ষণ করে।",
        my: "အလုပ်သမား၏ ကိုယ်ပိုင်အကောင့်တွင် အဝင်/အထွက်အချိန်များ၊ အနားယူချိန်များ၊ GPS အတည်ပြုချက်၊ အချိန်တံဆိပ်တပ်ထားသော ဓာတ်ပုံများ၊ အများပြည်သူသယ်ယူပို့ဆောင်ရေးကတ်မှတ်တမ်းများနှင့် အခြားအရာများကို သိမ်းဆည်းထားသည်။",
        mn: "Ажилчны хувийн дансанд ирэх/гарах цаг, завсарлага, GPS баталгаажуулалт, цаг хугацааны тэмдэглэгээтэй зураг, нийтийн тээврийн картын бүртгэл болон бусад зүйлийг хадгална.",
        lo: "ເກັບຮັກສາເວລາເຂົ້າ/ອອກ, ເວລາພັກຜ່ອນ, ການຢືນຢັນ GPS, ຮູບພາບທີ່ມີການປະທັບຕາເວລາ, ບັນທຶກບັດຂົນສົ່ງສາທາລະນະ, ແລະ ອື່ນໆ ໃນບັນຊີສ່ວນຕົວຂອງແຮງງານ.",
        tet:
            "Guarda oras tama/sai traballadór nian, tempu deskansa, verifikasaun GPS, fotografia ho data no oras, rejistu karta transporte públiku, no seluk tan iha sira-nia konta privadu.",
        ne: "कामदारको निजी खातामा इन/आउट समय, ब्रेक, जीपीएस प्रमाणीकरण, समय-स्ट्याम्प गरिएका फोटोहरू, सार्वजनिक यातायात कार्ड रेकर्डहरू र अन्य धेरै कुराहरू भण्डारण गर्दछ।",
        zh: '将上下班、休息、GPS 位置认证、带时间戳的照片、交通卡记录等保存在劳动者的个人账户中。',
        vi: 'Lưu giờ vào/ra ca, thời gian nghỉ, xác minh vị trí GPS, ảnh có dấu thời gian, lịch sử thẻ giao thông và các dữ liệu khác trong tài khoản riêng của người lao động.',
        uz: "Ishga kelish/ketish vaqtlari, tanaffuslar, GPS tasdiqlash, vaqt belgisi qoʻyilgan fotosuratlar, tranzit-karta yozuvlari va boshqalarni ishchining shaxsiy hisobida saqlaydi.",
      ),
    ),
    OnboardingGuideModuleText(
      title: L10nText(
        ko: '임금계산기',
        en: 'Wage Calculator',
        tr: "Ücret Hesaplayıcı",
        tg: "Ҳисобкунаки музди меҳнат",
        fil: "Wage Calculator",
        ur: "اجرت کیلکولیٹر",
        th: "เครื่องคำนวณค่าจ้าง",
        ky: "Эмгек акы калькулятору",
        km: "ម៉ាស៊ីនគិតប្រាក់ឈ្នួល",
        id: "Kalkulator Upah",
        si: "වැටුප් කැල්කියුලේටරය",
        bn: "বেতন ক্যালকুলেটর",
        my: "လုပ်ခတွက်ချက်စက်",
        mn: "Цалингийн тооцоолуур",
        lo: "ເຄື່ອງຄິດໄລ່ຄ່າຈ້າງ",
        tet: "Kalkuladór Saláriu",
        ne: "तलब क्यालकुलेटर",
        zh: '工资计算器',
        vi: 'Máy tính lương',
        uz: "Ish haqi kalkulyatori",
      ),
      description: L10nText(
        ko: '최저임금과 사업장 규모를 반영해 주휴수당, 연장·야간·휴일수당 등을 계산합니다.',
        en: 'Calculates weekly holiday pay and overtime, night, and holiday-work premiums based on the minimum wage and workplace size.',
        tr: "Asgari ücrete ve işyeri büyüklüğüne göre haftalık tatil ücretini ve fazla mesai, gece ve tatil çalışması primlerini hesaplar.",
        tg: "Музди меҳнати рухсатии ҳафтаина ва мукофотпулиҳоро барои корҳои изофагӣ, шабона ва рӯзҳои ид дар асоси музди меҳнати ҳадди ақал ва андозаи ҷои кор ҳисоб мекунад.",
        fil:
            "Kinakalkula ang sahod sa holiday ng linggo at mga premium para sa overtime, gabi, at holiday work batay sa minimum na sahod at laki ng lugar ng trabaho.",
        ur: "کم از کم اجرت اور کام کی جگہ کے سائز کی بنیاد پر ہفتہ وار چھٹی کی اجرت اور اوور ٹائم، رات اور چھٹی کے کام کے پریمیم کا حساب لگاتا ہے۔",
        th: "คำนวณค่าจ้างวันหยุดประจำสัปดาห์และค่าล่วงเวลา ค่าทำงานกลางคืน และค่าทำงานในวันหยุดตามค่าแรงขั้นต่ำและขนาดของสถานที่ทำงาน",
        ky: "Минималдуу эмгек акыга жана жумуш ордунун көлөмүнө жараша жумалык эс алуу акысын жана ашыкча иштөө, түнкү жана майрам күндөрү иштөө үчүн кошумча төлөмдөрдү эсептейт.",
        km: "គណនាប្រាក់ឈ្នួលថ្ងៃឈប់សម្រាកប្រចាំសប្តាហ៍ និងបុព្វលាភសម្រាប់ការធ្វើការថែមម៉ោង ពេលយប់ និងថ្ងៃឈប់សម្រាក ដោយផ្អែកលើប្រាក់ឈ្នួលអប្បបរមា និងទំហំកន្លែងធ្វើការ។",
        id: "Menghitung upah libur mingguan dan premi untuk lembur, kerja malam, dan kerja libur berdasarkan upah minimum dan ukuran tempat kerja.",
        si: "අවම වැටුප සහ සේවා ස්ථානයේ ප්‍රමාණය මත පදනම්ව සතිපතා නිවාඩු වැටුප් සහ අතිකාල, රාත්‍රී සහ නිවාඩු වැඩ සඳහා වාරික ගණනය කරයි.",
        bn: "ন্যূনতম মজুরি এবং কর্মক্ষেত্রের আকার অনুযায়ী সাপ্তাহিক ছুটির বেতন এবং ওভারটাইম, রাতের এবং ছুটির দিনের কাজের জন্য প্রিমিয়াম গণনা করে।",
        my: "အနည်းဆုံးလုပ်ခနှင့် လုပ်ငန်းခွင်အရွယ်အစားအပေါ်အခြေခံ၍ အပတ်စဉ်အားလပ်ရက်လုပ်ခနှင့် အချိန်ပို၊ ညပိုင်းနှင့် အားလပ်ရက်အလုပ်အတွက် ပရီမီယံများကို တွက်ချက်သည်။",
        mn: "Хамгийн бага цалин болон ажлын байрны хэмжээнээс хамааран долоо хоногийн амралтын цалин, илүү цаг, шөнийн болон амралтын өдрийн ажлын нэмэгдлийг тооцно.",
        lo: "ຄິດໄລ່ຄ່າຈ້າງວັນພັກປະຈຳອາທິດ ແລະ ຄ່າລ່ວງເວລາ, ຄ່າເຮັດວຽກກາງຄືນ ແລະ ວັນພັກຕາມຄ່າແຮງງານຂັ້ນຕ່ຳ ແລະ ຂະໜາດຂອງບ່ອນເຮັດວຽກ.",
        tet:
            "Kalkula pagamentu feriadu semana-semana nian no prémiu ba oras estra, servisu kalan, no feriadu bazeia ba saláriu mínimu no tamañu fatin servisu nian.",
        ne: "न्यूनतम ज्याला र कार्यस्थलको आकार अनुसार साप्ताहिक बिदाको तलब र ओभरटाइम, रातको काम र बिदाको कामको लागि प्रिमियम गणना गर्दछ।",
        zh: '根据最低工资和用人单位规模，计算周休津贴、加班、夜间及节假日工作津贴等。',
        vi: 'Tính tiền nghỉ hằng tuần có lương, phụ cấp làm thêm giờ, làm đêm và làm ngày nghỉ dựa trên mức lương tối thiểu và quy mô nơi làm việc.',
        uz: "Haftalik bayram toʻlovi va ishdan tashqari, tungi va bayram kunlari ishlash uchun qoʻshimcha toʻlovlarni minimal ish haqi va ish joyi hajmiga qarab hisoblaydi.",
      ),
    ),
    OnboardingGuideModuleText(
      title: L10nText(
        ko: '임금체불·산재 네비게이터',
        en: 'Unpaid Wage & Workplace Injury Navigator',
        tr: "Ödenmemiş Ücret ve İş Kazası Rehberi",
        tg: "Дастур оид ба музди меҳнати пардохтнашуда ва садамаи корӣ",
        fil: "Gabay sa Hindi Nabayarang Sahod at Aksidente sa Trabaho",
        ur: "غیر ادا شدہ اجرت اور کام کے حادثے کی گائیڈ",
        th: "คู่มือค่าจ้างค้างจ่ายและอุบัติเหตุจากการทำงาน",
        ky: "Төлөнбөгөн эмгек акы жана өндүрүштүк кырсык боюнча колдонмо",
        km: "មគ្គុទ្ទេសក៍ប្រាក់ឈ្នួលមិនទាន់បានបង់ និងគ្រោះថ្នាក់ការងារ",
        id: "Panduan Upah Belum Dibayar & Kecelakaan Kerja",
        si: "ගෙවා නොමැති වැටුප් සහ කාර්මික අනතුරු මාර්ගෝපදේශය",
        bn: "বকেয়া বেতন এবং কর্মক্ষেত্রে আঘাতের নির্দেশিকা",
        my: "လုပ်ခမရရှိခြင်းနှင့် လုပ်ငန်းခွင်ထိခိုက်မှု လမ်းညွှန်",
        mn: "Цалин хөлсөө аваагүй болон үйлдвэрлэлийн ослын гарын авлага",
        lo: "ຄູ່ມືຄ່າຈ້າງທີ່ຄ້າງຈ່າຍ ແລະ ອຸບັດຕິເຫດໃນບ່ອນເຮັດວຽກ",
        tet: "Gia Saláriu La Selu no Asidente Servisu",
        ne: "नतिरेको तलब र कार्यस्थल दुर्घटना मार्गदर्शन",
        zh: '欠薪与工伤导航',
        vi: 'Điều hướng nợ lương và tai nạn lao động',
        uz: "Toʻlanmagan ish haqi va ish joyidagi jarohat navigatori",
      ),
      description: L10nText(
        ko: '임금체불과 산업재해 피해 발생 시 진정 및 신청 절차를 단계별로 안내합니다.',
        en: 'Provides step-by-step guidance for filing an unpaid-wage complaint or an occupational-accident claim.',
        tr: "Ödenmemiş ücret şikayeti veya iş kazası talebi için adım adım rehberlik sağlar.",
        tg: "Дастури қадам ба қадамро барои шикоят оид ба музди меҳнати пардохтнашуда ё талаби садамаи корӣ пешниҳод мекунад.",
        fil:
            "Nagbibigay ng sunud-sunod na gabay para sa reklamo sa hindi nabayarang sahod o claim sa aksidente sa trabaho.",
        ur: "غیر ادا شدہ اجرت کی شکایت یا کام کے حادثے کے دعوے کے لیے قدم بہ قدم رہنمائی فراہم کرتا ہے۔",
        th: "ให้คำแนะนำทีละขั้นตอนสำหรับการร้องเรียนค่าจ้างค้างจ่ายหรือการเรียกร้องค่าสินไหมทดแทนจากอุบัติเหตุจากการทำงาน",
        ky: "Төлөнбөгөн эмгек акы боюнча арыз же өндүрүштүк кырсык боюнча доо арыз үчүн кадам-кадам көрсөтмөлөрдү берет.",
        km: "ផ្តល់ការណែនាំជាជំហានៗសម្រាប់ការដាក់ពាក្យបណ្តឹងប្រាក់ឈ្នួលមិនទាន់បានបង់ ឬការទាមទារសំណងគ្រោះថ្នាក់ការងារ។",
        id: "Memberikan panduan langkah demi langkah untuk pengajuan keluhan upah yang belum dibayar atau klaim kecelakaan kerja.",
        si: "ගෙවා නොමැති වැටුප් පැමිණිල්ලක් හෝ කාර්මික අනතුරු හිමිකම් පෑමක් සඳහා පියවරෙන් පියවර මඟ පෙන්වීමක් සපයයි.",
        bn: "বকেয়া বেতনের অভিযোগ বা কর্মক্ষেত্রে আঘাতের দাবির জন্য ধাপে ধাপে নির্দেশনা প্রদান করে।",
        my: "လုပ်ခမရရှိခြင်းတိုင်ကြားစာ သို့မဟုတ် လုပ်ငန်းခွင်ထိခိုက်မှုတောင်းဆိုမှုအတွက် အဆင့်ဆင့်လမ်းညွှန်မှုကို ပေးသည်။",
        mn: "Цалин хөлсөө аваагүй тухай гомдол эсвэл үйлдвэрлэлийн ослын нэхэмжлэлийг гаргах алхам алхмаар зааварчилгаа өгнө.",
        lo: "ໃຫ້ຄຳແນະນຳເທື່ອລະຂັ້ນຕອນສຳລັບການຮ້ອງຮຽນຄ່າຈ້າງທີ່ຄ້າງຈ່າຍ ຫຼື ການຮຽກຮ້ອງຄ່າຊົດເຊີຍອຸບັດຕິເຫດໃນບ່ອນເຮັດວຽກ.",
        tet:
            "Fó orientasaun pasu-ba-pasu ba keixa saláriu la selu ka reklamasaun asidente servisu.",
        ne: "नतिरेको तलबको गुनासो वा कार्यस्थल दुर्घटनाको दावीको लागि चरण-दर-चरण मार्गदर्शन प्रदान गर्दछ।",
        zh: '发生欠薪或工伤损害时，分步骤指导申诉及申请流程。',
        vi: 'Hướng dẫn từng bước quy trình khiếu nại nợ lương và yêu cầu giải quyết tai nạn lao động.',
        uz: "Toʻlanmagan ish haqi shikoyatini yoki kasbiy baxtsiz hodisa daʼvosini topshirish boʻyicha bosqichma-bosqich koʻrsatmalar beradi.",
      ),
    ),
  ];

  static const creatorTitle = L10nText(
    ko: '제작자',
    en: 'Created by',
    tr: "Oluşturan",
    tg: "Аз ҷониби",
    fil: "Nilikha ng",
    ur: "تخلیق کردہ",
    th: "สร้างโดย",
    ky: "Түзүүчүлөр",
    km: "បង្កើតដោយ",
    id: "Dibuat oleh",
    si: "නිර්මාණය කළේ",
    bn: "তৈরি করেছেন",
    my: "ဖန်တီးသူ",
    mn: "Бүтээсэн",
    lo: "ສ້າງໂດຍ",
    tet: "Kriadu husi",
    ne: "द्वारा सिर्जना गरिएको",
    zh: '制作团队',
    vi: 'Đơn vị phát triển',
    uz: "Yaratuvchilar",
  );

  static const creatorNames = L10nText(
    ko: '아주대학교 학생: 이건영, 정수환, 김형우',
    en: 'Ajou University students: 이건영, 정수환, 김형우',
    tr: "Ajou Üniversitesi öğrencileri: 이건영, 정수환, 김형우",
    tg: "Донишҷӯёни Донишгоҳи Аҷу: 이건영, 정수환, 김형우",
    fil: "Mga mag-aaral ng Ajou University: 이건영, 정수환, 김형우",
    ur: "اجو یونیورسٹی کے طلباء: 이건영, 정수환, 김형우",
    th: "นักศึกษาจากมหาวิทยาลัยอาจู: 이건영, 정수환, 김형우",
    ky: "Ажу университетинин студенттери: 이건영, 정수환, 김형우",
    km: "និស្សិតសាកលវិទ្យាល័យ Ajou៖ 이건영, 정수환, 김형우",
    id: "Mahasiswa Universitas Ajou: 이건영, 정수환, 김형우",
    si: "අජූ විශ්ව විද්‍යාලයේ සිසුන්: 이건영, 정수환, 김형우",
    bn: "আজু বিশ্ববিদ্যালয়ের ছাত্ররা: লি জিওন-ইয়ং, জং সু-হোয়ান, কিম হিউং-উ",
    my: "Ajou တက္ကသိုလ်ကျောင်းသားများ- 이건영, 정수환, 김형우",
    mn: "Ажугийн их сургуулийн оюутнууд: 이건영, 정수환, 김형우",
    lo: "ນັກສຶກສາຈາກມະຫາວິທະຍາໄລ Ajou: 이건영, 정수환, 김형우",
    tet: "Estudante Ajou University: 이건영, 정수환, 김형우",
    ne: "आजु विश्वविद्यालयका विद्यार्थीहरू: 이건영, 정수환, 김형우",
    zh: '亚洲大学学生：이건영、정수환、김형우',
    vi: 'Sinh viên Đại học Ajou: 이건영, 정수환, 김형우',
    uz: "Ajou universiteti talabalari: 이건영, 정수환, 김형우",
  );
}
