import '../../../core/app_language.dart';

/// 회원가입 국적 선택 목록. 고용허가제(EPS) 16개 협약국을 상단에 두고, 그 외
/// 유학·특정활동·방문취업 비자에서 자주 나오는 국적을 이어 붙였다 — 전체
/// ISO 국가 목록(약 200개)을 다 넣는 대신, 이 앱의 실제 이용자층에 맞춰 범위를
/// 좁혔다. 목록에 없으면 "기타"를 고르면 된다.
class Country {
  const Country({required this.code, required this.name});

  /// ISO 3166-1 alpha-2 코드.
  final String code;
  final L10nText name;
}

const countries = <Country>[
  // --- 고용허가제(EPS) 16개 협약국 ---
  Country(
    code: 'PH',
    name: L10nText(
      ko: '필리핀',
      en: 'Philippines',
      tr: "Filipinler",
      tg: "Филиппин",
      fil: "Pilipinas",
      ur: "فلپائن",
      th: "ฟิลิปปินส์",
      ky: "Филиппиндер",
      km: "ហ្វីលីពីន",
      id: "Filipina",
      si: "පිලිපීනය",
      bn: "ফিলিপাইন",
      my: "ဖိလစ်ပိုင်",
      mn: "Филиппин",
      lo: "ຟີລິບປິນ",
      tet: "Filipina",
      ne: "फिलिपिन्स",
      zh: '菲律宾',
      vi: 'Philippines',
      uz: "Filippin",
    ),
  ),
  Country(
    code: 'MN',
    name: L10nText(
      ko: '몽골',
      en: 'Mongolia',
      tr: "Moğolistan",
      tg: "Муғулистон",
      fil: "Mongolia",
      ur: "منگولیا",
      th: "มองโกเลีย",
      ky: "Монголия",
      km: "ម៉ុងហ្គោលី",
      id: "Mongolia",
      si: "මොංගෝලියාව",
      bn: "মঙ্গোলিয়া",
      my: "မွန်ဂိုလီးယား",
      mn: "Монгол",
      lo: "ມົງໂກລີ",
      tet: "Mongólia",
      ne: "मंगोलिया",
      zh: '蒙古',
      vi: 'Mông Cổ',
      uz: "Moʻgʻuliston",
    ),
  ),
  Country(
    code: 'LK',
    name: L10nText(
      ko: '스리랑카',
      en: 'Sri Lanka',
      tr: "Sri Lanka",
      tg: "Шри-Ланка",
      fil: "Sri Lanka",
      ur: "سری لنکا",
      th: "ศรีลังกา",
      ky: "Шри-Ланка",
      km: "ស្រីលង្កា",
      id: "Sri Lanka",
      si: "ශ්‍රී ලංකාව",
      bn: "শ্রীলঙ্কা",
      my: "သီရိလင်္ကာ",
      mn: "Шри Ланка",
      lo: "ສີລັງກາ",
      tet: "Sri Lanka",
      ne: "श्रीलंका",
      zh: '斯里兰卡',
      vi: 'Sri Lanka',
      uz: "Shri-Lanka",
    ),
  ),
  Country(
    code: 'VN',
    name: L10nText(
      ko: '베트남',
      en: 'Vietnam',
      tr: "Vietnam",
      tg: "Ветнам",
      fil: "Vietnam",
      ur: "ویتنام",
      th: "เวียดนาม",
      ky: "Вьетнам",
      km: "វៀតណាម",
      id: "Vietnam",
      si: "වියට්නාමය",
      bn: "ভিয়েতনাম",
      my: "ဗီယက်နမ်",
      mn: "Вьетнам",
      lo: "ຫວຽດນາມ",
      tet: "Vietname",
      ne: "भियतनाम",
      zh: '越南',
      vi: 'Việt Nam',
      uz: "Vyetnam",
    ),
  ),
  Country(
    code: 'TH',
    name: L10nText(
      ko: '태국',
      en: 'Thailand',
      tr: "Tayland",
      tg: "Таиланд",
      fil: "Thailand",
      ur: "تھائی لینڈ",
      th: "ไทย",
      ky: "Таиланд",
      km: "ថៃ",
      id: "Thailand",
      si: "තායිලන්තය",
      bn: "থাইল্যান্ড",
      my: "ထိုင်း",
      mn: "Тайланд",
      lo: "ໄທ",
      tet: "Tailándia",
      ne: "थाइल्याण्ड",
      zh: '泰国',
      vi: 'Thái Lan',
      uz: "Tailand",
    ),
  ),
  Country(
    code: 'ID',
    name: L10nText(
      ko: '인도네시아',
      en: 'Indonesia',
      tr: "Endonezya",
      tg: "Индонезия",
      fil: "Indonesia",
      ur: "انڈونیشیا",
      th: "อินโดนีเซีย",
      ky: "Индонезия",
      km: "ឥណ្ឌូនេស៊ី",
      id: "Indonesia",
      si: "ඉන්දුනීසියාව",
      bn: "ইন্দোনেশিয়া",
      my: "အင်ဒိုနီးရှား",
      mn: "Индонез",
      lo: "ອິນໂດເນເຊຍ",
      tet: "Indonézia",
      ne: "इन्डोनेसिया",
      zh: '印度尼西亚',
      vi: 'Indonesia',
      uz: "Indoneziya",
    ),
  ),
  Country(
    code: 'UZ',
    name: L10nText(
      ko: '우즈베키스탄',
      en: 'Uzbekistan',
      tr: "Özbekistan",
      tg: "Ӯзбекистон",
      fil: "Uzbekistan",
      ur: "ازبکستان",
      th: "อุซเบกิสถาน",
      ky: "Өзбекстан",
      km: "អ៊ូសបេគីស្ថាន",
      id: "Uzbekistan",
      si: "උස්බෙකිස්තානය",
      bn: "উজবেকিস্তান",
      my: "ဥဇဘက်ကစ္စတန်",
      mn: "Узбекистан",
      lo: "ອຸສເບກິດສະຖານ",
      tet: "Uzbekistaun",
      ne: "उज्बेकिस्तान",
      zh: '乌兹别克斯坦',
      vi: 'Uzbekistan',
      uz: "Oʻzbekiston",
    ),
  ),
  Country(
    code: 'PK',
    name: L10nText(
      ko: '파키스탄',
      en: 'Pakistan',
      tr: "Pakistan",
      tg: "Покистон",
      fil: "Pakistan",
      ur: "پاکستان",
      th: "ปากีสถาน",
      ky: "Пакистан",
      km: "ប៉ាគីស្ថាន",
      id: "Pakistan",
      si: "පාකිස්තානය",
      bn: "পাকিস্তান",
      my: "ပါကစ္စတန်",
      mn: "Пакистан",
      lo: "ປາກິດສະຖານ",
      tet: "Pakistaun",
      ne: "पाकिस्तान",
      zh: '巴基斯坦',
      vi: 'Pakistan',
      uz: "Pokiston",
    ),
  ),
  Country(
    code: 'KH',
    name: L10nText(
      ko: '캄보디아',
      en: 'Cambodia',
      tr: "Kamboçya",
      tg: "Камбоҷа",
      fil: "Cambodia",
      ur: "کمبوڈیا",
      th: "กัมพูชา",
      ky: "Камбоджа",
      km: "កម្ពុជា",
      id: "Kamboja",
      si: "කාම්බෝජය",
      bn: "কম্বোডিয়া",
      my: "ကမ္ဘောဒီးယား",
      mn: "Камбож",
      lo: "ກຳປູເຈຍ",
      tet: "Kamboja",
      ne: "कम्बोडिया",
      zh: '柬埔寨',
      vi: 'Campuchia',
      uz: "Kambodja",
    ),
  ),
  Country(
    code: 'BD',
    name: L10nText(
      ko: '방글라데시',
      en: 'Bangladesh',
      tr: "Bangladeş",
      tg: "Бангладеш",
      fil: "Bangladesh",
      ur: "بنگلہ دیش",
      th: "บังกลาเทศ",
      ky: "Бангладеш",
      km: "បង់ក្លាដែស",
      id: "Bangladesh",
      si: "බංග්ලාදේශය",
      bn: "বাংলাদেশ",
      my: "ဘင်္ဂလားဒေ့ရှ်",
      mn: "Бангладеш",
      lo: "ບັງກລາເດັສ",
      tet: "Bangladexe",
      ne: "बंगलादेश",
      zh: '孟加拉国',
      vi: 'Bangladesh',
      uz: "Bangladesh",
    ),
  ),
  Country(
    code: 'NP',
    name: L10nText(
      ko: '네팔',
      en: 'Nepal',
      tr: "Nepal",
      tg: "Непал",
      fil: "Nepal",
      ur: "نیپال",
      th: "เนปาล",
      ky: "Непал",
      km: "នេប៉ាល់",
      id: "Nepal",
      si: "නේපාලය",
      bn: "নেপাল",
      my: "နီပေါ",
      mn: "Балба",
      lo: "ເນປານ",
      tet: "Nepál",
      ne: "नेपाल",
      zh: '尼泊尔',
      vi: 'Nepal',
      uz: "Nepal",
    ),
  ),
  Country(
    code: 'MM',
    name: L10nText(
      ko: '미얀마',
      en: 'Myanmar',
      tr: "Myanmar",
      tg: "Мянма",
      fil: "Myanmar",
      ur: "میانمار",
      th: "เมียนมา",
      ky: "Мьянма",
      km: "មីយ៉ាន់ម៉ា",
      id: "Myanmar",
      si: "මියන්මාරය",
      bn: "মায়ানমার",
      my: "မြန်မာ",
      mn: "Мьянмар",
      lo: "ມຽນມາ",
      tet: "Mianmar",
      ne: "म्यानमार",
      zh: '缅甸',
      vi: 'Myanmar',
      uz: "Myanma",
    ),
  ),
  Country(
    code: 'KG',
    name: L10nText(
      ko: '키르기스스탄',
      en: 'Kyrgyzstan',
      tr: "Kırgızistan",
      tg: "Қирғизистон",
      fil: "Kyrgyzstan",
      ur: "کرغزستان",
      th: "คีร์กีซสถาน",
      ky: "Кыргызстан",
      km: "កៀហ្ស៊ីស៊ីស្ថាន",
      id: "Kirgizstan",
      si: "කිර්ගිස්තානය",
      bn: "কিরগিজস্তান",
      my: "ကာဂျစ္စတန်",
      mn: "Киргизстан",
      lo: "ກີກິດສະຖານ",
      tet: "Kirgizistaun",
      ne: "किर्गिस्तान",
      zh: '吉尔吉斯斯坦',
      vi: 'Kyrgyzstan',
      uz: "Qirgʻiziston",
    ),
  ),
  Country(
    code: 'TL',
    name: L10nText(
      ko: '동티모르',
      en: 'Timor-Leste',
      tr: "Doğu Timor",
      tg: "Тимори Шарқӣ",
      fil: "Silangang Timor",
      ur: "مشرقی تیمور",
      th: "ติมอร์ตะวันออก",
      ky: "Чыгыш Тимор",
      km: "ទីម័រខាងកើត",
      id: "Timor Leste",
      si: "නැගෙනහිර ටිමෝරය",
      bn: "পূর্ব তিমুর",
      my: "အရှေ့တီမော",
      mn: "Зүүн Тимор",
      lo: "ຕີມໍຕາເວັນອອກ",
      tet: "Timor-Leste",
      ne: "पूर्वी टिमोर",
      zh: '东帝汶',
      vi: 'Đông Timor',
      uz: "Sharqiy Timor",
    ),
  ),
  Country(
    code: 'LA',
    name: L10nText(
      ko: '라오스',
      en: 'Laos',
      tr: "Laos",
      tg: "Лаос",
      fil: "Laos",
      ur: "لاؤس",
      th: "ลาว",
      ky: "Лаос",
      km: "ឡាវ",
      id: "Laos",
      si: "ලාඕසය",
      bn: "লাওস",
      my: "လာအို",
      mn: "Лаос",
      lo: "ລາວ",
      tet: "Laos",
      ne: "लाओस",
      zh: '老挝',
      vi: 'Lào',
      uz: "Laos",
    ),
  ),
  Country(
    code: 'PG',
    name: L10nText(
      ko: '파푸아뉴기니',
      en: 'Papua New Guinea',
      tr: "Papua Yeni Gine",
      tg: "Папуа Гвинеяи Нав",
      fil: "Papua New Guinea",
      ur: "پاپوا نیو گنی",
      th: "ปาปัวนิวกินี",
      ky: "Папуа Жаңы Гвинея",
      km: "ប៉ាពួញូហ្គីណេ",
      id: "Papua Nugini",
      si: "පපුවා නිව් ගිනියාව",
      bn: "পাপুয়া নিউ গিনি",
      my: "ပါပူဝါနယူးဂီနီ",
      mn: "Папуа Шинэ Гвиней",
      lo: "ປາປົວນິວກີນີ",
      tet: "Papua Giné Foun",
      ne: "पपुवा न्यु गिनी",
      zh: '巴布亚新几内亚',
      vi: 'Papua New Guinea',
      uz: "Papua Yangi Gvineyasi",
    ),
  ),
  // --- 그 외 자주 나오는 국적(유학·특정활동·방문취업 등) ---
  Country(
    code: 'CN',
    name: L10nText(
      ko: '중국',
      en: 'China',
      tr: "Çin",
      tg: "Чин",
      fil: "Tsina",
      ur: "چین",
      th: "จีน",
      ky: "Кытай",
      km: "ចិន",
      id: "Tiongkok",
      si: "චීනය",
      bn: "চীন",
      my: "တရုတ်",
      mn: "Хятад",
      lo: "ຈີນ",
      tet: "Xina",
      ne: "चीन",
      zh: '中国',
      vi: 'Trung Quốc',
      uz: "Xitoy",
    ),
  ),
  Country(
    code: 'TW',
    name: L10nText(
      ko: '대만',
      en: 'Taiwan',
      tr: "Tayvan",
      tg: "Тайван",
      fil: "Taiwan",
      ur: "تائیوان",
      th: "ไต้หวัน",
      ky: "Тайвань",
      km: "តៃវ៉ាន់",
      id: "Taiwan",
      si: "තායිවානය",
      bn: "তাইওয়ান",
      my: "ထိုင်ဝမ်",
      mn: "Тайвань",
      lo: "ໄຕ້ຫວັນ",
      tet: "Taiwán",
      ne: "ताइवान",
      zh: '台湾',
      vi: 'Đài Loan',
      uz: "Tayvan",
    ),
  ),
  Country(
    code: 'JP',
    name: L10nText(
      ko: '일본',
      en: 'Japan',
      tr: "Japonya",
      tg: "Ҷопон",
      fil: "Japan",
      ur: "جاپان",
      th: "ญี่ปุ่น",
      ky: "Жапония",
      km: "ជប៉ុន",
      id: "Jepang",
      si: "ජපානය",
      bn: "জাপান",
      my: "ဂျပန်",
      mn: "Япон",
      lo: "ຍີ່ປຸ່ນ",
      tet: "Japaun",
      ne: "जापान",
      zh: '日本',
      vi: 'Nhật Bản',
      uz: "Yaponiya",
    ),
  ),
  Country(
    code: 'IN',
    name: L10nText(
      ko: '인도',
      en: 'India',
      tr: "Hindistan",
      tg: "Ҳиндустон",
      fil: "India",
      ur: "بھارت",
      th: "อินเดีย",
      ky: "Индия",
      km: "ឥណ្ឌា",
      id: "India",
      si: "ඉන්දියාව",
      bn: "ভারত",
      my: "အိန္ဒိယ",
      mn: "Энэтхэг",
      lo: "ອິນເດຍ",
      tet: "Índia",
      ne: "भारत",
      zh: '印度',
      vi: 'Ấn Độ',
      uz: "Hindiston",
    ),
  ),
  Country(
    code: 'KZ',
    name: L10nText(
      ko: '카자흐스탄',
      en: 'Kazakhstan',
      tr: "Kazakistan",
      tg: "Қазоқистон",
      fil: "Kazakhstan",
      ur: "قازقستان",
      th: "คาซัคสถาน",
      ky: "Казакстан",
      km: "កាហ្សាក់ស្ថាន",
      id: "Kazakhstan",
      si: "කසකස්තානය",
      bn: "কাজাখস্তান",
      my: "ကာဇက်စတန်",
      mn: "Казахстан",
      lo: "ຄາຊັກສະຖານ",
      tet: "Kazakistaun",
      ne: "कजाकस्तान",
      zh: '哈萨克斯坦',
      vi: 'Kazakhstan',
      uz: "Qozogʻiston",
    ),
  ),
  Country(
    code: 'RU',
    name: L10nText(
      ko: '러시아',
      en: 'Russia',
      tr: "Rusya",
      tg: "Русия",
      fil: "Russia",
      ur: "روس",
      th: "รัสเซีย",
      ky: "Орусия",
      km: "រុស្ស៊ី",
      id: "Rusia",
      si: "රුසියාව",
      bn: "রাশিয়া",
      my: "ရုရှား",
      mn: "Орос",
      lo: "ຣັດເຊຍ",
      tet: "Rúsia",
      ne: "रुस",
      zh: '俄罗斯',
      vi: 'Nga',
      uz: "Rossiya",
    ),
  ),
  Country(
    code: 'US',
    name: L10nText(
      ko: '미국',
      en: 'United States',
      tr: "Amerika Birleşik Devletleri",
      tg: "Иёлоти Муттаҳидаи Амрико",
      fil: "Estados Unidos",
      ur: "ریاستہائے متحدہ امریکہ",
      th: "สหรัฐอเมริกา",
      ky: "Америка Кошмо Штаттары",
      km: "សហរដ្ឋអាមេរិក",
      id: "Amerika Serikat",
      si: "එක්සත් ජනපදය",
      bn: "মার্কিন যুক্তরাষ্ট্র",
      my: "အမေရိကန်ပြည်ထောင်စု",
      mn: "Америкийн Нэгдсэн Улс",
      lo: "ສະຫະລັດອາເມລິກາ",
      tet: "Estadu Unidus Amérika",
      ne: "संयुक्त राज्य अमेरिका",
      zh: '美国',
      vi: 'Hoa Kỳ',
      uz: "Amerika Qoʻshma Shtatlari",
    ),
  ),
  Country(
    code: 'CA',
    name: L10nText(
      ko: '캐나다',
      en: 'Canada',
      tr: "Kanada",
      tg: "Канада",
      fil: "Canada",
      ur: "کینیڈا",
      th: "แคนาดา",
      ky: "Канада",
      km: "កាណាដា",
      id: "Kanada",
      si: "කැනඩාව",
      bn: "কানাডা",
      my: "ကနေဒါ",
      mn: "Канад",
      lo: "ການາດາ",
      tet: "Kanadá",
      ne: "क्यानाडा",
      zh: '加拿大',
      vi: 'Canada',
      uz: "Kanada",
    ),
  ),
  Country(
    code: 'AU',
    name: L10nText(
      ko: '호주',
      en: 'Australia',
      tr: "Avustralya",
      tg: "Австралия",
      fil: "Australia",
      ur: "آسٹریلیا",
      th: "ออสเตรเลีย",
      ky: "Австралия",
      km: "អូស្ត្រាលី",
      id: "Australia",
      si: "ඕස්ට්‍රේලියාව",
      bn: "অস্ট্রেলিয়া",
      my: "ဩစတြေးလျ",
      mn: "Австрали",
      lo: "ອົດສະຕຣາລີ",
      tet: "Austrália",
      ne: "अस्ट्रेलिया",
      zh: '澳大利亚',
      vi: 'Úc',
      uz: "Avstraliya",
    ),
  ),
  Country(
    code: 'GB',
    name: L10nText(
      ko: '영국',
      en: 'United Kingdom',
      tr: "Birleşik Krallık",
      tg: "Подшоҳии Муттаҳида",
      fil: "United Kingdom",
      ur: "متحدہ بادشاہت",
      th: "สหราชอาณาจักร",
      ky: "Бириккен Королдук",
      km: "ចក្រភពអង់គ្លេស",
      id: "Britania Raya",
      si: "එක්සත් රාජධානිය",
      bn: "যুক্তরাজ্য",
      my: "ယူနိုက်တက်ကင်းဒမ်း",
      mn: "Их Британи",
      lo: "ສະຫະລາດຊະອານາຈັກ",
      tet: "Reinu Unidu",
      ne: "संयुक्त अधिराज्य",
      zh: '英国',
      vi: 'Anh',
      uz: "Birlashgan Qirollik",
    ),
  ),
  Country(
    code: 'FR',
    name: L10nText(
      ko: '프랑스',
      en: 'France',
      tr: "Fransa",
      tg: "Фаронса",
      fil: "France",
      ur: "فرانس",
      th: "ฝรั่งเศส",
      ky: "Франция",
      km: "បារាំង",
      id: "Prancis",
      si: "ප්‍රංශය",
      bn: "ফ্রান্স",
      my: "ပြင်သစ်",
      mn: "Франц",
      lo: "ຝຣັ່ງ",
      tet: "Fransa",
      ne: "फ्रान्स",
      zh: '法国',
      vi: 'Pháp',
      uz: "Fransiya",
    ),
  ),
  Country(
    code: 'DE',
    name: L10nText(
      ko: '독일',
      en: 'Germany',
      tr: "Almanya",
      tg: "Олмон",
      fil: "Germany",
      ur: "جرمنی",
      th: "เยอรมนี",
      ky: "Германия",
      km: "អាល្លឺម៉ង់",
      id: "Jerman",
      si: "ජර්මනිය",
      bn: "জার্মানি",
      my: "ဂျာမနီ",
      mn: "Герман",
      lo: "ເຢຍລະມັນ",
      tet: "Alemaña",
      ne: "जर्मनी",
      zh: '德国',
      vi: 'Đức',
      uz: "Germaniya",
    ),
  ),
  // --- 목록에 없을 때 ---
  Country(
    code: 'ETC',
    name: L10nText(
      ko: '기타',
      en: 'Other',
      tr: "Diğer",
      tg: "Дигар",
      fil: "Iba pa",
      ur: "دیگر",
      th: "อื่น ๆ",
      ky: "Башка",
      km: "ផ្សេងៗ",
      id: "Lainnya",
      si: "වෙනත්",
      bn: "অন্যান্য",
      my: "အခြား",
      mn: "Бусад",
      lo: "ອື່ນໆ",
      tet: "Seluk",
      ne: "अन्य",
      zh: '其他',
      vi: 'Khác',
      uz: "Boshqa",
    ),
  ),
];
